### ISSUE TITLE
Implementation guide and template for plugins

### ISSUE THREAD

**Issue by otm** [wout/svg.js#149]
I would like to propose an implementation guide and template for official plugins.

The template for plugins could contain a reference for directory layout, build, testing and documentation.

The plugin system is so good and that would let the svg.js core to remain small and place some of the sugar in plugins instead.

**Comment by dotnetCarpenter** [comment]
@Fuzzyma where is the guide?

**Comment by Fuzzyma** [comment]
The "Extending functionality" section from the docs explains how to do it. 
There is nothing more to say because it's just that simple.
