### ISSUE TITLE
Safari 6 - Centring Paths

### ISSUE THREAD

**Issue by MathieuLoutre** [wout/svg.js#175]
This might be hard for you to test/replicate but I've identified a problem with the centring of paths on Safari 6.

`.center()` calls `.cx()` and '.cy()' but the end result is as if only `.cy()` has been called or rather, `.cx()` is called but its effect is not taken into account by `.cy()`.
From what I've seen, it seems to be a problem in the `.bbox()` calculation of the element. The `.bbox()` returned in `.cy()` is the same as the one returned in `.cx()` whereas on Safari 7 you can clearly see that the `x` in the `bbox` has been changed when `.cy()` is called.

Now I'm wondering where does the problem come from. Is it Safari which has a bug when calculating its `bbox` (and it seems to do it 'natively' in both cases)? `.cx()` when called alone seems to do its job visually, but the movement doesn't seem to impact the `bbox()` calculations.

Would there be a way around it if it's a bug in Safari?

The path is created within a group. The group is not positioned. Any other standard thing inside (like circle) doesn't seem to suffer from the problem.

Also, I'm using https://github.com/wout/svg.js/commit/f3b9e808601e8aa250b9373447527ca67ba75ec4 because of #176.

**Comment by Fuzzyma** [comment]
@MatthieuLoutre - is this still ab issue?

**Comment by MathieuLoutre** [comment]
I have no way to test things on iOS 6 unfortunately but I think that iOS 7 & 8's market shares are high enough that it could be disregarded.
