### ISSUE TITLE
IE10 and 9 with animations: block of white space at end of document, animation altering length of window

### ISSUE THREAD

**Issue by scottbirdsey** [wout/svg.js#191]
For IE9 and 10 (haven't tested in 11):

I'm seeing a block of whitespace added on both the demo page - http://svgjs.com/test/, as well as my own implementation that uses animation. I did notice that there's an SVG element created after the svg.js scripting, but have set that to position: absolute / left: -9999px to hide. This solved the problem for all browsers but IE, which still has large whitespace.

Additionally with an animation moving vertically I'm seeing the document height being altered as the animation moves. This is most easily seen by the scrollbar position moving with the animations.

Any workarounds for this? Is this just something inherent in IE9/10 that will occur with any SVG animations going along the Y-coordinate?

**Comment by Fuzzyma** [comment]
@scottbirdsey is this still a problem? plus could you create an example-fiddle please?
