### ISSUE TITLE
When elements are removed (or their parent is cleared), the removed element doesn't also remove clippath elements it created

### ISSUE THREAD

**Issue by mhintz** [wout/svg.js#212]
Hello, great library! The API is very slick, and pretty intuitive.

I'm using it for a project, and have noticed something somewhat odd. When I clip an element, and then later remove the clipped element, an empty clippath tag is left over in the top-level defs tag. I'm not sure if this is a feature or a bug, but I thought I'd bring it up. I made a jsfiddle that demonstrates this happening:

http://jsfiddle.net/4x7jx/1/

Cheers, and thanks again for making a great library!

Mark

**Comment by Fuzzyma** [comment]
I am not quite sure on how to fix this. When you remove one element which is clipped you still can put it on the svg again and it shall stay clipped. So you cant really remove the clip-path.
Any idea on how to solve that?

Anyway - in your example you just used Clip it in the wrog way.
When you want to reuse a clip-path do this:

    var mask = svg.clip().add(svg.rect(300, 150));

    // later
    circle.clipWith(mask)

That adds the clipPath to the defs at initialisation and never again

**Comment by mhintz** [comment]
Fair enough! Thanks for the suggestion of how to avoid the issue.
