### ISSUE TITLE
Ungroup? (merge transforms)

### ISSUE THREAD

**Issue by peteruithoven** [wout/svg.js#238]
I'm looking for a way to ungroup complete svg's, in such a way that the transforms of all parent groups get applied to the individual shapes. 
In inkscape for example when you group shapes and then move or scale it the group gets a transform. To properly turn imported svg's into a flat list of polygons I need to merge the transforms of the polygons with the transforms of their parents. 

The trickiest part seems to apply a transform on a existing transform. Is there anything built in for this in svg.js?

**Comment by Fuzzyma** [comment]
@peteruithoven still interested in implementing this?

**Comment by peteruithoven** [comment]
I'm afraid I can't find the time.

**Comment by Fuzzyma** [comment]
Finally after over a year this feature made it!!
