### ISSUE TITLE
Rotation transform in animation doesn't take rotation center into account

### ISSUE THREAD

**Issue by iravanchi** [wout/svg.js#258]
When rotation something in animation, the rotation center is ignored until the end of the animation. 
During the animation, the object rotates around its center, and when the animation finishes, the object location suddenly jumps to a place where it should have been at the end of the animation.

Psuedo-code:
<drawSomeLine>.animate(1000).rotate(45, 50, 50);

The same is true with transform() call when using rotation, which I think is what rotate() calls as a syntax sugar.

**Comment by Fuzzyma** [comment]
Quick fix:

    el.rotate(0, cx, cy).animate().rotate(deg, cx, cy)
