### ISSUE TITLE
Imported tspans all get an added top padding (dy)

### ISSUE THREAD

**Issue by jaapz** [wout/svg.js#259]
When I import a text with tspan like this:

    <text
     xml:space="preserve"
     style="font-size:16px;font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;text-align:start;line-height:125%;letter-spacing:0px;word-spacing:0px;writing-mode:lr-tb;text-anchor:start;fill:#000000;fill-opacity:1;stroke:none;font-family:Sans;-inkscape-font-specification:Sans"
     x="290.01382"
     y="382.73099"
     id="09.1-text"
     sodipodi:linespacing="125%"
     inkscape:label="#text3554">
    <tspan
       sodipodi:role="line"
       id="tspan3556-7-2-2-9-2-5"
       x="290.01382"
       y="382.73099">09.1</tspan></text>

The resulting object after import is this:

    <text id="09.1-text" font-family="Helvetica, Arial, sans-serif" inkscape:label="#text3554" sodipodi:linespacing="125%" y="382.73099" x="290.01382" xml:space="preserve" style="font-size: 16px; font-style: normal; font-variant: normal; font-weight: normal; text-align: start; line-height: 125%; letter-spacing: 0px; word-spacing: 0px; writing-mode: lr-tb; text-anchor: start; fill: rgb(0, 0, 0); fill-opacity: 1; stroke: none; font-family: Sans;">
    <tspan id="SvgjsTspan1621" 
                dy="20.8" 
                x="290.01382">09.1</tspan></text>

The y attribute for the tspan is removed and replaced by the dy attribute with the calculated content of 1.3 * 16 = 20.8.

This makes every text i have space 20.8 pixels down the place they actually should be.

I currently fix this by looping through all those elements in my own code and removing the dy, which fixes the problem, but of course that is not a situation i want to be in.

**Comment by Fuzzyma** [comment]
As much as I can follow your changes you basically add plain text when only one line is given but that doesn't fix this problem since the tspan is removed

**Comment by Fuzzyma** [comment]
This bug is fixed in svg.js v2
