### ISSUE TITLE
bbox() not returning proper data (Firefox only).

### ISSUE THREAD

**Issue by pawciow88** [wout/svg.js#261]
I'm trying to create a placeholder / free transform funcionality.
![ph](https://cloud.githubusercontent.com/assets/3949325/4354722/401f1694-4241-11e4-90e8-d81bebb9a66f.jpg)

I belive the only way to do that is to use clipping/masking (so images inside placeholders can be edited inside as well), right?
As you can see I'm almost there.

The problem is, when I get bounding box of element (needed to get dimensions of selected element's mask, to create Free transform points) I get wrong dimensions of mask on Firefox (no width and height, therefore x1,x2,y1,y2 are in same positions :/);
![ph_firefox](https://cloud.githubusercontent.com/assets/3949325/4354792/11c0eaf6-4242-11e4-9679-ba21ce5d0792.jpg)
So all the free transform editing points are in same place :/

Here is a structure of SVG:
![ph_structure](https://cloud.githubusercontent.com/assets/3949325/4354835/a40d0462-4242-11e4-843a-02aee5c6da87.jpg)

Does anyone know how to fix it? :(

**Comment by Fuzzyma** [comment]
I created a fiddle showing up this issue: http://jsfiddle.net/9jmvxgpt/3/
I think that is a bug in Firefox so we cant do anything here.

You can try to catch the x/y/width/height/transform-attributes by hand and calculate the stuff you need

```
var attr = clipRect.attr()
var rot= clipRect.transform('rotation')

var myRBox = {
    width: attr.width * Math.cos(rot) + attr.height * Math.sin(rot)
    height: attr.height * Math.cos(rot) + attr.width * Math.sin(rot)
    // and so on
}
```

**Comment by Fuzzyma** [comment]
long time ago but I finally found a workaround for this: http://stackoverflow.com/a/10433013/2129897
The thing is, that the clipper is in the defs and therefore not visible on the screen. Thats why the browser wont calculate a bbox. However you can use the trick from stackoverflow which should work

**Comment by Fuzzyma** [comment]
Just added some code which could fix your problem. Would be cool, if you could test this again :)
