### ISSUE TITLE
.data trailing zero trucated

### ISSUE THREAD

**Issue by pixelmagic66** [wout/svg.js#263]
Hi,

I insert a number of data fields to elements. With specific data inserted (in this case '018') the data is visible in the DOM with firebug ( data-wissel="018" ).

When requesting the specific data in JS (console.log(edit_element.data('wissel'));  ) then it returns 18 and not 018.

Is this as designed or could it be a bug ?

Thnx

**Comment by Fuzzyma** [comment]
That happens because svg.js tries to convert every strinng to the corresponding type (in this case number). If you want to access the string-value use `element.node.attributes['data-wissel']` instead
