### ISSUE TITLE
bower.json for plugins

### ISSUE THREAD

**Issue by mruoss** [wout/svg.js#266]
Hi

Could you please provide bower.json files for your plugins, too? I'd like to install using bower and I see no other way.

Thanks,
Michael

**Comment by bisubus** [comment]
+1 on that.
They can be installed via bower with "master" version restriction, but the packages miss valid bower.json, e.g. with `main` and `ignore` sections.

**Comment by wout** [comment]
Not all svg.js plugins are maintained by us so you'll have to ask the respective owners. At the moment we have other priorities but it is on the list. I'll close this issue for now.
