### ISSUE TITLE
Placing a plain text does not work in Opera

### ISSUE THREAD

**Issue by smsti** [wout/svg.js#267]
Hello,

http://jsfiddle.net/hyt4g20L/

A. The following code does not work in Opera
      var text1    = canvas.plain("");
      text1.move(20, 20);
      text1.plain("text1");

The text is nowhere to be found, since its y coordinate has some kind of nonsense value. If I call move() method twice or if I use setter attr() for x/y instead of move() in the above code, it does work. My Opera is version 12.16.

B. The following two codes provide different results. The first text is initialized to "", the second to "X". Then the coordinates and new text are set but their final coordinates are different. Do not know it is expected behaviour or not.

        var text1 = canvas.plain("");
        text1.move(20, 20);
        text1.plain("text1");

        var text2 = canvas.plain("X");
        text2.move(20, 20);
        text2.plain("text2");

C. Did you read the last message from https://github.com/wout/svg.js/issues/227? The bug has been closed so I do not know you have noticed any message afterwards. Unfortunately the method off() remains broken.

Regards

**Comment by Fuzzyma** [comment]
A and B works in Opera 20. I can't afford a patch for Opera 12 since I dont have it. Anyway I think its a bug of Opera because the methods are pretty straight forward without any magic which could explain that behaviour.

C was solved a few commits ago
