### ISSUE TITLE
how to center plain text around a given point?

### ISSUE THREAD

**Issue by YeoMagnus** [wout/svg.js#269]
Hi,

I have a coordinate x, y, and I want to center plain text around this coordinate.

Here is what I want as a result:

\<text x="10" y="10" style="text-anchor: middle; dominant-baseline: central; font-family: Roman; font-size: 10px;">Test\</text>

Here is what I tried with svg.js:

  var t = draw.plain ("Test").move (10,10);
  
  t.attr
  (
   {
    textAnchor:       "middle",
    dominantBaseline: "central",
    fontFamily:       "Roman",
    fontSize:         "10"
   }
  );

And here is the result:

\<text id="SvgjsText1077" font-family="Helvetica, Arial, sans-serif" x="75" y="-12" textAnchor="middle" dominantBaseline="central" fontFamily="Roman" fontSize="10">Test\</text>

The text is not centered around the coordinate. The coordinate is the bottom left corner of the text.

What can I do?

If this is not the right place to ask, please point me to the community of svg.js.

YeoMagnus

**Comment by Fuzzyma** [comment]
Maybe you should dig around a bit and google such problems.

    {
        not-valid: 'something',
        "valid-stuff": 'something'
    }

Just add `"` when using dashes in property-names!
