### ISSUE TITLE
Custom Distribution

### ISSUE THREAD

**Issue by thednp** [wout/svg.js#276]
Hi. I love light scripts and I want to know if it is possible to pack <code>svg.js</code> only for pie graphics and this kind of shapes http://tympanus.net/Tutorials/AnimatedSkillsDiagram/ ?

I don't need animation or draggable or any other :+1:

**Comment by Fuzzyma** [comment]
You can build your own version of svg.js. 
See the docu here:https://github.com/Fuzzyma/svg.js/tree/master#building

**Comment by fibo** [comment]
@Fuzzyma link is broken, https://github.com/Fuzzyma/svg.js/tree/master#building

you can use https://github.com/wout/svg.js#building instead
