### ISSUE TITLE
click events fire twice when there is also a dblclick event

### ISSUE THREAD

**Issue by GuidoFranz** [wout/svg.js#278]
Hello,

I want to use the click and dblclick events in parallel, but when double clicking the normal click events fire twice in addition to the dblclick event. Is this a (SVG) feature or is there a way to avoid this behaviour?

Thanks!

**Comment by Fuzzyma** [comment]
This is normal JS-Behaviour.
What you can do is the following:

- set a Timeout on the click-Handler
- wait for a doubleclick
- when it occurs, set a variable
- in the callback-function of the timeout check the variable and leave/execute code

    var dblclick_occured = false;

    element.dblClick(function(){
        dblclick_occured = true;
        // your dblClick-code here
    })

    element.click(function(){
        setTimeout(function(){
            if(dblclick_occured){
                dblclick_occured = false;
                return;
            }

            // Your click-code here
        }, 300) // time to doubleclick
    });
