### ISSUE TITLE
Request: Provide transform / move without scale consideration

### ISSUE THREAD

**Issue by ghost23** [wout/svg.js#281]
Hi,

currently, the move / transform and the other positioning methods incorporate the scale of the object for positioning an element. Like this:

    x.value /= this.trans.scaleX

If i don't want that, it seems I can only use the attr() method. But unfortunately, doing transforms via attr() prevents me from having these things animated, because

    animate(1000).attr("transform", "translate(400, 400)");

doesn't work, because animate attributes only works on simple numeric values, but not on complicated things like "translate(10, 20)".

Which leads me to my request: I would like to have an option to use transform(), move(), x(), etc. without that scale being applied, just the pure value.

**Comment by Fuzzyma** [comment]
In svg.js v2.0.1 the scale consideration was removed because it was not compatible to other move-functions e.g. of the PointArray which makes it almost impossibe to have a valid behavior when the element is zoomed
