### ISSUE TITLE
problem of importing large diagram

### ISSUE THREAD

**Issue by nahidshahin** [wout/svg.js#285]
Hi, I load a large SVG diagram using draw.svg method:

`$.get('a.svg', function(data) {`
`    var rawSvg = (new XMLSerializer()).serializeToString(data);`
`    var draw = SVG('drawing');`
`    var store = draw.svg(rawSvg);`
`});`

I try also inlined SVG XML but in both of the cases it generates following image (arrow and lables are missing):

![b](https://cloud.githubusercontent.com/assets/1224995/4939296/e8e926ee-65d1-11e4-8dfc-9d251e8e0d10.png)

But using JQuery load it works

`jQuery('#drawing').load('a.svg', null, function() {`
`    jQuery('#theElement').click( function() {`
`        alert('You clicked on the element!');`
`    });`
`});`

![a](https://cloud.githubusercontent.com/assets/1224995/4939302/effadd24-65d1-11e4-8dfd-1112611caf16.png)

Do you have any idea what could be the wrong?

**Comment by Fuzzyma** [comment]
Sorry for not answering that long.
I just had no idea what could be wrong.
You use XMLSerializer for the import. Did you check the outcom of this function? It is the same or changed? jQuery didnt alter the SVG. Maybe he Serializer did.
