### ISSUE TITLE
rotate() in Firefox has x,y values of 0 0 in transform

### ISSUE THREAD

**Issue by bluebrat** [wout/svg.js#288]
This has been driving me nuts and I'm finally starting to see what is happening between Chrome and Firefox (firefox seems to be the problem).

In chrome, rotate(15) results in transform="rotate(15 19.249500274658203 75.88949966430664)"
In Firefox, rotate(15) results in transform="rotate(15 0 0)"

This is of course throwing off the positioning in FF. I don't know where or how the rotate() function is getting the Y value of 75 but it's not from the height of the object, bounding box values. I'd calculate it myself but this number seems irrelevant to anything. :)

Any ideas?

**Comment by Fuzzyma** [comment]
So this can be closed?
