### ISSUE TITLE
follow bower naming guidelines.

### ISSUE THREAD

**Issue by blainekasten** [wout/svg.js#291]
Basically, I'm having an issue in Rails with Bower_Rails and sprockets. Because your bower naming scheme includes a period, I can't load it in sprockets. Bower specifies names should be seperated by a "-". 

So you should change the registry to something like "svgjs" or "svg-js"

**Comment by Fuzzyma** [comment]
From the bower docs:

```
    Must be unique.
    Should be slug style for simplicity, consistency and compatibility. Example: unicorn-cake
    Lowercase, a-z, can contain digits, 0-9, can contain dash or dot but not start/end with them.
    Consecutive dashes or dots not allowed.
    50 characters or less.
```

So nothing seems to be wrong with the name
