### ISSUE TITLE
Text on a hidden SVG

### ISSUE THREAD

**Issue by DetsCastelli** [wout/svg.js#295]
I figured out that drawing on a hidden SVG and after that calling show() is much faster then drawing on a visible SVG. 
However, text elements are not drawn the same way: calling text() on visible SVG adds the default text height to the Y-position, on an invisible SVG it doesn't. calling rotate() on a visible SVG rotates around the given text position, on an invisible SVG it rotates around 0,0.
What am I doing wrong?

**Comment by Fuzzyma** [comment]
The lib makes heavy use of bbox() which in some browsers return a zero-box when the element is not visible. Thus the positioning fails. So just dont do it
