### ISSUE TITLE
comic.js

### ISSUE THREAD

**Issue by balint42** [wout/svg.js#296]
Hey all,

just briefly wanted to drop a line: I made the humble [comic.js](https://github.com/balint42/comic.js) which you can see in action with SVG.js [here](http://www.morvai.de/comicjs/index3.html) perhaps you have suggestions how to improve performance (e.g. remove black shadows) or might be interested listing it as plugin / demo.

cheers!

**Comment by Fuzzyma** [comment]
You can add a PR including your plugin in the readme if you like

**Comment by balint42** [comment]
done

thx!
