### ISSUE TITLE
Some issues with exporting SVG from HTML due to various browser serialization bugs

### ISSUE THREAD

**Issue by bluebrat** [wout/svg.js#298]
First off, this is more of a browser based issue than it is an SVG.JS bug. It has to do with how a few of the various browsers deal with inserting or maiming of the namespace defined in the XML. It results in an SVG that can't be read by things such as illustrator, imagick or the same browser. I was exporting SVG's created by this library and sending to a PHP script to render them out using Image Magick, which is where I was discovering these stupid serialization issues. This problem has been reported to IE and Safari, but only Chrome so far has implemented the fix. Hopefully this information helps others in the future and saves some time.

By exporting, I am referring to the javascript methods such as *innerHTML* or jQuery's *.HTML(), as well as the Export plugin for SVG.JS.

*Internet Fucking Explorer* strips out the **:xlink** reference in the SVG header. Even though it displays properly in the inspector as:
```HTML
<svg id="SvgjsSvg1061" xmlns="http://www.w3.org/2000/svg" version="1.1" width="100%" height="100%" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 820 820">
```

But when exporting, it removes **:xlink**:
```HTML
<svg id="SvgjsSvg1061" xmlns="http://www.w3.org/2000/svg" version="1.1" width="100%" height="100%" xmlns="http://www.w3.org/1999/xlink" viewBox="0 0 820 820">
```

*Safari on OSX*, which **does not include Safari on iOS**, prefixes *HREF* tags with a namespace incrementer **NS1** when exporting. The exported SVG fails in Illustrator, Chrome & imagick. In Web Inspector, everything appears fine:
```HTML
<use id="SvgjsUse1128" href="#SvgjsG1063" transform="rotate(60 0 400) scale(-1 1)"></use>
```

After export, serialization steps in to ruin things:
```HTML
<use id="SvgjsUse1128" NS1:href="#SvgjsG1063" transform="rotate(60 0 400) scale(-1 1)"></use>
```

One final note relating specifically to ImageMagick, it won't recognize the SVG XML at all without the leading XML node. You'll need to add this yourself to the SVG string you give to PHP:
```XML
<?xml version="1.0" standalone="no"?>
```

Below is my craptastic solution for fixing all these issues with exporting serialization. I'm sure this could be done better but it works.

```PHP
		// $svgString is a string containing exported SVG XML
		$svgHeader = '<?xml version="1.0" standalone="no"?>'; // XML node needed by imagick
		$svgTag = 'svg'; // tag to search for
		preg_match_all("/\<svg(.*?)\>/", $svgString, $matches); // Get initial SVG node that may contain missing :xlink
		
		if ( !preg_match("/xmlns:xlink/", $matches[1][0]) )
			{
				$tempString = str_replace_nth( 'xmlns=', 'xmlns:xlink=', $matches[1][0], 1 ); // Replace second occurance of xmlns
				$svgString = str_replace($matches[1][0], $tempString, $svgString);
			}
			
		$svgString = preg_replace('/NS([1-9]|[1-9][0-9]):/', 'xlink:', $svgString); // Remove offending NS<number>: in front of href tags, will only remove NS0 - NS99
			
		$svgString = $svgHeader . $svgString; // Prefix SVG string with required XML node
```

**Comment by Fuzzyma** [comment]
Thanks for that solution.
So since everything is said I will close that :)

**Comment by oinp** [comment]
I just stumbled into this same issue. I somehow assumed that svg.js would help the devs overcome all SVG related browser quirks, so it was a surprise to find out that the export doesn't work in IE and in Safari (both supported browsers). When viewing an exported SVG in Safari, error "Namespace prefix NS1 for href on textPath is not defined" is displayed. IE however doesn't render the image at all. It just complains about duplicate xmlns-attribute in error console.

**Comment by dafen** [comment]
I know this is old but I still have this problem. I get tons of support tickets from users, that cant open their exported svg files in illustrator or even in the same browser. 

<img width="540" alt="screen shot 2018-05-08 at 13 51 01" src="https://user-images.githubusercontent.com/3841117/39755691-20a65dc8-52c7-11e8-886a-05f1d87a32b3.png">
<img width="680" alt="screen shot 2018-05-08 at 13 51 53" src="https://user-images.githubusercontent.com/3841117/39755693-20c13094-52c7-11e8-985a-5640f019a72d.png">
<img width="706" alt="screen shot 2018-05-08 at 13 52 38" src="https://user-images.githubusercontent.com/3841117/39755694-20d9f7a0-52c7-11e8-9686-09ba5e07f8ec.png">

Is there a way to fix tis apart from running it through some regex filters?

**Comment by Fuzzyma** [comment]
Which versions of svg.js are you using? Can you post one example file which is not working?

The top post of this issue explains where some of these errors come from. For example: When you want to save the svg as standalone file then you NEED to add the `<?xml` tag at start. This is nothing svg.js should take care of because the most usage is to import the exported svg at some point and browsers dont need the xml tag when you inline an svg into an html page.

The other errors appear to be browser issues. Maybe it is a solution to add polyfills for these browsers which monkeypatch the svg.js export method.
