### ISSUE TITLE
Is it possible to animate a pattern to its update state?

### ISSUE THREAD

**Issue by rubenmeines** [wout/svg.js#301]
Hey is it possible to animate the pattern state to the updated state e.g.:

```
var patroon = draw.pattern(40, 40, function(add) {
	add.rect(20,20).fill('#f06')
	 add.rect(10,10).move(10,10)
})
	
patroon.update(function(add) {
	add.rect(20,20).fill('#f06')
	add.rect(10,10).move(0,0)//animating .move()
})
```

**Comment by Fuzzyma** [comment]
Try the following 

    var myRect = draw.rect(10,10) 

    var patroon = draw.pattern(40, 40, function(add) {
        add.rect(20,20).fill('#f06')
        add.put(myRect).move(10,10)
    })

    myRect.animate().move(0,0)

Not tested but I feel like this could work
