### ISSUE TITLE
The use element can't point to an external file

### ISSUE THREAD

**Issue by GSchutz** [wout/svg.js#306]
The `href` attribute in the use element can point an external file using [IRI Reference](http://www.w3.org/TR/SVG/linking.html#IRIReference), like `href="img/tools.svg#hammer"`, but the library has no support for this.

**Comment by Fuzzyma** [comment]
Are you willing to make a PR for this?

(Please make sure to add a spec-example which fails without your patch and run all other specs afterwards to make sure that nothing is broken)
Thanks!
