### ISSUE TITLE
Performance of circle

### ISSUE THREAD

**Issue by smsti** [wout/svg.js#308]
"Note that this generates an ellipse element instead of a circle. This choice has been made to keep the size of the library down."

I implemented circle into svg.js and my code runs now two seconds instead of three seconds (before). Note that generating solid circles is only a small portion from what is being drawn and processed in my code.

Please implement circle as circle, not as an ellipse. It is a huge performance drawback. There will be some consequences for users of the library then, like "ellipse" becomes "circle", "SVGEllipseElement" becomes "SVGCircleElement", but it is definitely worth the significant performance gains.

**Comment by okonet** [comment]
This also has other implication such as `stroke-dashoffset` not working etc.

**Comment by Fuzzyma** [comment]
Implemented in svg.js v2
