### ISSUE TITLE
IE10 and IE11 animate clip image and mouseEnter + mouseLeave interaction

### ISSUE THREAD

**Issue by Nephelococcygia** [wout/svg.js#314]
- i have an image clip with a polygon;
- on mouseEnter of the image, i change the plot of the polygon with an animate method;
- on mouseLeave of the image, i set the original plot back with an animate method.

The bug is only on IE10 and IE11, when then animation start, a mouseLeave is triggered directly.
If i don't use animate it's working "fine", but there's no animation.
If i don't clip an image, it's also working fine.

It's working fine on IE9, lastest Safari, Firefox and Chrome.

**Comment by Fuzzyma** [comment]
As far as I know mouseenter and mouseleave is commented out in the source duo to bugs in IE.
You should use `mouseOver` instead
