### ISSUE TITLE
Animationframe leak

### ISSUE THREAD

**Issue by zachrbrown** [wout/svg.js#316]
A little background: I'm currently working on a project that contains about 20-30 items with linear gradients which animate their stops continuously throughout the entire run time of the experience. 

[gradient docs](http://documentup.com/wout/svg.js#gradient)
[animate docs](http://documentup.com/wout/svg.js#animating-elements)

As the site runs, the framerate drops continuously over time. Running the chrome dev tools timeline shows an insane amount of `requestAnimationFrame` calls from this library; more and more over time, thus the consistent drop in framerate. So much so that the chrome dev tools buffer fills up in a **few seconds**.

![screen shot 2015-01-29 at 12 49 40 am](https://cloud.githubusercontent.com/assets/845717/5954766/c13b74c4-a750-11e4-91ce-2694decf7baf.png)

[Video](http://cl.ly/282q2d1X1O3p)

Here is my code:
```javascript
var colors;
var fnAnimate;
var gradient;
var s1;
var s2;
var s3;
var stops;

colors = ['#EFFF22', '#D1FBFF', '#2759FF'];

gradient = draw.gradient('linear', function(stop) {
    s1 = stop.at(0, colors[0]);
    s2 = stop.at(0.4, colors[1]);
    s3 = stop.at(1, colors[2]);
    stops = [s1, s2, s3];
});

fnAnimate = function() {
    var color;
    var stop;

    color = _.sample(colors);
    stop = _.sample(stops);
    stop.animate().update({
        color: color
    });
};

setInterval(function() {
    fnAnimate();
}, 1000);
```

From my understanding of the documentation, each invocation of animate on an object should stop any preexisting animation on said object. [Checking here in the source](https://github.com/wout/svg.js/blob/master/src/fx.js#L434), that does seem to be the case. If you look closer at the [`stop` method](https://github.com/wout/svg.js/blob/master/src/fx.js#L368), it looks to clear an animation timeout and delete/reset some properties. It is **not** doing, however, one vital thing.

Looking through the [`fx.render` method](https://github.com/wout/svg.js/blob/master/src/fx.js#L165), on lines 189 and 192, we enter a `requestAnimationFrame` loop. This is good. **BUT** after looking around this entire library, [cancelAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window.cancelAnimationFrame) is nowhere to be found. There's also an absence of a shim for it in the [`helpers.js` next to the `requestAnimationFrame` shim](https://github.com/wout/svg.js/blob/master/src/helpers.js#L125).

Essentially what is happening is that every time `animate` is called, a `requestAnimationFrame` loop is created, but never killed, nor a reference to it stored; thus creating zombie animation loops. This would explain the extreme amount of `requestAnimationFrame` calls I'm seeing in my dev tools timeline.

**Comment by MathieuLoutre** [comment]
Oh! You may have found the root of a problem I've been struggling with for a while now... Have you worked out a patch yet? If not, I could look into it this weekend maybe.

**Comment by zachrbrown** [comment]
@MathieuLoutre Have not implemented/tested one yet. Hopefully tonight I can get around to it

**Comment by zachrbrown** [comment]
This PR fixes it. https://github.com/wout/svg.js/pull/318

**Comment by Fuzzyma** [comment]
Please add spec-examples to the commit so I can accept it

**Comment by Fuzzyma** [comment]
@zachrbrown - I think the problem of that zombie-calls is not about `cancelAnimationFrame`. `requestAnimationFrame` works like `setTimeout`. If you stop calling it, the loop will break.
However - this is not the case in the code because `fx.situation.play` is always true (one time set, never changed).
Imo the only thing to do is setting `fx.situation.play` to `false` when calling stop.

I have no test-scenario here. Would you mind to test that fix for me?

**Comment by Fuzzyma** [comment]
Not sure what you just did...

**Comment by Fuzzyma** [comment]
Doublechecked this. You are right. I will implement this. Thanks!

**Comment by zachrbrown** [comment]
@Fuzzyma Even if `fx.situation.play` is set to `false`, the loop is maintained. https://github.com/wout/svg.js/blob/master/src/fx.js#L192. I'm not sure why it's like this.

Hah, yea, sorry. I rebased my fork off of `wout/svg.js` `master` and in the process screwed up my history, and had to remerge the commit into my `master`. That closed the PR here too.

**Comment by Fuzzyma** [comment]
Ah okay. Meanwhile in figured out why the play = false didn't work. When you call the new animation Oi overwrite play again with the initial value which is true and the loop remains.

I will mention you in the changelog and commit this myself if this is OK for you (!?)

**Comment by zachrbrown** [comment]
Sure!

**Comment by Fuzzyma** [comment]
Testing that polyfill and this issue is pretty hard without old Browsers (and frame-view like chrome...)
Any Idea on how to test that in a proper way?

**Comment by MathieuLoutre** [comment]
If it's the one coming from either https://gist.github.com/paulirish/1579671 or http://www.paulirish.com/2011/requestanimationframe-for-smart-animating/ I'd assume they're already tested. If you'd want to manually give it a go, you can try browserstack, but the rendering speed won't be faithful.

**Comment by Fuzzyma** [comment]
I have taken the one from paulirish.com but modofied it slightly. Thats the result:

```
// requestAnimationFrame / cancelAnimationFrame Polyfill with fallback based on Paul Irish
(function(w) {
  var lastTime = 0
  var vendors = ['moz', 'webkit']
  
  for(var x = 0; x < vendors.length && !window.requestAnimationFrame; ++x) {
    w.requestAnimationFrame = w[vendors[x] + 'RequestAnimationFrame']
    w.cancelAnimationFrame  = w[vendors[x] + 'CancelAnimationFrame'] ||
                              w[vendors[x] + 'CancelRequestAnimationFrame']
  }
 
  w.requestAnimationFrame = w.requestAnimationFrame || 
    function(callback) {
      var currTime = new Date().getTime()
      var timeToCall = Math.max(0, 16 - (currTime - lastTime))
      
      var id = w.setTimeout(function() {
        callback(currTime + timeToCall)
      }, timeToCall)
      
      lastTime = currTime + timeToCall
      return id
    }
 
  w.cancelAnimationFrame = w.cancelAnimationFrame || w.clearTimeout;

}(window))
```
Should work imo :)

**Comment by MathieuLoutre** [comment]
Yeah, if it's based on what's on the website, I wouldn't worry too much about extra testing of the polyfill :)
