### ISSUE TITLE
How would I go about creating a circle path with text on it but with the text "reversed"

### ISSUE THREAD

**Issue by 01AutoMonkey** [wout/svg.js#320]
Example:
![](http://i.imgur.com/5z3eaMf.png)

As you can see I've got one text on a regular circular path (1 Kether) but the text "The Crown", if it were on this same regular circluar path it would be upside down, but it's not, and I managed to do that in Snap.svg by doing:

```
if (style.reversed == true) m.scale(-1, 1, p.x, p.y);
circlePath.transform(m);
text.attr({ 'textpath': circlePath})
```

Essentially I just "mirror" the circle path by scaling it with a -1.

How would I go about doing this in svg.js? (as far as I've gotten so far: http://jsfiddle.net/mhgtjgft/)

**Comment by Fuzzyma** [comment]
Actually there is only a hidden way to transform the text-path but it is possible.
First of all: only scaling without translating scales the circle out of the view. You have to keep that in mind!

When you know where the ref-path for the textPath is hidden its pretty straigth-forward:
    var draw = SVG('drawing')

    var circle = draw.circle(300);
    circle.move(100, 100)
    circle.fill('#000000')
    circle.stroke('#000000')
    circle.opacity(0.2)

    var text = draw.text("The Ciiircclee of Liiiife")
    text.attr("letter-spacing", 2);

    // circle to Path, remove Path from view, take path-attr
    // if you dont need your circle anymore use circle.toPath(true) instead which replaces the circle with the path
    text.path(circle.toPath().remove().attr('d'));

    // this.track holds a reference to the ref-path which you can transform
    text.track.translate(500,0).scale(-1,1);

Here is a working example: http://jsfiddle.net/mhgtjgft/4/
Next step (rotating, moving) are up to you.
