### ISSUE TITLE
How to fetch the x value of an element? What is attribute 'x' ?

### ISSUE THREAD

**Issue by szabgab** [wout/svg.js#322]
I wanted to retrieve the x,y coordinates of an object. 
The documentation shows how to fetch ```rect.attr('x')``` but that does not seem to be connected to the 'dx' value.  Is that 'x' only a placeholder in the example or is that a real attribute?
```rect.attr('dx')``` returns ```undefined``` and ```rect.dx()``` just sets the dx value to 0.

Most importantly, is there a way to fetch the dx/dy values of an element?

**Comment by szabgab** [comment]
Later in the documentation I found ```rect.x()``` returning the absolute coordinates.

**Comment by Fuzzyma** [comment]
So this is solved and can be closed?

**Comment by szabgab** [comment]
I left it open as this might need some clarification in the documentation. But it is your call after all.

**Comment by Fuzzyma** [comment]
There is nothing like a dx value on a rect element. A short look in the dom inspector would show you that. The function dx is for moving an element relative to its position but the resulting coordinates are still absolute. You can use rect.attr('x') or rect.x() as you like to retrieve the coordinates. That is all documented and works as it should.
