### ISSUE TITLE
Event detaching / off doesn't seem to work properly when called on multiple SVG elements

### ISSUE THREAD

**Issue by pjfsilva** [wout/svg.js#323]
**Steps to reproduce:**
1) Go to  http://jsfiddle.net/y5ufe7qn/
2) Turn on developer tools / javascript console
3) click on EVENTS ON button
4) click on a black circle on the map -> mousedown is caught OK (check console log)
5) click on EVENTS OFF button
6) click on a black circle on the map -> mousedown is still being activated when it shouldn't (check console log) --> Event off didn't work 

**Description**
From my understanding the problem is the usage of the "SVG.listeners" object. To understand this, go again to my example and press EVENTS ON and then "print svg listener" button. You can see that object is populated with only 1 SVGElement but I added the mousedown event to 2 SVGElements. 

This is because of the usage of "SVG.listeners[node]". As "node" object is not unique as a key for that object. When we call SVG.off the events aren't properly detached because of the wrong usage of this data structure.

I noticed this issue while debugging a related issue on svg.draggable: https://github.com/wout/svg.draggable.js/issues/30

On that plugin the element.on / off is very much used so this bug causes a lot of troubles.

**Possible fix**
To fix this I would change event.js to use node.id instead of the node object directly as such:
```
// Add event binder in the SVG namespace
SVG.on = function(node, event, listener) {
  // create listener
  var l = listener.bind(node.instance || node)

  // ensure reference objects
  SVG.listeners[node.id]        = SVG.listeners[node.id]        || {}
  SVG.listeners[node.id][event] = SVG.listeners[node.id][event] || {}

  // reference listener
  SVG.listeners[node.id][event][listener] = l

  // add listener
  node.addEventListener(event, l, false)
}

// Add event unbinder in the SVG namespace
SVG.off = function(node, event, listener) {
  if (listener) {
    // remove listener reference
    if (SVG.listeners[node.id] && SVG.listeners[node.id][event]) {
      // remove listener
      node.removeEventListener(event, SVG.listeners[node.id][event][listener], false)

      delete SVG.listeners[node.id][event][listener]
    }

  } else if (event) {
    // remove all listeners for the event
    if (SVG.listeners[node.id][event]) {
      for (listener in SVG.listeners[node.id][event])
        SVG.off(node, event, listener)

      delete SVG.listeners[node.id][event]
    }

  } else {
    // remove all listeners on a given node
    if (SVG.listeners[node.id]) {
      for (event in SVG.listeners[node.id])
        SVG.off(node, event)

      delete SVG.listeners[node.id]
    }
  }
}
```

If anyone confirms this is the real problem and this is a good solution I'll post a PR. 
This also seems to be the cause for this: https://github.com/wout/svg.js/issues/227 (that seems to be wrongly closed)

**Comment by Fuzzyma** [comment]
I tested a bit around this issue and found that you are right.
This was my test-example:

    var obj = {};
    var a = document.createElement('p');
    var b = document.createElement('p');
    obj[a] = 'tost';
    obj[b] = 'butter';
    console.log(obj);

Which outputs only `butter` because the p-html-obj is converted to the string representation which is `[object HTMLParagraphElement]` and therefore overides the key.

About the PR (in case you dont know):  
Add a failing `spec`-Test which you wanna fix and apply your patch to the code.
Run the tests again to see if something broke. If not -> PR

Thanks for spending time into that lib!
