### ISSUE TITLE
cannot remove() root or nested svg

### ISSUE THREAD

**Issue by loredanacirstea** [wout/svg.js#326]
http://jsfiddle.net/loredana_cirstea/aL1mfk37/1/

When trying to remove a root or nested svg:

    var draw = SVG('drawing').size(300, 300)
    var rect = draw.rect(100, 100).attr({ fill: '#f06' })
    draw.remove();

the svg is not removed and the browser console outputs: "undefined is not a function", with error pointing to `this.parent.removeElement(this)` from the remove() function.

I also tried clearing the svg before.

**Comment by Fuzzyma** [comment]
Thanks for notifying. I will look into it

**Comment by Fuzzyma** [comment]
Wops didn't mean to close this

**Comment by Fuzzyma** [comment]
Wops - didn't mean to close this

**Comment by loredanacirstea** [comment]
Thank you! This solved the issue.
