### ISSUE TITLE
Event click on multiple elements

### ISSUE THREAD

**Issue by maximhoffman** [wout/svg.js#328]
Hi, I'm creating my svg ellipses by loop, and fire click event on each of them. How I can change fill on the clicked element? I think I can push all SVG.js objects to array in loop, and then find in array necessary object and change his fill. Maybe there is another way to find the item I want?

**Comment by Fuzzyma** [comment]
What about just trying what you explained?
```
var drawing = SVG('drawing')

for(var i = 0; i < 5; ++i){
    var c = drawing.circle(50)
    c.on('click', function(){
        c.fill('#abc')
    })
}
```
