### ISSUE TITLE
svg.js morph fiddle

### ISSUE THREAD

**Issue by ctzurcanu** [wout/svg.js#329]
Hi Wout,

Your old email does not work anymore..
At some point you had a very interesting demo of morph() (for PointArray) on fiddle. I don't seem to be able to locate it. I am implementing the same for PathArray. Would you send me the pointer?

**Comment by ctzurcanu** [comment]
found it: http://jsfiddle.net/wout/4MJcU/

**Comment by IonicaBizau** [comment]
@ctzurcanu That's looks like my MS Paint drawings. :smile: Nice!
