### ISSUE TITLE
Linear gradient doesn't work in Safari 5.1

### ISSUE THREAD

**Issue by rajkaran** [wout/svg.js#330]
Hi There,

I am having trouble in getting linear gradient work with circle (/eclipse). I've only tested it on safari 5.1 and on my ipad safari browser. On my ipad it works I can see gradients but on desktop browser it doesn't.

After some googling I have find out that it's a bug in Safari. I am not sure is it actually happening because of bug or I am making some mistake.

Below is the code:

	var allElements = draw.group();
	var circleArray = new Array();

	PROJECTS //an object contains position of all circles

	COLOUR_COMBOS //a 2D array contains color combinations
	SELF.getRandomInt //returns random array from COLOUR_COMBOS

	DIAMETER = 80

	Object.keys(PROJECTS).forEach(function (key) {				
					
		var colorCombo = COLOUR_COMBOS[ SELF.getRandomInt(0, COLOUR_COMBOS.length-1) ];
		
		var gradient = draw.gradient('linear', function(stop) {
			s1 = stop.at(0, "#"+colorCombo[0])
			s2 = stop.at(.7, "#"+colorCombo[1])
		})
		
		gradient.from(0, 0).to(0, 1)
		
		circleArray[key] =  draw.circle( DIAMETER, DIAMETER ).center(PROJECTS[key]['position_on_x-axis'], PROJECTS[key]['position_on_y-axis']).fill(gradient).style({ cursor: 'pointer' });
		
		circleArray[key].attr('id', key);
		circleArray[key].data('dropColorFrom', colorCombo[1]);
		
		
		allElements.add(circleArray[key]);
		
	});

Note:- When I copy paste value of fill attribute in element inspector, it shows the gradient...  So I can assume that gradient is supported but I am missing something or doing it wrong...

Any help......

Raj

**Comment by Fuzzyma** [comment]
Next time you come for help please make sure you have created a fiddle.
I installed Safari 5.1.7 for you and created this fiddle: http://jsfiddle.net/mbng72q1/
Works as expected

**Comment by rajkaran** [comment]
Hi Fuzzyma,

Thank you for your prompt reply...  Your example only works for a single circle, when i puts gradient on more than one circle it doesn't work as expected...  Here is the updated fiddle http://jsfiddle.net/rajkaran07/mbng72q1/1/

Please bear with me I am new to SVG

Thanks

**Comment by Fuzzyma** [comment]
When I open this fiddle in my safari something awkward happens:
2 Circles have a linear Gradient shown but all have the correct gradient ID.
When I switched the tab to look for developer-tools for safari and came back to the fiddle, all 5 circles had a gradient now. 
So I think that is a Browserbug and not a Bug of svgjs. You should report it to the vendor

**Comment by rajkaran** [comment]
Fuzzyma, 

Closing this issue is fine, but I will investigate this issue in more detail by using some other libraries and will update you...

Raj

**Comment by Fuzzyma** [comment]
Thank you!
