### ISSUE TITLE
Documentation: why the direction of '<' in inheritance?

### ISSUE THREAD

**Issue by akauppi** [wout/svg.js#332]
I'm new to svg.js, and I do appreciate good documentation. Is there a reason why the '<' in class inheritance seems to point towards the subclass, not the superclass. This feels wrong for me, and I'd like to hear which convention this is based on.

> Javascript inheritance stack: SVG.G < SVG.Container < SVG.Parent

I bet there are many schools on this. I looked at [SO 247519](http://stackoverflow.com/questions/2471519/why-does-the-arrow-go-up-in-inheritance) and would generally feel like the one writing "B having more stuff in it then A", i.e. that the arrow should point to the superclass.

Furthermore, also [UML](http://www.ibm.com/developerworks/rational/library/content/RationalEdge/sep04/bell/) seems to have the arrowheads pointing towards the common superclass.

I understand that these conventions, and terms themselves are bizarre. "subclass" has "more stuff" than superclass, but its name really implies otherwise. Oh, well...

If it's just by chance, currently, I would suggest turning the arrows around. Thanks.

**Comment by wout** [comment]
Thanks for your suggestion.
You are more than welcome to update the docs and create a pull request :)
