### ISSUE TITLE
Discuss svg.js?

### ISSUE THREAD

**Issue by roblevintennis** [wout/svg.js#333]
@wout any chance you'd want to come on SVG Immersion podcast? Sorry, didn't know how else to contact you :yum:

**Comment by Fuzzyma** [comment]
He wont answer here since hes busy atm.
You can write him a mail (note that his mail from github is outdated. I dont want to publish it hear. I am sure you find a way to get the mail ;)  )

**Comment by roblevintennis** [comment]
Ah ok, tried, I'll have to try harder lol...closing thanks @Fuzzyma
