### ISSUE TITLE
Compilation with Closure Compiler using ES5 strict mode fails

### ISSUE THREAD

**Issue by bcbweb** [wout/svg.js#336]
polyfill.js contains a function declared inside an if block, which is not allowed in ES5 strict mode. We're using Closure Compiler in strict mode, so this causes compilation to fail. Is there a reason for it being declared like this?

**Comment by bcbweb** [comment]
```
// Add CustomEvent to IE9 and IE10 
if (typeof CustomEvent !== 'function') {
  // Code from: https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent
  function CustomEvent (event, options) {
    options = options || { bubbles: false, cancelable: false, detail: undefined }
    var e = document.createEvent('CustomEvent')
    e.initCustomEvent(event, options.bubbles, options.cancelable, options.detail)
    return e
  }

  CustomEvent.prototype = window.Event.prototype

  window.CustomEvent = CustomEvent
}
```

**Comment by Fuzzyma** [comment]
The reason actually is in the comments. This is a polyfill from mozilla which just wasn't changed. Feel free to setup a RR to change it to `CustomEvent = function(){...}` which should fix that warning

**Comment by Fuzzyma** [comment]
Closed with https://github.com/wout/svg.js/commit/08e67dfb31cb21405407d8e964290fae61dc527f
