### ISSUE TITLE
Question: draw.viewBox() is not a function

### ISSUE THREAD

**Issue by qfz** [wout/svg.js#340]
I tried to set the view box by calling draw.viewBox(), but got error that it's not a function. Can anyone please explain in a bit more detail how to use the viewBox() function, or point me to a fuller example than the documentation? Do I call viewBox() on the object returned by SVG('drawing')?

**Comment by twooclock** [comment]
For me following is working:
var box = draw.viewbox();
draw.viewbox(box.x, box.y, box.width - 100, box.height - 100);
Beware of character case (viewBox != viewbox)...
