### ISSUE TITLE
custom svg element

### ISSUE THREAD

**Issue by twooclock** [wout/svg.js#341]
Hi，
I am new to SVG. I want to draw a system made of blocks (rectangulars) and L-joins. Elements stack one after another left to right/up down. I want the blocks to raise events (to be able to modify their properties). I plan to get a model from the server and use svg.js to draw my view. I was studying svg.js and I'm pretty sure it's doable.

I'm having trouble starting:
1.How to organize elements? in groups, sets,...? 
2.I'd like to have composite elements - should I group basic svg elements, use images or is there any other way? 
3.Is it possible to define your own custom element (for example a rect with two diagonal lines in it)?

Hope someone understands and pont me to the right direction...

**Comment by Fuzzyma** [comment]
1. When you use groups you can move all elements in a group at all when moving the group. Also nested SVG will work. The elements are physically grouped as childs from the group. When you just want an array-like container to hold your elements use `set` instead which gives you some other functions to work on that *array*

2. You can ofc use single elements to draw your image again and again. But the clever option is to use a `symbol` or `use` to reference one composite element you defined once.

3. See point 2 here. You can define your rect with 2 lines once and reuse it. But you can also take a look at the `invent`-function which does exactly that. See the doc here

**Comment by GSchutz** [comment]
Maybe is better if you try some SVG tutorial , [like this](http://tutorials.jenkov.com/svg/index.html) and [in MDN](https://developer.mozilla.org/pt-BR/docs/Web/SVG/Tutorial).

**Comment by twooclock** [comment]
Thank you both. Right now I'm struggeling with another challenge: when rotating an element for 90 degrees (group) coordination system axis switch (x becomes y and vice versa). How do you usually deal with this? Any tips...?

**Comment by Fuzzyma** [comment]
How do you deal with it, when its upside down? What do you do when its rotatet 45deg?
This is a forum to report bugs and not to ask one question after another.
You can't "handle" that in a simple way. There are enough guides on the internet that shows how to deal with transformations

**Comment by twooclock** [comment]
ok, I'm sorry! Is there any user group to ask questions like that? I'll try to use stakoverflow in the future... Thanks for everything...#close

**Comment by Fuzzyma** [comment]
Stackoverflow is the way to go imo :)

**Comment by Fuzzyma** [comment]
@twooclock just found this again (#209)
Maybe it helps
