### ISSUE TITLE
Initializing SVG element doesn't always work

### ISSUE THREAD

**Issue by MyrionPhoenixmoon** [wout/svg.js#342]
My code looks like this:
var drawingPad = SVG('drawingPad').size('100%', '100%');

Usually, when I get to the page where I use this, the svg element just remains empty and uninitialized. Once I reload it always works. 

Can anyone help me figure out what is going on?

**Comment by akauppi** [comment]
Are you calling that within a `window.onload`block or similar (jQuery `$( function() { ... } )`) that makes sure the DOM has finished loading?

Not sure if that's the problem here - just asking what's the context where your line gets called.

**Comment by MyrionPhoenixmoon** [comment]
yes, I'm calling it from within $document.ready.

**Comment by MyrionPhoenixmoon** [comment]
```  
var drawingPad = $document[0].getElementById('drawingPad');
var temp = drawingPad;

$document.ready(function () {
    drawingPad = SVG('drawingPad').size('100%', '100%');
    console.log(temp);
    console.log(drawingPad.parent);
    console.log(angular.equals(drawingPad.parent, temp));
    if ($routeParams.screenshotURL) {
      drawingPad.image(decodeURIComponent($routeParams.screenshotURL)).loaded(function (loader) {
        drawingPad.attr({
          width: loader.width
        });
        drawingPad.attr({
          height: loader.height
        });
      });
    }
  });
```

So, when it works, the comparison returns true, but when it fails I have this situation:
temp gets logged as ```<svg id="drawingPad"></svg>``` while drawingPad is this:
```<svg id="drawingPad" xmlns="http://www.w3.org/2000/svg" version="1.1" width="960" height="946" xmlns:xlink="http://www.w3.org/1999/xlink">[...]</svg>```

Then, a reload fixes it. 
It seems like a weird cross between a loading issue and the DOM not getting updated...

**Comment by MyrionPhoenixmoon** [comment]
I have added more debug output, which just shows me that I fundamentally don't understand something involved here:
```
  var drawingPad;
  var temp = drawingPad;
  console.log('temp');
  console.log(temp);
  $document.ready(function () {
    console.log('before initialization, in .ready');
    console.log($document[0].getElementById('drawingPad'));
    drawingPad = SVG('drawingPad').size('100%', '100%');
    console.log('drawingPad after .get');
    console.log(drawingPad.parent);
    console.log('document element');
    console.log($document[0].getElementById('drawingPad'));
    if ($routeParams.screenshotURL) {
      drawingPad.image(decodeURIComponent($routeParams.screenshotURL)).loaded(function (loader) {
        drawingPad.attr({
          width: loader.width
        });
        drawingPad.attr({
          height: loader.height
        });
      });
    }
  });
```

In the failed case, the log looks like so:
temp: undefined
before initialization and document element after init: simple svg as in .html file
drawingPad: svg element with image child

Seems like $document doesn't get updated...

In the working case, **all** the output except for temp (which is still undefined) is the SVG element that SVG('drawingPad') should generate!
**Including the log from before actually constructing the SVG.js element!**

Sorry for the multiple posts, but I hope this gives you enough info to figure it out.

**Comment by akauppi** [comment]
I shouldn't have asked for more details, without suggesting to take this to StackOverflow. 

It looks like belonging there - for generous helpful answers. Now it's in the projects GitHub Issues, which is where one would normally take reproducible bugs. So something discussed in SO that turns out really to be a bug should end up here.

I'm not one of svg.js authors, just tracking the project. So what I write here is just my own suggestion, not a project guideline.

If you copy-paste the above to StackOverflow, add the `svg.js` tag to it. There are currently [52](http://stackoverflow.com/questions/tagged/svg.js) questions with such tag.

**Comment by MyrionPhoenixmoon** [comment]
That is a good idea and I will do so.

However, I would like to ask you to try and reproduce it. To me, it does look like a bug where svg.js fails to properly initialize its doc element and I'm not sure what I could even be doing wrong to produce such inconsistent behavior.

**Comment by MyrionPhoenixmoon** [comment]
Since adding a timeout in AngularJS fixed the issue, I apologize for opening this here.
It seems it was some really weird behavior in AngularJS.

**Comment by DanLeininger** [comment]
Adding a timeout also solves issues around initializing existing svg elements, and getting them by id in Ember.js
