### ISSUE TITLE
Text is moved in relation to the rest of elements after drawing been hidden

### ISSUE THREAD

**Issue by marekjedrzejewski** [wout/svg.js#343]
I experienced a bug with SVG Text in project I'm wrining using svgjs and angular. Here's how it look:
https://rawgit.com/marekjedrzejewski/darts/svgtextbug/src/darts.html
After clicking start ng-show for the drawing evaluates to true and board shows up. Unfortunately text is moved out of its place.
How it works if it's not hidden in the beginning: 
https://rawgit.com/marekjedrzejewski/darts/master/src/darts.html

Tried it on FF, Chrome and on mobile, everywhere it behaves the same way, so I suspect it must be a bug in svg.js OR svg in general. Probably you would know better, because you're working on the library and I am just doing my first project using it :)

Code here:
https://github.com/marekjedrzejewski/darts/tree/svgtextbug

**Comment by Fuzzyma** [comment]
So if you could break down your code to the part which is important for the "bug" that would be great.

**Comment by marekjedrzejewski** [comment]
Html line 20. Here's div where SVG is generated.

    <div id="board" ng-show="show_board()"></div>

16-23 in board.js:

    var points_text = [];
    // numbers are generated before everything else to cover them
    // from being selected with transparent mask
    for (var i = 0; i < n.segments; i++) {
        points_text[i] = draw.text(n.values[i].toString());
        set_attr.points(points_text[i],i);
    }

276-289:

    set_attr.points = function (text, i) {
    	text.fill(c.points);
    	text.font({
       		family: "Ubuntu Condensed, Segoe UI Semilight," +
    						"HelveticaNeueCondensed, sans-serif",
    		size:     n.points_fontsize
    	});
    	text.center(point_calc.x(n.points_r, i*n.segment_rotation),
    							point_calc.y(n.points_r, i*n.segment_rotation) );
    };

103-117:

    // functions returning x and y based on angle and distance
    // from center. Angle 0 is understood as straight up.
    var point_calc = {};
    point_calc.x = function(dist, ang) {
    	return (
    		n.center + dist *
    		Math.cos(Math.radians(270+ang))
    	);
    };
    point_calc.y = function(dist, ang) {
    	return (
    		n.center + dist *
    		Math.sin(Math.radians(270+ang))
    	);
    };


That's how I generate it. The same way as I generate rest of the elements.

**Comment by Fuzzyma** [comment]
Thats basically what I got when I read through your code.
"break down your code" means that you create a testcase as simple as possible where the problem still exists (jsfiddle). Such a bunch of code is not useful for debugging

**Comment by marekjedrzejewski** [comment]
Sorry, here it is:
https://jsfiddle.net/Vac2Q/5592/

**Comment by Fuzzyma** [comment]
Thank you. I will take a look at it

**Comment by Fuzzyma** [comment]
So the problem is: 
Whenevery a y-value for a text-element is calculated it takes the bbox into account. This is especially needed when you move the text-alement by its center.
The Browser calculates the bbox on its own which is no problem at all but when the element is not visible the browser fails.
So we have no bbox, 0 is used => text jumps around.

Any idea is very appreciated because that is a big problem.
`text` has no height like `rect`. It "inherits" is height from its content (text, tspan...). I thought about calculating the height using the font-size and line-height (leading in svg.js) which would give me a fair chance to calculate a height. The problem is that you are free to place your tspans everywhere in your textelement so this calulation breaks when the build-mode for text is not used.

**Comment by marekjedrzejewski** [comment]
This is also a partial solution, and I don't know if not ridiculous:

If there's no problem with paths, converting text to paths may be a solution. But it won't be selectable then so if one wants the text to be selectable it is another problem.

**Comment by Fuzzyma** [comment]
When you think about it: Drawing an SVG when its hidden sounds kinda stupid. You dont do that with html and jquery either. Not even jquery can give you e.g. the offset of an element when its hidden with display:none. That brings me to the idea that `visibility:hidden` could work. Maybe thats something you can try.
