### ISSUE TITLE
Is it possible to pause ALL running animations?

### ISSUE THREAD

**Issue by brandondurham** [wout/svg.js#344]
So I'm working on a project that includes a piece that essentially amounts to a one-minute movie made with SVG. It's been a blast to work on so far using your library. I do wonder, though:

Is there a way to pause ALL running animations with the option to continue where you left off, like a video?

There are moments where there are 3–4 elements animating at a time, and it's going to be a nightmare to keep a running record of what is currently animating so I can manually cycle through and pause each individual item.

Suggestions?

**Comment by Fuzzyma** [comment]
svg.js doesnt keep record of every animation which is running. So it cant pause it all at once. However there **is** a pause-function you can use.

You can try to add all elements which are animated to a set. SVG.Set has an `each`-function which you coould use to apply `pause` to every element. To make sure that the set is always clean you can use the `after`-method which adds a callback to the end of the animation. In this callback you can remove the element from the set.

**Comment by brandondurham** [comment]
Great ideas for a workaround. If it works well I'll post my solution here for reference.

**Comment by Fuzzyma** [comment]
any solution till now? :D

**Comment by brandondurham** [comment]
Nope. :/ Fortunately didn't have to for this job.
