### ISSUE TITLE
Can you set animation delay for individual properties?

### ISSUE THREAD

**Issue by brandondurham** [wout/svg.js#345]
I have the following animation:

```javascript
line.animate(400, SVG.easing.expoOut, 300).attr({
	x1: startX,
	y1: startY,
	x2: startX,
	y2: startY
});
```

The delay is set to `300` for the entire animation, but I'd love to somehow stagger the animation of the `x2` and `y2` properties so it comes in maybe `200ms` later. Is this possible to do within the same animation, or do I need to set two like this (which doesn't seem to work):

```
line.animate(400, SVG.easing.expoOut, 300).attr({
	x1: startX,
	y1: startY
});
line.animate(400, SVG.easing.expoOut, 500).attr({
	x2: startX,
	y2: startY
});
```

**Comment by Fuzzyma** [comment]
Looks like we need chainable animations here which is somthing which should be implemented in version 2 some day (#225)

**Comment by brandondurham** [comment]
Is it possible with `during()`?

**Comment by jonesrussell** [comment]
I wouldn't mind helping with this feature.  I needed to move some little bits in a chain-able path, with their own durations.  You can see my dirty method here:

https://github.com/jonesrussell/bell-creek-ore-processing-plant/blob/master/app/scripts/ore-animation.js
https://github.com/jonesrussell/bell-creek-ore-processing-plant/blob/9ffb1644a73e430e8d271961c84c7d619cddee95/app/scripts/svgjs_anim/ore.js

I am doing two more animations soon and I would love to have this feature.

**Comment by Fuzzyma** [comment]
Yes it is possible with `during` - kinda.
`during` gives you the position of the animation from 0 to 1 which means if the animation is 5sec long you would have to start the second part of the animation maybe at 0.5. The problem is, that the scale is nonlinear when easing is used which makes it hard to determine the right position

**Comment by brandondurham** [comment]
Yeah. Just tweaked the animation accordingly. Shall I close?

**Comment by Fuzzyma** [comment]
jep^^
@jonesrussell thx for your code but it's hard to use your functions because you wrapped them AROUND svg.js. An implementation into the core would be very very nice! :)
