### ISSUE TITLE
Modify element created with use()

### ISSUE THREAD

**Issue by jpgamaral** [wout/svg.js#346]
Hello,

I wanted to modify an element (character with head, body, legs, etc) I created with use(). I tried modifying the reference but I can't access it using element.reference('href'), I get "undefined" back.

How should I proceed?

Thanks.

**Comment by Fuzzyma** [comment]
Can you please show your example or (even better) create a fiddle?

**Comment by jpgamaral** [comment]
Throughout my web app I have a character that I want to modify (change hair color, change hairstyle, switch pants for shorts, etc) depending on what the user answers to the questions.

		scenes.forEach(function (scene, index) {
			scene.use('main_character', path_ab + 'vectors/main_character.svg')
				  .move('45%', '21%')
				  .attr({ 'class': 'main-character', 'id': 'main-character-' + (index+1) });
		});

If I then use SVG.get('main-character-1').reference('href') I get undefined. How can I modify the character by acessing its contents (hair group, tshirt group, face group, etc)?

**Comment by Fuzzyma** [comment]
You cant alter an SVG in another file which is only referenced from use.
You link to an SVG which is outside of the scope of the current SVG-instance. That cant work!
That said its only consistently that the reference call returns undefined
