### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by damiangill** [wout/svg.js#350]
The hrefs of index links do not have corresponding anchors in the documentation text.  It would be very helpful if they worked correctly (it's a lot to scroll through on one page).

Thank you for the excellent work you have done on this library!

**Comment by Fuzzyma** [comment]
Which doc do you mean exactly? I know at least 3 places with a doc from svg.js

**Comment by pjfsilva** [comment]
The link that is on svgjs.com homepage: http://documentup.com/wout/svg.js

**Comment by Fuzzyma** [comment]
I think only wout can change the docs

**Comment by pjfsilva** [comment]
Is there any place else where the docs are still working OK? it seems the cause was the latest commits

**Comment by wout** [comment]
@Fuzzyma The docs on documentup are generated automatically from the README file every time you push changes. I also noticed the docs are no longer working which is a bummer! I'll contact documentup to see what's the problem.

**Comment by wout** [comment]
I notified the author of documentup and he informed me he was working on a complete rewrite of the app. I believe he finished the rewrite because the docs are working again: http://documentup.com/wout/svg.js
