### ISSUE TITLE
Uncaught TypeError: element.array.morph is not a function

### ISSUE THREAD

**Issue by inluxc** [wout/svg.js#354]
I get this error when i had animate
```
var draw = SVG('drawing').size('100%', 380);
var leftContent = draw.polyline('0,0 0,0 0,0 0,0').fill('#ddd').stroke({ width: 0 });
leftContent.animate().plot([['0,0'],['0,340'],[position['lX2']+',340'],[position['lX']+',0']]);
```

**Comment by Fuzzyma** [comment]
Thanks for reporting this. I found the error and will fix it.
However, your example has mistakes in it. Corrected and ready to try:

    var draw = SVG('drawing').size('100%', 380);
    var leftContent = draw.polyline('0,0 0,0 0,0 0,0').fill('#ddd').stroke({ width: 0 });
    leftContent.animate().plot([[0,0],[0,340],[70, 340],[90,0]]); // Note the missing quotation marks
