### ISSUE TITLE
Initialise on a dom element?

### ISSUE THREAD

**Issue by MeirionHughes** [wout/svg.js#355]
I would like to initialise on a dom element, rather than a string.like: 
```javascript
var draw = SVG(element).size(300, 300)
```
 Unfortunately it not liking it. I can't actually see anything in the documentation that discusses it either. 

Is it possible?

**Comment by MeirionHughes** [comment]
never mind, looks like I have to supply the actual svg element rather than the parent div. as per SVG.Doc: 
```javascript
element = typeof element == 'string' ?
        document.getElementById(element) :
        element
```

**Comment by Fuzzyma** [comment]
Svg(Id of div)  initialise a new svg in the div. Where is the problem?

**Comment by MeirionHughes** [comment]
I don't have an id. its a view template bound to a viewmodel. There are multiple copies.

**Comment by Fuzzyma** [comment]
You can also initialize an svg in a div when you call

    SVG(div-node)

**Comment by MeirionHughes** [comment]
I specifically needed to search for svg element relative to another element, because I'm making reusable components in aurelia: 
So this works in the end: 
```javascript
import {inject} from 'aurelia-framework';
import SVG from 'svg.js';

@inject(Element)
export class Widget {
  constructor(element) {
    this.element = element;
    this.title = "Widget!";
  }

  draw(svgElement) {
      var draw = SVG(svgElement);
      var rect = draw.rect(100, 100).attr({fill: '#f06'})
  }

  attached() {
    var svgElement = this.element.querySelector('svg');
    if(svgElement)
      this.draw(svgElement);
  }
}
```
