### ISSUE TITLE
Uncaught TypeError: undefined is not a function - getAttribute('stroke'), line 920 (v2.0.2)

### ISSUE THREAD

**Issue by parabolika66** [wout/svg.js#357]
Hi,
I use svg.js v2.0.2 in combination with svg.select.js v1.0.4.
When selecting a rectangle on mousedown I get the follwing error on line 920 of svg.js:
Uncaught TypeError: undefined is not a function
```
node.getAttribute('stroke')
```
Any ideas?
Thanks!

**Comment by Fuzzyma** [comment]
Could you post your code please?

**Comment by parabolika66** [comment]
these are the essential lines of code:
```
tool.component = null;

tool.component.on('mouseup', function (event) {
        this.select();
}, false);

// the rectangle is being drawn on mousedwon/move/up events
tool.component = tool.drawingPad.rect(0, 0, 0, 0);
//...
```

**Comment by Fuzzyma** [comment]
I am pretty sure you mixed up the order of the code because you cant call `on` on the `null`-object
Furthermore `rect` is called with only 2 parameters (width and height).

However: Your code is not very essential because this gives no error:

```javascript
    var r = draw.rect(100, 100);
    r.on('mousedown', function(){
        this.select();
    })
```

Give me some more. A stacktrace would be very cool, too

**Comment by parabolika66** [comment]
No, I don't think this can be the problem. I'll give you some more code. As it is scattered over a number of files I copied only parts of it. So when I finish drawing my rectangle, the mouseup event is assigned to the component. 

// this is called in a mouseup event
tool.onmouseupTemplate = function () {
        tool.mousedown = false;
        tool.originalX = 0;
        tool.originalY = 0;

        if(tool.component) {
            tool.component.on('mouseup', componentOnMouseUp, false);
        }

        $rootScope.$broadcast(tool.DRAWING_ENDED_EVENT);
};

var componentOnMouseUp = function () {
        console.log('clicked on component ' + this.id());
        this.select();
};

Stacktrace:
![bildschirmfoto 2015-06-25 um 08 55 49](https://cloud.githubusercontent.com/assets/10995253/8348936/e57edbb4-1b18-11e5-9b42-e37838ab73f2.png)

Thank you very much!

**Comment by parabolika66** [comment]
btw:
the selection works fine when I delete this code in svg.js:
```javascript
node.getAttribute('stroke') ||
```

**Comment by Fuzzyma** [comment]
Just to doublecheck the error: Could you give me the svg created to the point at which the error occurs?
Also mark somehow on which element `select` is called. Make sure to NOT reformat the code. I need the code the way the browser sees it

**Comment by Fuzzyma** [comment]
Fixed that with the last commit
