### ISSUE TITLE
Symbol no longer works as documented in version 2.0.2

### ISSUE THREAD

**Issue by gerrat** [wout/svg.js#358]
[This example in the svg.js documentation](http://documentup.com/wout/svg.js#symbol) no longer works.  

Javascript reports : "TypeError: symb.rect is not a function"

[Codepen example here](http://codepen.io/anon/pen/wapKMJ)

**Comment by Fuzzyma** [comment]
Found the mistake - thank you for reporting

**Comment by gerrat** [comment]
Works great!  Thanks for the quick fix!
