### ISSUE TITLE
Import svg doesn't work anymore

### ISSUE THREAD

**Issue by ThibaultR** [wout/svg.js#360]
Hi !

I was using svg.js (1.1.0) with svg.import.js to import my svg and it worked pretty fine. Then I tried to update my svg.js to (2.4.0) that have its own import functionnality and decided to try that way but it doesn't seem to work anymore. Indeed, I get this error: 
```
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'. 
svg.js:1101
```

At line 1011 in svg.js you have this:

```javascript
// transplant nodes
  for (var i = 0, il = well.firstChild.childNodes.length; i < il; i++)
           this.node.appendChild(well.firstChild.childNodes[i])
```

Is this really what you mean to do ? because from [documentation of appendChild](https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild):

> Adds a node to the end of the list of children of a specified parent node. If the node already exists it is removed from current parent node, then added to new parent node.

So when you append a child it is removed from the childNodes list so you end up trying to add undefined elements...

This should do the trick, I don't know if there is a better proper way to do it:
```javascript
// transplant nodes
  for (var i = 0, il = well.firstChild.childNodes.length; i < il; i++)
           this.node.appendChild(well.firstChild.childNodes[0])
```

**Comment by Fuzzyma** [comment]
Thats indeed a mistake. Thanks for reporting that.
I would recommend using `firstChild` instead of `childNodes[0]` but that are peanuts.
I will include that in the next bugfix!

**Comment by ThibaultR** [comment]
Thanks, keep up the good work ! :)

I have an other question, since [this commit (2.0.0)](https://github.com/wout/svg.js/tree/843c0f5b0f7140c4d46d92293c2c18767d070f69), there is a `select()` method in svg.js (same as import, it wasn't there in svg.js 1.1.0 that I used). 
So how am I supposed to do to use the svg.select.js plugin ? Because `mySvg.select()` now call the svg.js function and not the svg.select.js one. 
Is this supposed to replace the plugin ? because it doesn't work the same way at all and I can't use svg.resize.js :(

Or maybe there is some javascript trick that I am not aware of, to use the plugin function via namespace or something ? (I'm quite new to javascript ^^)

**Comment by Fuzzyma** [comment]
No, you are right. The plugin needs to be renamed. But at the moment selecting of parent elements doenst work anyway (not sure if i fixed that) and the select-method of svg.js should only be available at container-elements (?!)
