### ISSUE TITLE
Element.move() applied to an SVG.G generates NaN transform in Latest Safari

### ISSUE THREAD

**Issue by chrismichaelscott** [wout/svg.js#364]
In Safari 8.0.5 if you create a simple group then move it, a transform string is applied with NaN values. This does not happen on older Safaris so it could be related to an update.

    var rectgroup = chart.group();
    var rect = chart.rect(10, 10);
    rectgroup.add(rect);
	
    rectgroup.move(100, 100);
    console.log(rectgroup);

Resulting transform is: matrix(0,0,0,0,NaN,NaN). A screenshot is attached.
![screen shot 2015-07-21 at 11 30 41](https://cloud.githubusercontent.com/assets/1412521/8798819/21bf4260-2f9d-11e5-9223-58e20ffeff48.png)

This issue does not affect Chrome or Firefox.

**Comment by Fuzzyma** [comment]
still an issue?
