### ISSUE TITLE
Multiple clipWith calls cause many clip path definitions to be created

### ISSUE THREAD

**Issue by seveibar** [wout/svg.js#371]
Multiple clipWith calls with same elements causes many clip path definitions to be created-

```javascript
var a = root.rect(100,100);
var b = root.rect(50,50);

for (var i = 0;i < 100;i++){
a.clipWith(b);
}
```

The intended behavior is probably to do nothing.

**Comment by seveibar** [comment]
JSFiddle: https://jsfiddle.net/w5zod1m3/6/

**Comment by Fuzzyma** [comment]
The clipPath holds no references to its content. So every time you call clipWith, it will create a new clipPath not knowing that it is the same. For your purpose just create a clipPath first:

```javascript
var b = root.clip().add(root.rect(50,50));

a.clipWith(b) // wont create a new clipPath every call now

```

or do it once and remember the clipper:

```javascript
a.clipWith(b);

console.log(a.clipper); // holds the clipPath for reusing
```

**Comment by seveibar** [comment]
Sounds like this behavior is intended :) thanks @Fuzzyma!
