### ISSUE TITLE
transform bug

### ISSUE THREAD

**Issue by rdfriedl** [wout/svg.js#374]
i used svg.js 1.0.1 in my last project, im starting a new project and id like to use the latest version of this awesome library, but iv run into a few problems...

my next project will allow the user to select some elements on the svg, and to show that they are selected i want to put a Rect over the element (like a selection box).
this worked fine in v1.0.1 but with the new transform changes in 2.0.* it dose not work.

here is a link to a jsFiddle example http://jsfiddle.net/1ne468sf/3/
as you can see the first one is perfect, but when it moves to the second one the transforms x & y mess it up.
and here is a jsFiddle example of it with v1.0.1 http://jsfiddle.net/p2xz53ne/2/

if someone could explain to me whats going on here that would be great.
thanks.

**Comment by Fuzzyma** [comment]
I have no time to look into your problem at the moment but I can lead you
to the select.svg.js plugin which does exactly what you want. It should
work with transformations, too.

However I will have a look at this when I find some time

rdfriedl <notifications@github.com> schrieb am Sa., 22.08.2015, 16:13:

**Comment by rdfriedl** [comment]
thanks ill take a look at select.svg.js if nothing else i can use it as an example to find out whats going wrong with my code.

**Comment by Fuzzyma** [comment]
Fixed it: http://jsfiddle.net/1ne468sf/4/
You did not specify a rotation center when creating the elements. Its not the elements center by default

**Comment by rdfriedl** [comment]
thanks, this will help out a lot :)
