### ISSUE TITLE
Animation with each step calls

### ISSUE THREAD

**Issue by sergeyMelentyev** [wout/svg.js#375]
Hello,
I am trying to use svg.js with svg.connectable.js
As a simple example I have two rectangles with one connectable line between.
Next step is animation: rect.animate(2000, '>', 100).move(150, 150);
But here comes an issue - svg.connectable.js by default listen to
elmSource.on("dragmove", con.update);
elmTarget.on("dragmove", con.update);
Connectable line upgrades only after 'dragmove' event fires, or I could also call update() method after each svg.js step.
My question is - how I can listen to the each step in animate() and call update() method on svg.connectable.js
?

**Comment by Fuzzyma** [comment]
Take a look at the `during`-function: https://github.com/wout/svg.js#during

**Comment by IonicaBizau** [comment]
@Fuzzyma Thanks! I tested it [here](http://jsfiddle.net/c8qbjbb4/) and it's working as expected. :+1: :cake:

**Comment by IonicaBizau** [comment]
And here is a demo how to  use it with [svg.connectable.js](https://github.com/jillix/svg.connectable.js): http://jsfiddle.net/prkvq6mb/1/
