### ISSUE TITLE
Changelog 2.0?

### ISSUE THREAD

**Issue by villanus** [wout/svg.js#376]
How do I find a changelog for 2.0?
Are plugins no longer supported?

Also, who owns the project now?  Still wout?

**Comment by villanus** [comment]
Sorry I found the changelog:
https://github.com/wout/svg.js/blob/master/CHANGELOG.md

But cannot understand when moving to version 2 is a good idea?

**Comment by akauppi** [comment]
I'm also pondering this at #378

**Comment by Fuzzyma** [comment]
wout has no time for this project anymore. Thats why I am the one looking over it.
Version 2 has some major improvements but you dont have to use it when you dont need this features.
Many plugins dont work with version 2 cause there are breaking changes. However, e.g. the export or adopt plugin are implemented in the core of version 2 anyway.

**Comment by Fuzzyma** [comment]
No I am sorry there is no guide. But mostly all former references like `parent` is now a method `parent()` beside that nothing that much changed. I would just try it and then look what breaks
