### ISSUE TITLE
Line connector not displayed but endpoints are displayed in latest svgjs version

### ISSUE THREAD

**Issue by kiriti999** [wout/svg.js#377]
Using the following:

svg js,
svg.connectable.min.js
and svg.draggy.min.js

I am creating a line connector using dragdrop as shown in this example: http://jsfiddle.net/L2sjjc3b/16/

But the same is not working in my program. I can see the line path is created in console but not displayed in output. Here's my plunker: http://plnkr.co/edit/oAQ4bj4WhXdLxPg8eCyL?p=preview

![screenshot_2](https://cloud.githubusercontent.com/assets/13074074/9466591/846a2dfe-4b53-11e5-87e0-67dcdecc455c.png)

<div id="canvas" tabindex="0">
    <script>
        var draw = SVG('canvas').size('100%', '100%');
        var clientX, clientY, offsetX, offsetY;
        var x, y;
        var shapeId = "";

        function getId(id)
        {
            shapeId = id;
            console.log(shapeId);
        }
        function createShape(event)
        {
            var $stageContainer = $("#canvas");
            var stageOffset = $stageContainer.offset();
            clientX = event.clientX;
            clientY = event.clientY;
            offsetX = stageOffset.left;
            offsetY = stageOffset.top;
            x = clientX - offsetX;
            y = clientY - offsetY;
            console.log("x is: " + x + " " + "y is: " + y);

            switch (shapeId)
            {
                case('newConnector'):
                    createLine(x, y);
                    break;
                default:
                    console.log("Nothing to drag");
            }
        }
        function createLine(x, y)
        {
            var links = draw.group();
            var markers = draw.group();
            var nodes = draw.group();

            var g1 = nodes.group().translate(20, 80).draggy();
            g1.circle(10).fill("#FF5252").opacity(0.4);

            var g2 = nodes.group().translate(100, 80).draggy();
            g2.circle(10).fill("#C2185B").opacity(0.8);

            var conn1 = g1.connectable({
                container: links,
                markers: markers,
                marker: 'default',
                targetAttach: 'perifery',
                color: 'black'
            }, g2);
        }
    </script>
</div>

I fixed it by using the old version: http://cdnjs.cloudflare.com/ajax/libs/svg.js/1.0.1/svg.min.js

Please fix the latest version as well. Thank you

**Comment by Fuzzyma** [comment]
Did you think about adapting the plugin to the lib and not the other way round?
Cause thats how things are working
