### ISSUE TITLE
Latest stable download: 1.0.1 or 2.0.5?

### ISSUE THREAD

**Issue by akauppi** [wout/svg.js#378]
I'm considering moving a project to use svg.js. Which version would be best to learn and use?

The project [website](http://svgjs.com) still lists only 1.0.1 (from 2014) as the downloadable version. GitHub releases has [2.0.5](https://github.com/wout/svg.js/releases/tag/2.0.5).

Should the website be updated, or are the 2.0.x versions still experimental in some way?

Thanks for the help.

**Comment by Fuzzyma** [comment]
The website is outdated and svg.hs v2 is a full release.
