### ISSUE TITLE
Image used as fill in circle problem

### ISSUE THREAD

**Issue by cretace** [wout/svg.js#379]
I have a loop putting 12 images in stroked circles - works fine, using add to group.
I then want to place one bigger image in the centre of all 12, inside a larger stroked circle.
But whatever I do I cannot get this last image to center inside its stroked circle . 
If I move the image using x and y values (or 'move' or 'center') all that happens is that the image gets clipped down to a smaller size, so it cannot fill the circle.
Its as if 'move' is shifting a clipping area - but I am not using 'clip'.

**Comment by Fuzzyma** [comment]
I have no idea what you are talking about

**Comment by cretace** [comment]
The photos are arranged as on a clock face - I can move a photo within it's stroked circle using 'move'.
I then want a bigger circle in the centre with another picture inside.
But as I try to move the picture it gets clipped to a smaller rectangle within the circle. 
I think it's becuse it's a 'pattern' and the spaces between each element are expanding.
I solved it by putting the central item in another div layered on top.

**Comment by Fuzzyma** [comment]
You know - a fiddle would be awesome

**Comment by cretace** [comment]
I've made two fiddles 
one in all one div where I have the alignment problem on central pic
https://jsfiddle.net/ckoqfvb8/1/

And one with my extra div that fixes it in a hacky way.: 
https://jsfiddle.net/51ub13kh/2/

**Comment by cretace** [comment]
the issue is caused by .size(n,m)
docs imply that that will scale an image - but the first value sets an apparent clipping box width, while second value scales the entire image, in proportion, based on the y height. So either the docs are unclear or the code has a bug ; )

**Comment by Fuzzyma** [comment]
No it is not.
Here is a fiddle explaining what actually goes on when you use images and pattern:
https://jsfiddle.net/ckoqfvb8/3/

From the fiddle:
```javascript
// svg always preserves the aspect ratio on images. You have to disable it
var image = draw.image('http://i.imgur.com/97fGZHR.jpg').attr('preserveAspectRatio',"none")

// dont move the image in the pattern.
// You end up creating free space when you move the image out of the pattern
image.size(220,220)//.move(-34,-12)

// I made the circle bigger so you can see how pattern works
// You can get the pattern reference with the same named method and move the whole pattern instead of the image inside it
var circle = draw.circle(centrepicsize)
    .attr({ fill:image,stroke:'#c66','stroke-width':9 }).move(330,270)
    .radius(420).reference('fill').move(20)
}) 
```

So the lib is fine, and I lost an hour searching for you mistake :P

**Comment by cretace** [comment]
Ok, then the documentation meeds updating. 
I said "I think" and  "..either the docs are unclear or the code has a bug".

**Comment by Fuzzyma** [comment]
In this case you just need to learn how pattern works and you have to know how images work in svg. Both has nothing to do with the documentation

**Comment by cretace** [comment]
If you know SVG so well you should have recognised my problem in sceonds.
What am I meant to do?
I Googled it extensively. I know what patterns are. I made Fiddles to help pinpoint the issue - but you still complain I wasted your time.

**Comment by Fuzzyma** [comment]
Thats the thing. I really dont know much about svg. I have to dig myself into the issue everytime.
I just wanted to point out, that the docs are still up to date at this point.
I am not mad at you and thankful for the fiddles!
