### ISSUE TITLE
Animation Rotate

### ISSUE THREAD

**Issue by pabloriera** [wout/svg.js#380]
Hi.

If I do a immediate rotation like:

```
rect.rotate(X);
```

The rect objects goes to a rotated position of X degrees, but if I do 

```
rect.animate().rotate(X);
```

The objects first goes to the X rotated position, but if I repeat the action the objects starts incrementing the angle of rotation by X. This behaviour is deliberate by design or is not?

By the way, the library works great.

**Comment by Fuzzyma** [comment]
Please add a fiddle for me

**Comment by pabloriera** [comment]
Hi! Thanks for the reply.

Here is the fiddle
https://jsfiddle.net/Ln5thhhn/

When the move button is pressed the rect goes to a fixed position, and stays there if you press again. But if you pressed rotate before, it starts rotating. In the other hand, one click on rotate, makes the rect fo to the 45 angle position, but if you keep on pressing, it starts rotating counterclockwise at 45 steps.

Maybe all of this is deliberate behavior, but is tough to get what I need, that is a simple goto X,Y position and with an A angle.

Thanks

**Comment by Fuzzyma** [comment]
Ok - that is really ridiculous. I dont know when I find time to look into this issue.
Everything which is connected to transformations is wired to debug

**Comment by JKillian** [comment]
I'm also getting weird behavior: https://jsfiddle.net/266ue769/1/

**Comment by maryisdead** [comment]
+1 `animate()` seems to work with some relative values.

Simple example: http://jsfiddle.net/maryisdead/bpj7b04m/

Just move the mouse over the rectangle quickly and it won't reset correctly.

**Comment by Fuzzyma** [comment]
Please take a look at #385 where I ask about intended behavior. It would help much if you could leave your thoughts about that!
