### ISSUE TITLE
Pattern Rotation

### ISSUE THREAD

**Issue by inluxc** [wout/svg.js#383]
Can you please add rotation for the patterns?
Thanks.

**Comment by Fuzzyma** [comment]
<img src="https://pbs.twimg.com/profile_images/467672610919022593/JU7-IRiY_400x400.jpeg">

**Comment by Fuzzyma** [comment]
Just joking.
Can you give me a link or somewhat where this pattern rotation is explained?

**Comment by inluxc** [comment]
Here it goes :p

http://tutorials.jenkov.com/svg/fill-patterns.html
http://vanseodesign.com/web-design/svg-pattern-attributes/
