### ISSUE TITLE
Version 2.0.5 Problem with Prototype.js

### ISSUE THREAD

**Issue by inluxc** [wout/svg.js#384]
I using svg.js with magento and it has prototype.js, and i getting an error.

```
findAll	@	prototype.js:883
SVG.utils.filterSVGElements	@	svg.min.js:229
SVG.Parent.SVG.invent.extend.children	@	svg.min.js:2197
SVG.Parent.SVG.invent.extend.index	@	svg.min.js:2224
SVG.Parent.SVG.invent.extend.has	@	svg.min.js:2220
SVG.Parent.SVG.invent.extend.add	@	svg.min.js:2203
SVG.Parent.SVG.invent.extend.put	@	svg.min.js:2215
SVG.Polyline.SVG.invent.construct.polyline	@	svg.min.js:3162
SVG.prepare	@	svg.min.js:157
SVG.SVG	@	svg.min.js:28
(anonymous function)	@	site.js:29
m.Callbacks.j	@	jquery-1.11.3.min.js:2
m.Callbacks.k.fireWith	@	jquery-1.11.3.min.js:2
m.extend.ready	@	jquery-1.11.3.min.js:2
J	@	jquery-1.11.3.min.js:2
```

Looks like and error with the new function:
```
filterSVGElements: function(p) {
    return [].filter.call(p, function(el){ return el instanceof SVGElement })
  }
```

Version 2.0.0 was working fine :P

**Comment by Fuzzyma** [comment]
If you are already that far, why not test it further? I dont use prototype and it would be awesome if you would track down the error. I am a bit short on time atm to dig into a new library for that.

**Comment by inluxc** [comment]
Ok, i found the problem, prototype.js 1.7.0 overrides filter function, we have to update prototype to 1.7.2, to resolve this problem.

:D

**Comment by Fuzzyma** [comment]
Never ever play with the native API :P
