### ISSUE TITLE
Custom build feature proposal

### ISSUE THREAD

**Issue by fibo** [wout/svg.js#388]
Hi all,

in order to achieve a lighter dist of svg.js, I tryed this approach https://github.com/fibo/svg.js/commit/873c1ded13a9fa16323db1f81e53455d05f0140c where I created a separated *parts.json*. A similar feature was asked in https://github.com/wout/svg.js/issues/276.

The question is, how it could be specified a custom *parts.json* file? Maybe with some gulp command line option, or using an environment variable like `SVGJS_PARTS=src/parts-custom.json' ?

What do you think about it?

**Comment by Fuzzyma** [comment]
Why cant you just comment out the modules in the gulpfile? Its actually not that complicated

**Comment by fibo** [comment]
Cause it would be nice to have a procedure to build a custom svg.js that could be used by all users and also automated. The result would be a lighter dist file.

Your hint is ok, is fast, I am just askying if you think it is worth to make it configurable. Consider what happens when you pull from the upstream remote (wout/svg.js). You should merge the comments?

**Comment by Fuzzyma** [comment]
The gulp file can be used by all isses. There is no magic at all. For the
merge thing you have  point. But you get the same problem when I add
something like a modules.json where all active modules are listed. You only
move the problem.
However feel free to setup a pr for the gulp file where you add a parameter
to load  custom list.

Gianluca Casati <notifications@github.com> schrieb am Fr., 09.10.2015, 9:41:

**Comment by fibo** [comment]
Ok, thank you for the feedback. I will procede in this order: first trying just forking and commenting out parts I can exclude. If I find a way using a gulp command line parameter that can help also other people I will do a pull request.

**Comment by fibo** [comment]
I will delete my fork and create a new one so the commit link above will be broken (i guess :)

**Comment by fibo** [comment]
By the way I could comment out few parts, since many elements depend on each other: for example, sugar.js needs existence of few functions.

On the other hand, files like polyfill.js are needed only by IE <10.

As a first result I could get a 100k build with this custom [gulpfile](https://github.com/fibo/svg.js/blob/5c5d5186644a15b101b02719ec61d4fd06b734ed/gulpfile.js).

The good part is that if new features will be added later in svg.js I will be able to include them only if needed. Probably it could be possible to reduce the build up to 60k by creating fake functions like SVG.Gradient, which is not used by my [flow-view](http://g14n.info/flow-view/) project, but it is needed only cause it is referenced by other parts like sugar.js

**Comment by Fuzzyma** [comment]
DId you actually look into the code pieces you comment out?
I can imagine that you would loose the ability to move a polygon or set their size.
Also the polyfills are needed for the whole IE-world (custom events).

If you are that curious about traffic: what about reducing your image quality? That would do a much more difference. Also you can ship all your code gziped.

**Comment by fibo** [comment]
Thanks for the hints, I am using a subset of svg.js features: I am not using polygons for example. Also I am not using images, since I am building a tool, not a website. Also I am not planning to support older version of IE.

**Comment by Fuzzyma** [comment]
The problem with the polygon applies to lines and polylines, too. If you dont polygons you can remove this part of the lib, too.

And when I say the whole IE-world i mean ALL of them. CustomEvent needs a polyfill in IE11 to work. Well - maybe 11 is "old", too. I would not count on it.

**Comment by Fuzzyma** [comment]
Addiotionally: the min-version of svg.js is only around 50 kB (gziped 14 kB)
