### ISSUE TITLE
GUI for drawing flowcharts?

### ISSUE THREAD

**Issue by ThorsenRune** [wout/svg.js#390]
Hi, (sorry for probably posting at the wrong place).
Has anybody wrapped this into an application for making and editing diagrams (UML) etc. ?
Preferably with connectors!?
I've been trying SVG-EDIT but it doesn't work very well. (Can't edit grouped texts etc)

**Comment by Fuzzyma** [comment]
This is something nobody would answer here because people who are interested in _issues_ are coming to this place. Your question is better placed at stackoverflow.

However there is a connectable plugin for this lib to conntect 2 shapes. Thats all I can say

**Comment by ThorsenRune** [comment]
Ok. Posted:http://stackoverflow.com/questions/33124386/svg-js-gui-for-drawing-flowcharts
