### ISSUE TITLE
Creating markers leads to an infite loop

### ISSUE THREAD

**Issue by MrGde** [wout/svg.js#392]
Creating a marker just like in the documentation doesn't work - Browser is stuck in an infinite loop.

I'm using the latest version of svgjs.js 2.1.1 (BUILT: Sun Oct 11 2015).

Example code:
    var path = draw.path('M 100 200 C 200 100 300  0 400 100 C 500 200 600 300 700 200 C 800 100    900 100 900 100z')
    path.fill('none').stroke({ width: 1 })
    path.marker('start', 10, 10, function(add) {
      add.circle(10).fill('#f06')
    })

**Comment by Fuzzyma** [comment]
uiuiui - a loop in the new bbox section. I will fix that. Thank you!
