### ISSUE TITLE
text() returns undefined

### ISSUE THREAD

**Issue by erivas3649** [wout/svg.js#393]
After importing an svg into canvas, the text() function returns undefined until the element is modified.

**Comment by Fuzzyma** [comment]
please show me your code

**Comment by erivas3649** [comment]
//Import
draw = SVG("canvas").size(view.width, view.height);
draw.svg(data.svg);			
draw.each(function(){
      if(this.type == 'image' || this.type == 'text'){
	    this.click(onMouseClick);
}

//OnMouseClick
function showTextProperties (elem) {
	$("#text-content").val(elem.text());	// THIS RETURNS UNDEFINED
	$("#text-font").val(elem.attr("font-family"));
	$("#text-size").val(elem.attr("font-size"));
}

//The original SVG that i'm importing
<?xml version="1.0" encoding="UTF-8" standalone="no"?><svg height="591" width="1004" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" xmlns="http://www.w3.org/2000/svg" id="SvgjsSvg1000"><defs id="SvgjsDefs1001"></defs><text fill="#000000" font-size="22" y="262.1999626159668" x="311" font-family="Arial, Helvetica, sans-serif" id="SvgjsText1007"><tspan x="311" dy="28.6" id="SvgjsTspan1010">INSERT TEXT HERE</tspan></text></svg>

**Comment by joarobles** [comment]
same problem here!

**Comment by Fuzzyma** [comment]
Which version you are using?

**Comment by erivas3649** [comment]
svg.js v2.1.0

**Comment by Fuzzyma** [comment]
Its an easy fix though. Nevertheless it needs some thoughts about it because it leads to deeper changes.
For a quickfix use `textEl.node.textContent` to get the content of the text element

**Comment by erivas3649** [comment]
Ok, thanks!

**Comment by Fuzzyma** [comment]
text will now return the `textContent` of all nodes.
However note that the information about newlines (which are simulated by svg.js) are not exported and therefore not imported, too.

So when you create a text like `draw.text('Text with\nline break')` it will return that when calling `text()`. But when you export this snipped and import it again it will loose the `\n` and just return `Text withline break`.
I am considering to add a custom attribute in the svgjs namespace to save that information on the node when exported (like `<tspan svgjs:newline="true">FooBar</tspan>` but that needs to be thought through.
