### ISSUE TITLE
http://svgjs.com/clock/ doesn't work OK

### ISSUE THREAD

**Issue by pmros** [wout/svg.js#394]
[Clock demo](http://svgjs.com/clock/) doesn't work OK. Clock hands dissappear! I've tested on Firefox, Chrome (at desktop and mobile). However I've cloned [Clock repo](https://github.com/wout/svg.clock.js) and it works perfectly for me. Can you fix it?
Thank you for svg.js.

**Comment by wout** [comment]
The clock plugin will be rewritten soon. I'll close this issue for now.

**Comment by dgaenko** [comment]
Site is down?
