### ISSUE TITLE
Animate rotation problems I have had to user SnapSvg to work with

### ISSUE THREAD

**Issue by GrupoWebex** [wout/svg.js#395]
Hello.

I was doing a animate function, doing a transform on rotate, but it works really bad.
No correct degress. Relative switch fails. Error ocurrs when try to animate second time.
Diferent effects on same functions.

There is my code. You can click on first and third section for movement animation.
Actually im going to work with SnapSVG wich work well with.

*** see comment 3

**Comment by ibrierley** [comment]
I think it would be useful to break the code down into a specific small chunk, onto a jsfiddle or similar, highlighting the specific problem, as not really sure what its supposed to look like, or whats supposed to happen.

**Comment by GrupoWebex** [comment]
Yea sorry. You can test it here: http://jsfiddle.net/reocL50v/1/

**Comment by Fuzzyma** [comment]
Would you please add your thought to this issue: #385 ?
The rotation animation problems are not new. I could need a bit help with that

**Comment by ibrierley** [comment]
I'm not quite sure from the docs how animating a transform is supposed to work, so hesitant to suggest whats a bug, but it looks a bit counterintuitive. Maybe the docs need some more examples...there is a github entry at https://github.com/wout/svg.js/issues/385 worth following...

As per the original issue here, you can certainly work around the problem, and in many cases, this is what I would do in Snap in a similar fashion, ie include a function using 'during' and use its interpolation.

So for the example fiddle...
c12.animate(2000, '-').during( function(pos) {
                     c12.transform({ rotation: pos*85, cx:ocx, cy: ocy })
            });

I think this would achieve what you want, or if start and end needed, I note there is a morph aspect to the function.

So a cut down jsfiddle...

http://jsfiddle.net/reocL50v/5/ (click on grey bar)

**Comment by GrupoWebex** [comment]
continue on #385
