### ISSUE TITLE
svgjs:data redefined in Entity

### ISSUE THREAD

**Issue by erivas3649** [wout/svg.js#398]
Using the latest commit fd73060 I get "Attribute svgjs:data redefined in Entity".
Seems like the exported data has repeated svgjs:data attriibutes.

```xml
<text svgjs:data="{'leading':{'value':1.3,'unit':' '}}" svgjs:data="{'leading':{'value':1.3,'unit':' '}}" fill="#000000" font-size="33" y="357.1999855041504" x="277" font-family="Arial, Helvetica, sans-serif" id="SvgjsText1010">
<tspan svgjs:data="{'newLined':true}" svgjs:data="{'newLined':true}" x="277" dy="42.9" id="SvgjsTspan1038">Text Here</tspan>
</text>
```

**Comment by Fuzzyma** [comment]
How is this even possible? Can you pls show your code?

**Comment by erivas3649** [comment]
For import.
```javascript
	draw = SVG("canvas").size(view.width, view.height);	
	draw.viewbox({ x: 0, y: 0, width: view.width, height: view.height });
				draw.svg(data.svg);			
				draw.each(function(){
					if(this.type == 'image' || this.type == 'text'){						
						this.click(onMouseClick).mouseover(onMouseOver).mouseout(onMouseOut).draggable().on('dragstart', onDragStart);						
					}
				});
```

For Export
```javascript
var svgContent= draw.svg();
```

**Comment by Fuzzyma** [comment]
Whats in data.svg?

**Comment by erivas3649** [comment]
Data previously exported with the library.

**Comment by Fuzzyma** [comment]
which browser?

**Comment by erivas3649** [comment]
Iceweasel 42 a.k.a Firefox for Debian.

**Comment by Fuzzyma** [comment]
try adding the following line after line 1160 and see if the error disappears:

```javascript
this.node.removeAttributeNS(SVG.svgjs, 'svgjs:data')
```

**Comment by erivas3649** [comment]
No, the error remains.

**Comment by Fuzzyma** [comment]
sorry but I cant reproduce your error. I can export and import as often as I want. There always is only one attribute and no error appears

**Comment by Fuzzyma** [comment]
However it should work when you use:
```javascript
this.node.removeAttribute('svgjs:data')
```

**Comment by erivas3649** [comment]
In this fiddle (https://jsfiddle.net/3upj7e1o/) you can drag the text around, export, and import the previously exported data.
To reproduce the issue press export, then import, and finally export again, and see the duplicated data attributes in the textarea. Also you can see the nested svg elements each time you repeat the (export/import) cycle.

**Comment by Fuzzyma** [comment]
I still didnt get any error. However I can see what happens.
Did you try the fix above?

**Comment by erivas3649** [comment]
The duplicated attribute is the error, because the exported svg is malformed.
The library used in the fiddle has the fix applied.

**Comment by Fuzzyma** [comment]
Obviously it has not. Maybe you read again what I wrote.
The code may look similar - I still changed it

**Comment by erivas3649** [comment]
Sorry my bad. Your last fix resolves the duplicated attributes (AWESOME!).
It's normal for the imported svg to be nested? There's some way to avoid it?

**Comment by Fuzzyma** [comment]
Yes this is intended behavior. It was designed that way to not touch the svg around.
However I am not that happy with it either.
What do you think it should do?

- erase all content from the svg and display only the imported
- add all elements to the svg at the very end

I would vote for point 2

**Comment by erivas3649** [comment]
I think both of the possibilities should be available:
 - The import should erase all content from the svg and display only the imported.
 - Another function like "append" should allow you to "adopt" nodes from a string.
