### ISSUE TITLE
Using an existing svg element...

### ISSUE THREAD

**Issue by ibrierley** [wout/svg.js#399]
Not sure if I'm doing something I'm not supposed to, but I thought you could use an existing element (sure I have got this working before), by using SVG('elementid')

But if I try that, it seems to put an svg & defs element inside the rect element I am looking at. Minimal example at 

http://jsfiddle.net/tguko1wq/

Or right click rect and inspect element.

**Comment by Fuzzyma** [comment]
Try 'SVG.get(id)'  (my first thought)

**Comment by ibrierley** [comment]
Doesn't seem to work, have tried .get() and .select() and still seems the same.

**Comment by Fuzzyma** [comment]
`get()` DOES work - try again

**Comment by ibrierley** [comment]
Ah thanks, strange, it didn't seem to work earlier, but I can see get() does return the object, but you need to run SVG() before you can do certain things with it....eg

//this works, even though we don't use 's', but I'm guessing does some required initialisation
var s = SVG() 
var r = SVG.get('myrect');
r.rotate(20)

//this doesn't work, no rotation will happen
var r = SVG.get('myrect');
r.rotate(20)

Not sure if thats expected, or a bug, but can work, thanks for the help.

**Comment by Fuzzyma** [comment]
Instead of calling `SVG()` you can also directly call `SVG.prepare()` which more or less does the same when you pass no id to the constructor. It creates the parse svg-instance which is needed for certain things in svgjs

**Comment by ibrierley** [comment]
thanks!
