### ISSUE TITLE
Examples on front page not working

### ISSUE THREAD

**Issue by ibrierley** [wout/svg.js#401]
I think you're probably aware of some of these, but just mentioning in case
The clock, filter, animated textPath examples aren't currently working.

Clock I think is referenced with #394 and maybe related to animation at 380 or centre of rotation.

**Comment by Fuzzyma** [comment]
This examples still using svg v1. As I already said: I have no access to this page so I cant change it

**Comment by villanus** [comment]
Before you close this issue.   has Wout abandoned the project and are you now taking over?  If so, what is the correct version to use?   Its a little confusing because the site says use 1.1 for production and it links to 2.x.   

Also, what is the status of the various plugins?

Maybe its time to rebrand it to NEWSVG.js  or something different????

**Comment by wout** [comment]
Hi Guys,

Fuzzyma will be taking over because I no longer have the available time to continue with the project.
As for updating the webs page, if anyone designs something and sends it over, I'll make sure it gets published.

**Comment by Fuzzyma** [comment]
The newest release is always the version you should use - thats more or less the meaning of a release.
I dont see any reason to rebrand this library. Same api, same behavior. That would lead to confusion.

Regarding the plugins: I should didnt have time to look into all of them.
You just have to test that.

**Comment by ibrierley** [comment]
I think its purely the front page thats confusing a few people as things get out of date. Its hard for other folk to suggest what the front page updates should be, as they don't necessarily know.

**Comment by villanus** [comment]
can you please do a write up on using 2.0 versus the legacy 1.0 version?
Is there a reason to go to 2.0 if 1.0 is working?
Critical bugs? Performance?

**Comment by pmros** [comment]
https://github.com/wout/svg.js/blob/master/CHANGELOG.md

**Comment by villanus** [comment]
THANKS!!!
