### ISSUE TITLE
The cx, cy method of a group not working correctly

### ISSUE THREAD

**Issue by BurningLutz** [wout/svg.js#405]
Hi everyone,
I've got a problem when using the group in an SVG with `viewBox` set.
Here is the code:
```js
var g = SVG.adopt(groupElem);
g.cx(100);
g.cy(100);
console.log(g.cx(), g.cy());
```
the return value of cx or cy doesn't match what I set before.

**Comment by ibrierley** [comment]
A group element doesn't have a cx/cy, nor x,y,width,height etc, so to me its not clear what should happen (and potentially more fiddly than one would expect otherwise to cover all cases). You could possibly do something with transforms, but for those straightforward cases you could probably roll your own easy enough I would imagine.

You could probably use the bbox and the cx/cy from that, and do a transform I would imagine ?

**Comment by Fuzzyma** [comment]
Thats exatly what the lib is doing:
```javascript
    // Move by center over x-axis
  , cx: function(x) {
      return x == null ? this.tbox().cx : this.x(x - this.tbox().width / 2)
    }
```javascript

**Comment by BurningLutz** [comment]
Yeah, I know that a group element doesn't have a cx/cy, but what I think is that since the lib provides such methods for a group element, they should work correctly as if a group element DOES have a cx/cy, or x/y.

**Comment by Fuzzyma** [comment]
the cx method is implemented as you would think it is. Can you place an example about how much the values differs from eachother?

**Comment by BurningLutz** [comment]
Here is the code:
```html
<svg width="1000" height="500" viewBox="0 0 500 250">
  <g>
    <rect width="100" height="50"></rect>
  </g>
</svg>
```
then I ran the code below:
```js
var group = SVG.adopt(groupElem);
group.cx(200);
```
after that, the svg became:
```html
<svg width="1000" height="500" viewBox="0 0 500 250">
  <g transform="matrix(1,0,0,1,100,0)">
    <rect width="100" height="50"></rect>
  </g>
</svg>
```
and if I call the cx method without any parameter, it return a 300:
```js
group.cx(); // --> 300
```

**Comment by Fuzzyma** [comment]
hm - shouldnt it be translated by 150 instead of 100units? Even if you apply the viewbox zoom it does not calculate correctly (it would be 100 units in the elements system so it should translate to 50 instead of 100).
Seems like the tbox-function does some crazy stuff.
Thanks for the code!
