### ISSUE TITLE
line.x() produces Error "too much recursion" in Firefox

### ISSUE THREAD

**Issue by DetsCastelli** [wout/svg.js#408]
Hi, 
I currently upgraded from Version 1.0.1 to Version 2.2.0. Now calling line.x(n) produces an Error "too much recursion" in line 930 (this.node.instance = this) in Firefox 42.0.
Svg.js Version 1.0.1 works as expected. Both versions work in Chromium. 
Is there any workaround?

greetz, Dets

**Comment by Fuzzyma** [comment]
show me your code please

**Comment by DetsCastelli** [comment]
When preparing a clean version of my code, I found a workaround by myself: it seems that svg.js 2.2.0 doesn't like to move hidden lines. 
My line.x(n) was wrapped into line.hide() and line.show(). After removing these lines line.x(n) now works in firefox too.

Dets

**Comment by Fuzzyma** [comment]
I would like to find the issue anyway. I would need more surrounding code for this!

**Comment by DetsCastelli** [comment]
No problem:
a simple HTML page:
```
<!DOCTYPE html>
<html>
 <head>
  <title></title>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <script type="text/javascript" src="test.js"></script>
  <script type="text/javascript" src="svg.js"></script>
  <script type="text/javascript">
function init() {    
  grafik = new Grafik(); // Grafikobjekt erzeugen
  grafik.init();
}   
  </script>
 </head>
 <body onload="init()">
  <div id="clientDiv" style="background-color:#fffff0"></div>
 </body>
</html>
```
and the javascript file which displays a vertical bar under the mousecursor:

```
function Grafik() {
  var svg;                // Grafikbereich
  var cursorline;         // Instanz der Hilfslinien-Klasse
    
  // SVG initialisieren
  this.init = function() {
          
    // SVG für die Grafik
    svg = SVG('clientDiv').style({'position': 'absolute', 'left': '0px', 'display': 'block', 'background-color': '#e0e0e0'});  
    
    
    cursorline = new Cursorline();

    // wenn die Maus über die Grafik gefahren wird, dann Cursorlinie anzeigen    
    svg.mousemove(function(evt) {      

      // Zeile und Spalte berechnen
      var col = Math.floor(evt.clientX / 10);
              
      try {
        cursorline.setPos(col);
        
      } catch(e){
        console.log("Error: " + e);  
      }
    }); 
  };
      
  
  //****************************************************************************
  // Klasse zum Zeichnen einer vertikalen Cursorlinie
  //****************************************************************************
  Cursorline = function() {      
    var x = 0;
    var cline = svg.line(x, 0, x, 500).stroke({width: 10, color: '#c0e0ff'});           

      
    this.setPos = function(c) {
      
      // cline.hide();
      cline.x(c * 10 + 5);  
      // cline.show();
    };            
  };
}  
```
to reproduce the error, remove the slashes in setPos(), use svg.js Version 2.2.0 togesther with Firefox

**Comment by Fuzzyma** [comment]
Ah i see. For whatever reason I thought about a line of text the whole time.
Moving an invisible line indeed fails in FF because FF cant calculate the bbox of invisible elements.
The bbox method has a workaround for the general case, that the elements in the defs and therefore not visible but not for the case that they are hidden with css.
So just dont move invisible lines (or any other element using methods which are not native to the element e.g. cx, cy for circle).

You can ofc use `attr` on invisible lines, too
