### ISSUE TITLE
SvgPathSeg is removed in Chrome 48

### ISSUE THREAD

**Issue by jurebajt** [wout/svg.js#409]
Hi!

According to https://www.chromestatus.com/features#pathseg SVGPathSeg interface was a part of svg1.1 and will be removed. This brakes the drawing of paths in Chrome Canary (Version 48.0.2564.0 canary (64-bit)) using SVG.js version 2.2.0.

```
Uncaught TypeError: Cannot read property 'numberOfItems' of undefined
```

Call stack:
```
SVG.extend.parse (SVG.js:669)
SVG.Array (SVG.js:387)
SVG.PathArray (SVG.js:553)
SVG.Path.SVG.invent.extend.plot (SVG.js:3362)
SVG.Path.SVG.invent.construct.path (SVG.js:3397)
```

**Comment by danburzo** [comment]
:+1: I was about to write this one up as well
There's a polyfill that might be helpful: https://github.com/progers/pathseg
More discussion, for context: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/EDC3cBg9mCU

**Comment by Fuzzyma** [comment]
>**Compatibility Risk**
>Low, this feature is relatively obscure and didn’t gain much usage so the SVG WG decided it was best to remove it before usage grows.

Well...

> Can you please confirm for me that after your removal the only way to access this information in Chrome will be for us to parse the `d` attribute ourselves?

> Until the new API [1] matures and is implemented - yes that is correct

Is this a joke? Better lets remove a feature because a better feature *might* be coming in the future.

Sometimes I don't get these people...

However a big thanks for posting this!
I will try to fix this in 2.2.1

**Comment by Fuzzyma** [comment]
In my tests the new code was 100% faster - and its even less code ^^

**Comment by jurebajt** [comment]
Awesome!

**Comment by pjfsilva** [comment]
I know this is a hard request but I need to be stuck on svg.js 1.1.0 because of plugin dependencies so...

Is there any possibility we can backport this fix to 1.1.0 branch?

**Comment by ibrierley** [comment]
You can always include the polyfill listed above I assume.

**Comment by Fuzzyma** [comment]
yes thats right. just include the polyfill and it will work
