### ISSUE TITLE
Is there a destroy function?

### ISSUE THREAD

**Issue by cretace** [wout/svg.js#414]
Having a hell of a time clearing an svg - it gets redrawn in a different design for responsive mobile - but I can't get rid of previous svg when doing manual resize - a refresh fixes it, but I need to clear or destroy the previous svg on resize.

I've tried:
	$("#drawing".svg).empty();
	svg.selectAll("*").remove();

Any ideas?

**Comment by Fuzzyma** [comment]
`clear()`?

**Comment by cretace** [comment]
I don't understand SVG.
Should it be:
clear(mysvg)
or clear()
either way I then just get a blank screen.
Don't worry, I'll find a way eventually..

**Comment by Fuzzyma** [comment]
Maybe thats because your whole code is incorrect? Do you even use svg.js?

```javascript
$("#drawing".svg).empty(); // it should be $("#drawing.svg") or something
svg.selectAll("*").remove(); // svg.js has no selectAll method
```

Get your svg with id and clear it:

```javascript
var mySVG = SVG.get('id of svg')
mySVG.clear()
```

**Comment by cretace** [comment]
Yes I'm using svg.js - I was trying selectall in desperation

Anyway I found solution - doing both these works via my resize function:
	drawmainset.clear();
	drawmainset.remove();
Thanks for help
