### ISSUE TITLE
Throws an error when image loads but parent no longer exist

### ISSUE THREAD

**Issue by assembler** [wout/svg.js#415]
When upgraded from 2.1 to 2.2.1 I have started to get errors `Cannot read property 'instance' of null` (https://github.com/wout/svg.js/blob/master/src/svg.js#L94)

Digging deeper through stack trace, I have found out that it has to do with image onLoad callback (https://github.com/wout/svg.js/blob/master/src/image.js#L19).

This happens when the image loads, but the element where it was supposed to be drawn no longer exist (e.g. canvas was redrawn in the mean time). I'm not sure how this was handled in v2.1 but it wasn't throwing errors before I have upgraded.

**Comment by Fuzzyma** [comment]
The parent method was reworked in the 2.2 patch. Therefore it returns null if no element is found.
I will include a null-check which should fix this.
Thanks for reporting!
