### ISSUE TITLE
SVG Paths getting messed up

### ISSUE THREAD

**Issue by dhardtke** [wout/svg.js#416]
Take a look at this: https://jsfiddle.net/jm0tujnb/1/

As you can see if you open your DOM inspector SVG.js completely messes up the "d" attribute of the path.

It probably has to do with https://github.com/wout/svg.js/commit/cf783fca1213d26b50bc07af0ca7e2b0f6385401 I think.

**Comment by Fuzzyma** [comment]
The "parser" fails at the non-negative numbers starting with "." instead of "0."
This is fixed with the latest commit (a bit ugly but I saw no other possibilitiy).
