### ISSUE TITLE
Is there any way to delete element at the existing Group?

### ISSUE THREAD

**Issue by kangchals** [wout/svg.js#418]
Hi

I want to add some paths to the group and

when some event happen on a path, I try to delete the path in the group.

I found the function clear, but it seems that it destroy all the elements in the group.

Is there any way to delete a element in a group??

**Comment by Fuzzyma** [comment]
```javascript

var g = draw.group()
var rectInGroup = g.rect(100,100)

// later
rectInGroup.remove()

// or
g.get(0).remove()
// or
g.first().remove()

// or
g.select('rect').first().remove()
```

**Comment by kangchals** [comment]
Thank you!!!
