### ISSUE TITLE
moving element with image fill

### ISSUE THREAD

**Issue by robertmartin** [wout/svg.js#420]
Image used to fill an element does not render properly when the element is moved.
Steps to reproduce.
1. create an element (polygon in this case)
2. fill with an image (works so far)
3. animate.move (image is rendered in the wrong location)
    This looks very funny, albeit very non-functional. 
    Check it out with the the draggable plugin for a laugh.

The image used to fill an element should be static inside the element.
This is a show-stopper for me.

**Comment by Fuzzyma** [comment]
This is expected bahvior. Why on earth the fill should alter its position when the element is changed? The fill is only a reference and can be used multiple times in the whole document. Imagine you move one element and all other elements change their fill. No - thats not a good idea.

However you can ofc bind to the `dragmove` event to update the fill accordignly but thats nothing which svg.js will do by default.
For the animate you can use the `during` method to keep track of the changed

**Comment by robertmartin** [comment]
If you want people to use and enjoy something you create you certainly should not talk down to them.  Given your tone and unwillingness to help I have decided to move to a different library.

**Comment by Fuzzyma** [comment]
>> unwillingness to help
sorry?
