### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by I-NOZex** [wout/svg.js#421]
In RBOX section http://documentup.com/wout/svg.js#rbox  there is a typo:
Important: Mozilla browsers include stroke widths where other browsers do not. Therefore the resulting box might be different in **Mozulla** browsers. It is very hard to modify this behavior so for the time being this is an inconvenience we have to live with.

Bold word should be **Mozilla**

**Comment by Fuzzyma** [comment]
fixed
