### ISSUE TITLE
Hover on Rectangle

### ISSUE THREAD

**Issue by nattynatty** [wout/svg.js#422]
First thanks for this handy library.

Second, this might not be an issue at all in which case I apologize. 

I have created a jsfiddle here : http://jsfiddle.net/qyva4m18/

The issue is that on hover, the rectangle which is supposed to hover gets cropped. Is there a way to set the property so that it does not get cropped. Please note that this jsfiddle is a simplified use case of what I am trying to do.

Thanks

**Comment by ibrierley** [comment]
I'm guessing you will want to append the 'hidden rects' after all the initial rects have been added, as display is by DOM ordering

**Comment by Fuzzyma** [comment]
I cleared and fixed your fiddle: http://jsfiddle.net/qyva4m18/2/
Call `front()` to move it to the front (which just does what @ibrierley already mentioned: It put it at the first position in the dom)
