### ISSUE TITLE
How to copy a transform?

### ISSUE THREAD

**Issue by ThorsenRune** [wout/svg.js#423]
I don't understand the documentation about transform. I want to give object A the same transform as objec B and did:
A.transform(B.transform())
but it does not seem to work. I would expect
A.transform() to be equal to  B.transform() after that.
Could you please elaborate, (and then copy to the documentation)
Best Regards.

**Comment by Fuzzyma** [comment]
That's exactly how it's supposed to work. May you check the return value of
transform?
This could be a bug!

Rune Thorsen <notifications@github.com> schrieb am Fr., 04.12.2015, 15:27:

**Comment by ThorsenRune** [comment]
On crome 46 I do:
A=zsvg.rect(100,50).rotate(40).move(100,100)
B=zsvg.rect(100,50).rotate(20).move(200,100).fill('green').skew(3)
A.transform(B.transform())
A.transform()
Object {x: 11.565872543846297, y: -15.593322685931142, skewX: -20, skewY: 20, scaleX: 1…}
B.transform()
Object {x: -167.31620872575394, y: 142.69103399810294, skewX: 9.64992648932018, skewY: 0, scaleX: 1.132474331431794…}

as you see the matrixes are not identical. The objects are not transformed in the same way
On the other hand: if I do 
A.matrix()
end 
B.matrix()
they become reset to have the same shape
Hope it helps in debugging.

**Comment by Fuzzyma** [comment]
There is indeed a mistake made in the trasform function which only returns the extracted matrix values but not the matrix itself. For now you can use a hacky way.
You get the matrix when calling `matrixify` and pass it to the transform function:
```javascript
a.transform(b.matrixify())
```

Thanks for reporting. I will fix it as soon as possible

**Comment by Fuzzyma** [comment]
fixed in https://github.com/wout/svg.js/commit/3a6fe31f702078cee66118e2cb1b37d4e03c93e1
