### ISSUE TITLE
Hover over title

### ISSUE THREAD

**Issue by nattynatty** [wout/svg.js#424]
Why doesnt the mouseover work when hovering over text as shown in a simple test case below

http://jsfiddle.net/qyva4m18/5/

I have tried with SVG.select('text.class1') but still no luck? Anything I am missing here.

**Comment by Fuzzyma** [comment]
I dont see the problem: http://jsfiddle.net/qyva4m18/6/

**Comment by nattynatty** [comment]
Works. Thank you.
