### ISSUE TITLE
masks "targets" array gets deleted on remove

### ISSUE THREAD

**Issue by rdfriedl** [wout/svg.js#429]
im not sure if this is intentional but at [mask.js line 21](https://github.com/wout/svg.js/blob/master/src/mask.js#L21) the "targets" array is deleted when the mask is removed.
which couses problems if you want to add that mask back into the svg document.

for example if you remove a mask from the svg and then add it back at some later point, it will be missing its "targets" array.
and then if you try to use the mask by calling Element.maskWith(mask).
the code at [mask.js line 47](https://github.com/wout/svg.js/blob/master/src/mask.js#L47) throws an error.

**Comment by Fuzzyma** [comment]
Its interesting that you mention that. I myself thught about this a half year ago: https://github.com/wout/svg.js/issues/212#issuecomment-75445762

I did not realize that the reference is deleted when removing the mask. We should instead set it back to its initial state (which is an empty array). Do you agree?
