### ISSUE TITLE
SVG.get(id) throws uncaught exception when an object with ID doesn't exist

### ISSUE THREAD

**Issue by emwhy** [wout/svg.js#431]
`SVG.get(id)` throws uncaught exception when an object with ID doesn't exist.

In previous version (1.1.0), `SVG.get(id)` with non-existing object ID returned `undefined`, which I was able to use in my code.

I temporary made the following simple change to my copy of 2.2.4 to get around the issue.

```javascript
// **At line 4339: **
SVG.get = function(id) {
  var node = document.getElementById(idFromReference(id) || id)
  
  if (node === null)
    return null
  else
    return SVG.adopt(node)
}
```

I would like to see for future version:
- `SVG.get(id)` returns `null` for non-existing object as shown above
and/or
- Add `SVG.exists(id)` / `SVG.has(id)` method to check for existence of object

**Comment by Fuzzyma** [comment]
Why you want to use elements which are NOT on the site in the first place? In my opinion the responsibility for the presence of an element lays by the programmer and not by the lib.
Obviously you are trying to execute code which is not made for this particular site because elements doenst exists.

However I thought long about this problem and was about to fix it some month ago. I just saw it as an unneeded additional check which has to be performed very often.
I was not aware, that the `SVG.get` will need that, too. I will think about that again.

Quickfix:
```javascript
try{
    SVG.get('id')...
}catch(e){
    // element doesnt exist
}

**Comment by emwhy** [comment]
This is my thought as a developer who use svg.js very heavily in the project.

First of all, my answer to your question: It's because I am dynamically generating svg using data from the database in the back, and only attempt to write the element when it hasn't already been written yet.  This is why I needed some kind of way to find out if a certain object exists.  The expectation is not unlike *document.getElementById(id)* returning null if it doesn't exist. 

I have no idea how others are using svg.js.  But I am personally finding it necessary to check for existence of certain object.  Right now, there seems to be no other way built into svg.js.  

There is a "has(id)" method to go with "get(id)" method in referring to child objects, but not under SVG object.  I am ok with checking for existence before calling "get(id)", if such method existed.  If you don't want to check for that every time "get(id)" is called, having "has(id)" would be help that.

But the other problem for me was that it was an undocumented behavioral change.  Under 1.1.0, "get(id)" returned undefined.  In 2.2.4, it throws exception.  Which one is the preferred behavior going forward?  Either way you decide, I think the behavior should be well documented and stay consistent.  Inconsistent behavior in versions could potentially break code when upgrading, and I would like to minimize that potential.  The regression is extremely important for users of the library.  I don't want to wonder what else could be different and spend few hours trying to figure out what when wrong when upgrading. (Is this why the demo no longer works?)

I understand that performance of the library is very important.  I am a dev, too, and I try to make things efficient.  But there is a tough balance between making it as lean as possible and making it more developer friendly (i.e., friendly exception message, graceful failure, etc).

I think svg.js is an excellent piece of software.  I think developers of svg.js has done an awesome work.  I know that trying to meet demand of users is not easy.  I don't want to knock your work or offend you in any ways, but I just wanted to tell you my point of view as one user.

Best regards,
Em.

**Comment by Fuzzyma** [comment]
Thanks for your comprehensive answer. I am really thankful for that. I dont have such a deep insight about actually using the library. I maintain it but only use it rarely.
Getting a feeling for which issues the libbrary is used helps me a lot.
As I already said: I tended to implement the check and now I will do it.

**Comment by emwhy** [comment]
I really appreciate you working with me.  I don't want to start flaming or unreasonably demanding something.  I simply want to have a discussion in a civilized and logical manner, which hopefully would help svg.js become even better than it is now, with consistent syntax and stable features.

I am planning on continuing to use svg.js in my project or any other project that would come around that may require SVG implementation.  This kind of responsiveness by library dev will be highly appreciated, and amount of activity is definitely one of the reason I chosen svg.js.

If you need any users' prospective in future, I would be happy to help.

**Comment by Fuzzyma** [comment]
Thank you very much. I will get back to it :)
