### ISSUE TITLE
SVG.G. Methods x and y

### ISSUE THREAD

**Issue by makarti** [wout/svg.js#433]
svg.js line 2639:  dont correct work If parameter "x" as string.
```javascript
this.transform({ x:  -this.x() + x }, true) 
```

If you dont mind, you can rewrite this method as
```javascript
this.transform({ x: x -this.x() }, true) 
```

**Comment by Fuzzyma** [comment]
Yes that's indeed an optimization which I can do. Did you spot any other
methods with the same problem? I will look for it myself, too :)

Artur <notifications@github.com> schrieb am Fr., 25.12.2015, 10:09:

**Comment by makarti** [comment]
not yet :)
