### ISSUE TITLE
Drop shadow in svg.filter.js plugin stopped working after svg.js 2.2.1

### ISSUE THREAD

**Issue by steffdev** [wout/svg.js#435]
Maybe this was caused by new feature in svg.js 2.2.3 "added workaround for SvgPathSeg which is removed in Chrome 48 (#409)"? See https://github.com/wout/svg.filter.js/issues/8 for an example and more details. Am missing the drop shadow a lot. Thanks in advance for your help! Svg.js is amazing!

**Comment by Fuzzyma** [comment]
The referenced issue actually comes with a working example - so only the docs should be fixed.
You are saying, that the shadow is not working at all so maybe you are talking about a different issue?

However: The code which replaced the pathseg code does not effect filters in any way. Its all about paths

**Comment by steffdev** [comment]
Thanks so much for your quick response! The shadow works but only in the 'colored glass' fashion (in the color of the shape). Previously, the shadow had the typical semi-transparent black-blurred look. Maybe I am missing something? Any help figuring this out is very much appreciated.

**Comment by Fuzzyma** [comment]
and prior to 2.2.3 it looked right?

**Comment by steffdev** [comment]
Yes!

**Comment by Fuzzyma** [comment]
would you mind creating a fiddle with a comparison of both versions?
Also: is 2.2.3 just a guess or does the exact commit broke these things?

**Comment by steffdev** [comment]
I'll double-check pre-2.2.3 and post some screenshots to illustrate ASAP, hopefully by tonight PST

**Comment by Fuzzyma** [comment]
any news on this?

**Comment by steffdev** [comment]
Was completely sidetracked - sorry and thanks for following up! Here is a fiddle showing the 'colored glass' version: https://jsfiddle.net/steffdev/erv2jv2x/ - I don't get the prior version to work but please find a screenshot attached that shows how the drop shadow used to look. Any idea how to get it to look like before (semi-transparent black-blurred)
![svgfilterdropshadowexample](https://cloud.githubusercontent.com/assets/16563083/12435618/73e35abc-bec3-11e5-9c2e-bd7d646b3c88.png)
?

**Comment by Fuzzyma** [comment]
Here is the url for svg.js v2.2.2: https://rawgit.com/wout/svg.js/2.2.2/dist/svg.js
I am not a professional when it comes to filter. So I cant just snap and give you a solution for your problem. This issue is not about fixing the filter but about fixing the bug which leads to the wrong filter.
It would be nice to have 2 identical pictures only with one shadow with the current version and one with the old. Thats why I asked for 2 fiddles

**Comment by mkorganashvili** [comment]
it is a 'parent'-s problem, as it is not a member any more but function

**Comment by Fuzzyma** [comment]
could you please explain that in more detail?

**Comment by wout** [comment]
Is this still an issue?
