### ISSUE TITLE
Line disappears when moved outside of body's bound. 

### ISSUE THREAD

**Issue by raphaelduartepinheiro** [wout/svg.js#438]
Hello. Today while I was testing some movements with svg.js I've found something that I don't know if it's a bug or an expected behavior.

If I move a set of lines to somewhere outside of body's bound, and try to come back with it, one line disappear.

Example: 

https://jsfiddle.net/t13tdkr0/

Use scroll of the mouse to simulate: 1 scroll up, 2 scrolls down.

If I apply ``position: absolute`` to the line element, the problem doesn't occurs.

My question: is this behavior correct? I wanted to "hide" the elements and show, going out of screen, but the vector layout seems to break.

Appreciate any reply.

**Comment by Fuzzyma** [comment]
I cant reproduce your issue. The jsfiddle just does nothing :D

**Comment by raphaelduartepinheiro** [comment]
Sorry if I wasn't clear... Did you tried to scroll with the mouse wheel? 

Using Chrome here.

**Comment by Fuzzyma** [comment]
Maybe the error shown is the problem:
```
<line id="SvgjsLine1007" x1="3.5225866668042727e-1000.00074022007352669840.074015945492518660.57995862887638291.43078614585458052.74594071839242164.4810105268363896.4931922665276779.0282073374043111.96522289547170115.08921226539659719.01063177886423722.84830958758977527.00718360153441831.7661582017862536.862292889936741.9536462671662247.661958633942853.6621020238646159.5605687469985466.077661285027272.834069933126379.3944101755523486.5598104375567893.9061191396822100.9667955521109108.60406760304036116.35938585794509123.74654115406085131.66763000936885139.64099614319136147.17273404304103155.1825962065231162.70819832166328170.66854360304797178.56994968503074185.9325444066405193.65542502459303201.25381618407476208.27211199505717215.56736499799214222.67564362701194229.17682679211222235.86481883954087242.307955527228248.13194534073142254.04799587227296259.6673392098319264.670729713816269.6691659311379274.3263490360665278.38594015102217282.34368396559523285.9240315335457288.93986265321223291.759461277323294.17481326868005296.0726246219216297.68465017973307298.8755326123758299.6085937852008299.9733528574736300.0000000003522600.00074021972126803170.189456509097379880.7573474528049741.77376213345791793.212864351179194.9497768356347347.1966059581485059.85065863150819612.7138241068623716.13574328144231619.93939482532649523.85831265527462728.37106287514398833.2306547649464838.1088281863726843.601290564158949.39716351949255.1144757130313261.4514075965558168.0408479898596374.4565197546358681.4818848498550688.7026387895476295.65869499431814103.19950549673776110.87377405651544118.19893351169179126.06950964022705134.008326858711141.52221982769632149.52876187711806157.5366477269654165.05425722768226172.99961756054412180.87939131548214188.2156088525073195.9041463282751203.4617818069876210.4359653570494217.67836266627677224.7277658009236231.16818781903137237.78611310382647244.15370419360508249.90178011513774255.73227809135423261.2612659108109266.17545902981004271.0749634869601275.6292060063212279.58851257892525283.43638145675067286.9037381105254289.81066686873163292.51215286511575294.80724582499107296.7871356488208298.07880209922286299.09414331827696299.76023251634626299.999259780278753000-0.0007402197212680317-0.23976748365374667-0.8548814404501615-1.9211979007771274-3.310599025391725-5.192754175008918-7.4878471348842455-10.019305104915222-13.096261889474587-16.563618543249298-20.17480046204715-24.370793993678753-28.925036513039952-33.527023096938215-38.73873408918912-44.2677219086458-49.74719697483104-55.84629580639491-62.21388689617346-68.43592758318113-75.27223419907638-82.32163733372323-89.13303635007-96.53821819301238-104.09585367172488-111.32889176789101-119.12060868451779-127.0003824394559-134.4769582124366-142.46335227303456-150.47123812288194-158.00725346381407-165.991673141289-173.930490359773-181.34038356036172-189.1262259434845-196.8004945032622-203.9018094008836-211.29736121045235-218.51811515014495-225.1359938041065-231.95915201014037-238.54859240344413-244.52008067780534-250.602836480508-256.7303515813928-261.57676947105375-266.7693452350535-271.628937124856-275.88606789785723-280.0606051746735-283.86425671855767-287.0956335411092-290.14934136849183-292.8033940418515-294.9294496922572-296.7871356488208-298.2262378665421-299.1946217987148-299.81054349090266-3000-0.006661933657525765-0.10657910391161929-0.622094819222152-1.4964513425163695-2.8364223834998867-4.712525830705339-6.911002414890966-9.353025105414654-12.336806147402829-15.713152751278248-19.472436799571145-23.35081117469774-27.821890939423593-32.3484762099885-37.48333955543108-42.939059658536806-48.35303437948465-54.38640153769656-60.69242404374674-66.86047818949588-73.64378763744432-80.64483734385122-87.41509295073519-94.78131709729828-102.30500492513838-109.51075583092553-117.27851379051859-125.13958157578203-132.60339827865582-140.58142207060297-148.5863042350284-156.1244027967765-164.11624699777715-172.0678367757956-179.49460419231298-187.3034830747282-195.00598593619142-202.13855054565553-209.57218359521707-216.83593835653443-223.9091012322437-231.16818781903137-237.4035719502864-243.41816707321686-249.5497712148688-255.39749546982736-260.62696760372603-265.87679455167967-270.7961828566683-275.1117650419757-279.35054663359557-283.00323835508345-286.51589560274937-289.63925896754034-292.21528555260477-294.5585517435014-296.59021853522904-298.0028916311802-299.09414331827696-299.76023251634626-299.99703912842057-300" y1="7658798196" x2="320.10540515481557" y2="7658798196" stroke="#d5d5d5" stroke-width="2"></line>
```

There is something deeply wrong. Well - could you please checkout the 3.0.0 branch and check if the error remains there? If its fine there, then I would stall this issue until the new animation system is released

**Comment by raphaelduartepinheiro** [comment]
Tested again with 3.0.0 branch [new JSFiddle](https://jsfiddle.net/t13tdkr0/1/)

The same situation occurred. 

My guess is that something is not handling well numbers for position system. For some reason ``x `` was seeded with a giant number. It seems the element is trying to behave like a block element, since ``y`` is "7658798196". Strangely, positioning the line element as absolute the problem do not happen (at least in my tests outside JSFiddle).

**Comment by snowyplover** [comment]
I have updated the [jsfiddle](https://jsfiddle.net/t13tdkr0/2/) to use the non-minified version of the 3.0.0 branch.

The error occurs only when the lines are scrolled back to their starting point. That is, if I scroll the lines off the screen to one side, I can scroll back and forth without problem. The problem starts with the next scroll after the lines return to their starting point.

When the lines are scrolled back to the starting point, they no longer have exactly the original coordinates. The coordinates are slightly off due to floating point arithmetic.

The problem is only caused when a coordinate has a starting value of 0. (In the jsfiddle, change x1 on the first line from 0 to 1 and the problem disappears.

When the lines are scrolled and returned to their initial position, an attribute with a starting value of 0 ends up with a value in exponential notation (e.g. 4.768378403241513e-8).

Somewhere in the code, this exponential value is being treated as a string when it shouldn't be. So Javascript's type conversion is treating a + somewhere as string concatenation rather than addition. All the values for animating the attribute are being stuck together into a string, which is where the mess Fuzzyma quoted above comes from.

I haven't figured where the bug is, but that seems to be what it's doing.

**Comment by snowyplover** [comment]
I found a bug which may be related to this issue (see issue #443), as it is also related to floating point exponents and strings. However, that bug seems more likely simply to set some numbers randomly to 0 than to cause string concatenation.

**Comment by snowyplover** [comment]
The fault appears to be in `SVG.regex.isNumber`, which does not check for exponents.

**Comment by snowyplover** [comment]
The fix seems to work. [Here's an updated jsfiddle that tests it.](https://jsfiddle.net/t13tdkr0/3/)

**Comment by Fuzzyma** [comment]
wow - snow - you are a genius! Thank you for hunting down this error!!

**Comment by raphaelduartepinheiro** [comment]
Very clever, @snowyplover! It's solved, now it's just a matter of time to see it in the next release! Thank you both!
