### ISSUE TITLE
svg rectangle with select resize and draggy

### ISSUE THREAD

**Issue by sacer6** [wout/svg.js#439]
Hi, I'm trying to do a rectangle can resize and drag, but doesn't work for me
I was add a svg.js library and svg.select, svg.resize and svg.draggy
Are incompatible or something?

Thanks for all

**Comment by Fuzzyma** [comment]
Try the official plugin svg.draggable.js

sacer6 <notifications@github.com> schrieb am Fr., 15.01.2016, 11:32:

**Comment by sacer6** [comment]
Hey there, thanks for your help
I tried what you said and still does not work
My code is

part of head:

  <script src="Scripts/svg.js"></script>
    <script src="Scripts/svg.select.js"></script>
    <script src="Scripts/svg.resize.js"></script>
    <script src="Scripts/svg.draggable.js"></script>
    <link href="Content/svg.select.css" rel="stylesheet" />

and code js
 svg = new SVG(document.querySelector("#SvgDiv")).size("100%", "100%");
   svg.rect(100, 100).resize().selectize({ deepSelect: true }).draggable();

**Comment by sacer6** [comment]
Hey there, thanks for your help
I tried what you said and still does not work
My code is

svg = new SVG(document.querySelector("#SvgDiv")).size("100%", "100%");
svg.rect(100, 100).resize().selectize({ deepSelect: true }).draggable();

**Comment by sacer6** [comment]
Thanks for all, it works now

**Comment by Fuzzyma** [comment]
I am curious was the mistake was :)

sacer6 <notifications@github.com> schrieb am Fr., 15.01.2016, 12:24:

**Comment by xlxxxxlx** [comment]
sacer6, i have same problem, please give a solution ! )

**Comment by aiduryagin** [comment]
Hi, still doesn't work

Code: 
`
rectangle = activeRoomSVG.rect().draggable().selectize().attr({ fill: '#80a47d' }).draggable().draw();
`

**Comment by Fuzzyma** [comment]
Any reason why you make it draggabke selected and resizeable when it's not even drawn? Call all this methods when the corresponding draw event is fired

**Comment by aiduryagin** [comment]
I created pull request with description of a problem https://github.com/Fuzzyma/svg.select.js/pull/25

**Comment by Fuzzyma** [comment]
actually you did not describe your problem. I have still no idea what your problem is and what you claim to have been solved there. So please be a bit more specific about your bug!

**Comment by aiduryagin** [comment]
Outdated code is not a reason of a bug) Updated demo: http://codepen.io/aiduryagin/pen/KrYbXK 

The problem is that if a css file has a css rule
`* {
  pointer-events: auto!important;
}`
this rectangle
![rect](https://cloud.githubusercontent.com/assets/6934028/17837191/d4c9202e-67b4-11e6-8360-d1d3548d0f8e.png)
prevents dragging of first "<rect id="SvgjsRect1009" ... ></rect>" element

**Comment by Fuzzyma** [comment]
I dont see this. I can drag it and draw it and resize it without any problem

**Comment by aiduryagin** [comment]
Hm... In my demo i can't drag it. Browsers: Chrome 52, Chrome 54 canary, Firefox 48

**Comment by Fuzzyma** [comment]
But you draw it first, right? Because dragging without drawing makes no sense

**Comment by aiduryagin** [comment]
Whatever. Even if element has already been drawn. Example: http://codepen.io/aiduryagin/pen/KrYbXK

**Comment by Fuzzyma** [comment]
Oh cmon - you enable pointerevents on purpose for all elements with
```
* {
  pointer-events: auto!important;
}
```

and then you wonder, why the rect gets in the way when dragging.
Thats not the plugins fault. You have to take care of your css yourself.
However: changing the css at the right place would solve this issue, too:

```
.svg_select_boundingRect{
    stroke-width:1;
    fill:gray;
    stroke-dasharray:10 10;
    stroke:black;
    stroke-opacity:0.8;
    fill-opacity:0.1;
    pointer-events:none !important; /* important added */
}
```

This issue would have been solved quite fast when you just would have simplified your code down to the actual problem!!

**Comment by aiduryagin** [comment]
I solved the problem yesterday. I tried to explain you that the problem exists and where she is. My solution: https://github.com/Fuzzyma/svg.select.js/pull/25/commits/521a626d8b04ded936b983c2087d5e150f32122d

**Comment by Fuzzyma** [comment]
Yeah I saw your PR. However I aim for as little dom pollution as possible. Also lines instead of rects make this whole thing a bit overcomplicated. Imo just set the pointer-events to `important` as stated above.
