### ISSUE TITLE
SVG.Number exponent bug

### ISSUE THREAD

**Issue by snowyplover** [wout/svg.js#443]
The `SVG.Number` constructor does not correctly process floating point numbers with exponents that are passed as strings.

* Exponential float passed as number<br>
`x = new SVG.Number(4.5678765e-8)`<br>
_`SVG.N…r.SVG.i…t.create {value: 4.5678765e-8, unit: ""}`_ __<-- works fine__
* Non-exponential float passed as string<br>
`x = new SVG.Number('4.5678765')`<br>
_`SVG.N…r.SVG.i…t.create {value: 4.5678765, unit: ""}`_ __<-- works fine__
* Exponential float passed as string<br>
`x = new SVG.Number('4.5678765e2')`<br>
_`SVG.N…r.SVG.i…t.create {value: 0, unit: ""}`_ __<-- error: returns default value__

(This problem may be the cause of issue #438, though it's not clear.)

**Comment by Fuzzyma** [comment]
closed with #444

**Comment by snowyplover** [comment]
@Fuzzyma 

While I noticed this problem when I was looking for the bug #438, and while it is related in a sense, it is not caused by `String.regex.isNumber` and so the fix in #444 has no effect on it.

The reason it is related is that `SVG.regex.unit` has the same problem as `isNumber` did: it only matches a subset of floats.

However, it also seems badly named as it does not actually require a unit on its argument in order to match, which makes the constructor for `SVG.Number` confusing: when I read it, it looked like there was no branch that dealt with string values that did not include a unit.

As it turns out, `regex.unit` has the same problems as `regex.isNumber` did. It doesn't match exponents plus a few other legal number formats (such as a prefixed +), and it does match a lot of illegal strings (e.g. things like '4...5...6'). Also, given the needs of the context where it is used, I think it should be renamed `regex.attribute`. And it should only match valid units rather than any short character sequence

Indeed, `SVG.Number` might be better named `SVG.Attribute`, as its purpose is wrapping an attribute value, which is a number with an optional unit, not simply a number.

I can fix the regex easily. Anything more involved, we should probably discuss.

In any case, this issue should be reopened until it is actually resolved. Or, if github doesn't have a mechanism to reopen issues, I can just create a new one.

**Comment by snowyplover** [comment]
Here's the regex I came up with:

`/^([+-]?(\d+(\.\d*)?|\.\d+)([eE][+-]?\d+)?)(%|em|ex|px|pt|pc|cm|mm|in|s|ms|deg|rad|grad)?$/`

However, fixing this problem is not just a matter of changing the regex. There are a lot of parentheses in this one so any code retrieving the unit needs to be changed.

For example, if `ex` is the expression above then:
```javascript
> ex.exec('+3.45654e-9em')
[ '+3.45654e-9em',
  '+3.45654e-9',
  '3.45654',
  '.45654',
  'e-9',
  'em',
  index: 0,
  input: '+3.45654e-9em' ]
```

The numeric part has index 1 like before, but the unit has index 5 (rather than 2).

There is also the question of what value should be in returned in the unit slot, when there is no unit. The expression above will return undefined:
```javascript
> ex.exec('+3.45654e-9')
[ '+3.45654e-9em',
  '+3.45654e-9',
  '3.45654',
  '.45654',
  'e-9',
  undefined,
  index: 0,
  input: '+3.45654e-9em' ]
```
 But if the end of the regex is changed to:
```
|grad|)$/
```
then the empty string will appear instead of undefined. The old regex seems to return the empty string, so I should probably go with that.

Yet another reason there should be a test suite for the regexes... :)

**Comment by Fuzzyma** [comment]
I looked into the testsuite yesterday and it indeed has regex tests - but just not for every case and not for every regex.
The SVG.Number object is not for all attibute (-values) which can be set on a node. e.g. think about `fill="#000"`. It is only made for  _numbers_ (with additional units). I agree that the reges is missleading. To make that clear it should be named `isNumberWithAdditionalUnit`.
As far as I can see the unit makes no difference unless you specify `%` or `s`.
Your regex would do the job - however I am not sure if the unit thing is needed. They are ignored anyway. But better save than sorry - so its okay on my side.
However I vote against the `SVG.Attribute` thing because I think it matches even less than `SVG.Number` :P

**Comment by snowyplover** [comment]
I think the abstraction here is well described as a numeric quantity with a unit, where the unit may be implicit. (And fortunately, the display code, not this library, usually gets to worry about which implicit unit goes with which attribute.)

You are, of course, right that the term 'attribute' was an over-generalization on my part, and not my best idea :) A more appropriate term is probably 'quantity'.

I think my problem with `SVG.Number` is contextual. If there were a class hierarchy, where `Number`, `Color`, etc subclassed `Attribute`, then `Number` might work, as the contrast with other types would be clear. But that's not the structure being used here, and `SVG.Number` seems like it should just be wrapping a number.

Aesthetic kvetching aside, though, `SVG.Number` may be a case where changing it is not worth the bother. However, my experience of `regex.unit` is that it actually does hinder code readability and is worth changing.

**Comment by Fuzzyma** [comment]
Albeit I can follow your thoughts, i would myself find confused when I read about a regex named quantity. Its a term I dont here often in programming related stuff. However I agree, that `unit` is the wrong name for a regex which matches a number with an additional unit.
Maybe its related to my bad english but quantity sounds wrong to me in this case.
What about `unitNumber` or `numericValue`? I am not that creative when it comes to naming :D.

**Comment by snowyplover** [comment]
I suppose it's true that the meaning of 'quantity' I have in mind is not the one most commonly used. The sense I'm after is "something that has been quantified" -- in the sense of being measured. A measurement, of course, must be made with respect to a chosen unit, which is why I thought it a fairly precise fit. But while this is an important usage in scientific contexts, perhaps it is too technical to work well here.

'measure' is far too ambiguous to be a good choice, 'magnitude' could work, though may also be technical.

A choice that seems more like a programming usage than a technical borrowing might be to simply call it 'numeric'. It's not usually a noun, but works well enough in the current sort of context.

Unfortunately, the svg spec is not much of a guide here as it does not define a collective term that groups lengths, angles, and times.

**Comment by Fuzzyma** [comment]
Maybe we should not forget that this is only about naming a regex variable :D.
Iam completely fine with longer desciptive names like `numberWithAdditionalUnit` or `checkNumberAndUnit` or whatever. However I am fine with `numericValue`, too while only `numeric` has (for me) the same meaning as Number

**Comment by snowyplover** [comment]
I was wondering whether that last comment was a bit of language nerd excess. Sadly, I wondered this after I posted it... :D 

If you like `numericValue`, let's just go with that.

**Comment by Fuzzyma** [comment]
So be it - but my tests fail :D.
However: I already wrote something about the unit part in the regex. I would like to generalize it a bit since the user maybe has its own units (who knows...)
It would look like this: `/^([+-]?(\d+(\.\d*)?|\.\d+)([eE][+-]?\d+)?)([a-z%]*)$/`
Dunno if this one will pass the tests ^^

**Comment by snowyplover** [comment]
@Fuzzyma

I'm wondering if it is possible for users to have their own units. The only scenario I've come up with would be someone writing an extended implementation of svg. Are you sure that making the regex more permissive is best?

My sense is that user-defined units would be so rare, that freely allowing them would not make up for the loss of error messages for faulty value strings. If I had a display error due to a typo in a unit, I would prefer the library help me find it, than have to hunt for it. If there is an actual need for user-defined units and I'm just not seeing it, then it would be easy enough to provide a function to register unit strings that would add them to the regex.

**Comment by Fuzzyma** [comment]
Yes ofc I agree with that.
The thing is, that the lib would not help. It would just not work. The regex would just fail and the Number would default to `0`.
Thats maybe just only my opinion but I think with the non strict regex the lib is more tolerant to errors.
Either way the lib wont throw an error.

In the first place the regex is for dividing the number from the unit and not check for the correctness of those. That are my thoughts to this :)

**Comment by snowyplover** [comment]
What's wrong with:

```javascript
  match = value.match(SVG.regex.numberAndUnit)

  if (match) {
    etc...
  } else {
    throw new RangeError('Invalid attribute value: ' + value)
  }
```

Hm, there isn't a single `throw` statement in the whole library currently.

It's certainly possible to use the regex as just a parser. However, my instinct is that, since we're running the regex anyway, we might as well use whatever information it produces. If the `SVG.Number` constructor threw an error on invalid input, the bug in #438 would have been a lot easier to find.

**Comment by Fuzzyma** [comment]
Of course you right saying that throwing an error would be provide more information. But when I start checking for input values here I certainly have to do it everywhere else, too.
I more or less followed the code style which doesn't use throws at all till now. 
I myself don't like it and try to avoid it
