### ISSUE TITLE
could Element.attr() support camel case properties?

### ISSUE THREAD

**Issue by CicholGricenchos** [wout/svg.js#446]
I don't want to write strings as object keys...
Codes would seems cleaner without quotes.

Thanks!

**Comment by Fuzzyma** [comment]
If you can prove me that this will have no major impact on performance
since this is the most important function in svg.js, than I will think
about it.
Feel free to use the "attr(key, value)" syntax meanwhile.

谜之哈希 <notifications@github.com> schrieb am Mi., 20.01.2016, 18:04:

**Comment by CicholGricenchos** [comment]
@Fuzzyma 
Well I tried to replace the property name and then bunch of tests failed...
Then I realize that there are some properties who born with camel case name.

So a list of names would be needed to distinguish them.
https://jsfiddle.net/hu3orrm4/ here is a performance test, though I don't have a certain list.

If I use an object to store the list, there would be about 100ms slower for 100000 times attr({}), but if use switch, there is no significant difference.

**Comment by CicholGricenchos** [comment]
The test result fluctuates.. I may need a more precise test.
https://jsfiddle.net/hu3orrm4/1/
repeating by 500000 times attr({})
```
attr
4015ms
modified attr
4096ms
attr
4021ms
modified attr
4094ms
```

**Comment by CicholGricenchos** [comment]
@Fuzzyma 
I did a patch myself, fitting my own case.
It's not good to hard code all these attributes into the lib, so closing this.

**Comment by Fuzzyma** [comment]
Well that escalated quickly... What are these "born" camel case properties?
I can't imagine one.

谜之哈希 <notifications@github.com> schrieb am Do., 21.01.2016, 3:07:

**Comment by CicholGricenchos** [comment]
@Fuzzyma like `markerWidth`...

**Comment by CicholGricenchos** [comment]
https://github.com/adobe-webplatform/Snap.svg/blob/master/src/svg.js#L1632-L1712

The Snap implementation of `attr`, with a style attributes list.

**Comment by Fuzzyma** [comment]
Wouldn't it be easier to have a list of properties which are already camel cased instead of the other way round? However this is a problem... 
I didn't know that Html/svg is case sensitive...
