### ISSUE TITLE
Simultaneously animate multiple points with .plot

### ISSUE THREAD

**Issue by paulous** [wout/svg.js#449]
just wondering if I am missing something, or maybe it's not currently possible. But is there a way that I can:

```javascript
var points [  [ [x,y], [x,y], [x,y] ],  [ [x,y], [x,y], [x,y] ],  [ [x,y], [x,y], [x,y] ]... ];

var polygon [ poly1, poly2, poly3...];

polygon.forEach(function (v, i) {

v.animate(3000).plot( points[ i ] ); // Simultaneously animate?

});
```

Great work! and thanks!

**Comment by Fuzzyma** [comment]
Well I would think it would work exactly that way :D.
This will be animated nearly (if not almost) simultaneously.
The only other way would be animating one polygon and updating all other with the `during` method.

```javascript
poly2.array().morph(points[1])
poly3.array().morph(points[2])

poly1.animate(3000).plot(points...).during(function(pos){
  poly2.plot(poly2.array().at(pos))
})
```

Well - Iam not completely sure about that. Maybe you have to clone the point array before you can use them correctly...

**Comment by paulous** [comment]
Thanks for the fast reply!
It changes the polygon shape, but no animation. I am not adding any additional points just re arranging the x, y numbers in a triangle. I tried the morph anyway but didn't make a difference. By cloning the array do you mean:  array2 = array1.slice(0);

I also tried just animating one item in the array with the same out come. I can past some code if you care.
cheers!

**Comment by Fuzzyma** [comment]
The code you posted first should work since `3.2.0`
