### ISSUE TITLE
Clone positioning and group cloning

### ISSUE THREAD

**Issue by insominx** [wout/svg.js#45]
Currently, element has a clone method which works well although it appears to do something  I didn't expect with the offset.  The very last line of the clone method has this:

    /* apply attributes and translations */
    return clone.transform({})

which results in the negative offset being applied.  My original element had this

    transform="translate(0,0)"

but the clone has

    transform="translate(-711.3419799804688,-20.5)"

Is this intended?

Also, could we add a method for cloning an entire group (element and all its children)?
FYI, I'm working on a game that uses an svg map.  You can see a test here: http://www.realitymeltdown.com/Svg/test-svgjs.html

**Comment by Fuzzyma** [comment]
@insominx - did this issue still exists with the new version?
