### ISSUE TITLE
How to get a tspan inside a textpath ?

### ISSUE THREAD

**Issue by plopinou** [wout/svg.js#450]
Hello there.

Thank you a lot for this wonderfull library that saved me so much time already.

On a website I'm managing I recently upgraded svg.js from version 1.x to the latest 2.x one.
I ran into a few issues but that was ok, except for one :
I didn't find a way to get the reference to an SVG.Tspan element when it is inside a TextPath element.

```javascript
var text = draw.text(function(add) {
  add.tspan('We go ')
  add.tspan('up').fill('#f09').dy(-40)
  add.tspan(', then we go down, then up again').dy(40)
})
text
  .path('M 100 200 C 200 100 300 0 400 100 C 500 200 600 300 700 200 C 800 100 900 100 900 100')
  .font({ size: 42.5, family: 'Verdana' })

console.log(text.lines()) // -> return set with textpath but no tspan, because lines() only get first level tspans
```

What am I missing ?

For the time being I'm using this :
```javascript
SVG.utils.getSVGTspanElements = function(p, includeTextPath) {
  var tspans = [];
  [].forEach.call(p, function(el){
    if (el instanceof SVGTSpanElement)
      tspans.push(el);
    else if (includeTextPath && el instanceof SVGTextPathElement)
      tspans.push.apply(tspans, SVG.utils.getSVGTspanElements(el.childNodes));
  });
  return tspans;
};

SVG.extend(SVG.Text, {
  getTspans: function(includeTextPath){
    var lines = SVG.utils.map(SVG.utils.getSVGTspanElements(this.node.childNodes, includeTextPath), function(el){
      return SVG.adopt(el);
    });

    return new SVG.Set(lines);
  }
});

console.log(text.getTspans(true)) // -> return all tspans including those inside textpath elements
```

**Comment by Fuzzyma** [comment]
Its not returning an empty set but a set with the textpath in it.
This is still not really what one would expect.
I think thats something the lines method whould be aware of.
Thanks!

**Comment by plopinou** [comment]
Yes, it return a set with textpath in it, my bad :) I was ready to sleep when I posted this issue.
I changed the comment accordingly.

**Comment by Fuzzyma** [comment]
I looked deeper into this issue and I found, that lines would be a bad method name when it returns tspans in a textpath (which are not really lines there).

Instead in my opinion the textPath instance should have the possibility to return its children:
```javascript
var text = draw.text('some text around a circle').path('M233.292,233.291c-44.182,0-80-35.817-80-80s35.818-80,80-80c44.182,0,80,35.817,80,80S277.473,233.291,233.292,233.291z')

text.textPath().children() // should return a set of all children
```

Unfortunately this is not implemented yet. I will add that but I want to hear your opinion first.
Does this makes sense to you?

**Comment by plopinou** [comment]
It makes sense, but in the specific case I ran into when I opened this issue, I had a set of text lines that could be both "normal" tspans and tspans inside a textpath (this is a stamp customizer tool I created for a customer).
So with the getTspans function I could get all the tspans, whether they were in textpath or not, in one call and apply some specific styles to them.
