### ISSUE TITLE
Link to svg.js on test page (& other demos) broken.

### ISSUE THREAD

**Issue by isnav** [wout/svg.js#453]
Seems the file hosted on https://s3-eu-west-1.amazonaws.com/svgjs/svg.js is returning a 403.

![screen shot 2016-02-02 at 3 22 45 pm](https://cloud.githubusercontent.com/assets/486514/12742453/da6d486c-c9c0-11e5-9e3d-dd1a1cc96063.png)

**Comment by joemaller** [comment]
This makes evaluating the library kind of challenging. @isnav thanks for pointing that out, understanding it's a network error is better than assuming it's all broken.

**Comment by wout** [comment]
The library has seen a lot of changes and the examples have not been updated accordingly.
For the time being we removed the examples from the site.
