### ISSUE TITLE
Problem at rotating an element

### ISSUE THREAD

**Issue by sacer6** [wout/svg.js#454]
Hi!

I have the following libraries included: svg.js, svg.select.js, svg.draggable.js and svg.resize.js.

When I rotate an element, the maxX and maxY draggable limits exchanged. 

I don't know how I could solve it.

Thank you

**Comment by Fuzzyma** [comment]
Show your code and create a jsfiddle please!

**Comment by Fuzzyma** [comment]
@sacer6 is this still relevant or can it be closed?
