### ISSUE TITLE
How to get SVG.toDataURL()

### ISSUE THREAD

**Issue by sayasajer** [wout/svg.js#455]
Hi,

I want to know how to get data url from svg.js.

Thanks.

**Comment by Fuzzyma** [comment]
What exactly are you talking about? Example? Code?

sayasajer <notifications@github.com> schrieb am Fr., 05.02.2016, 6:20:

**Comment by villanus** [comment]
Are you talking about exporting the whole svg?

**Comment by ibrierley** [comment]
I'm assuming they are meaning base64 encoding the svg so it can be used as a data url string, something like this...

https://github.com/sampumon/SVG.toDataURL

**Comment by sayasajer** [comment]
Yes, Thank you for understanding because I do not know how to explain more.

The reason why I want to export the whole svg is because I want to use it in Pixijs Sprite.

**Comment by Fuzzyma** [comment]
You can use `window.atob()` to convert an XML string to base64 encoded data. At least that works in Firefox. For other non supporting browsers you can fallback to a base64 poly fill. you can get the xml string with the `svg()` method which returns the whole svg as String. 
Make sure you add the type to the base64 encoded string which should be `data:image/svg+xml;base64,`

**Comment by villanus** [comment]
Quick questions?
How does this differ than the export plugin?
Getting the full SVG work with nested SVGs?

**Comment by Fuzzyma** [comment]
The export plugin is obsolete. Its implemented in the core since svg.js v2. Same goes for the import plugin.

**Comment by sayasajer** [comment]
@Fuzzyma 
> The export plugin is obsolete. Its implemented in the core since svg.js v2. Same goes for the import plugin.

I am not quite follow you. If it implemented since v2, then how I can use it? Is there any example?

**Comment by Fuzzyma** [comment]
I already wrote that in this thread and it's written in the docs. A call do
`root.svg()` will return the whole svg as a string.

sayasajer <notifications@github.com> schrieb am Do., 11.02.2016, 8:23:

**Comment by sayasajer** [comment]
Thanks for reply.

I managed to use svg.js in pixi js now. Here is the codes in [jsbin](https://jsbin.com/temahatara/1/edit?js,output)

**Comment by sayasajer** [comment]
Can i get the SVG string without adding it to the DIV or append to the document body?

**Comment by Fuzzyma** [comment]
In order to export the svg you ofc must have it in the dom. That's after all a dom library because it works in a browser. If you don't need the dom you don't need a browser either and you just can generate the svg on server-side...
