### ISSUE TITLE
Rotate/translate/scale

### ISSUE THREAD

**Issue by smsti** [wout/svg.js#459]
Hello, I realized my app is bombing in SVG.js with recent Chrome. Eventually I understood that updating SVG.js helps, since it supports new SVG interface, while the old SVG interface is unsupported by the recent browser.

So upgrading SVG.js somehow helped but not completely, since a mess is produced by recent SVG.js. The reason is that **rotate(), translate(), scale() does not do the same as it did before**. It does almost the same only when I rewrite my app to call 1. rotate(), 2. scale() and 3. translate() in exactly that order on objects. Otherwise the objects are spilled around the screen.

**Comment by Fuzzyma** [comment]
From which version did you update?

smsti <notifications@github.com> schrieb am Mi., 10.02.2016, 0:33:

**Comment by smsti** [comment]
From svg.js 1.0.1-3-g6b0c1d2

**Comment by Fuzzyma** [comment]
svg.js v2 added parameters to specify the origin in scale and rotate. You have to make sure that the origin is set correctly to achieve what you want. 
Please note that this is a normal problem when working with transformations. Rotating an object around the 0,0 point when it is not centered at this point will rotate the object around the 0,0 which is then visibible as rotation and translation

**Comment by smsti** [comment]
I used three parameters with rotation indeed. For scale I do not see such parameter. The former SVG.js version caused a translate() attribute within SVG element to appear. The recent SVG.js version voids that SVG parameter and converts it into matrix() parameter now and the results are unfortunately different.

**Comment by Fuzzyma** [comment]
Its not pointed out in the doc at the right spot - sorry for that.
There are 2 more parameters for scale like in the matrix method: https://github.com/wout/svg.js#scale-1

**Comment by smsti** [comment]
Well I do not know how to use the new one. I did fix some simple cases (although I didn't know what I am doing, just some magic) but my more complicated sequences of transforms causes objects to fly around.

Let's ignore scale for a moment and let's talk about translate() and rotate() only. The old version, when I call these two methods on object, it is clear where the objects is to be found then. In the new version the same sequence causes object to jump somewhere.. Just a plain sequence of translate(x, y) and rotate(90, x, y) does unexpected results on an object. _But not always._ Then for example rotate back to (0, x, y) does _sometimes_ set coordinates to (-x, y) although object is still expected to be at (x, y).

It looks to me it's broken and if you play with that only for a little it should be not difficult to confirm that. It would be great to have that fixed. I may try to make a fiddle if you can't simulate it, but I'd rather avoid it as what can be tested in a few seconds from console would take me an excessive time on jsfiddle. Thanks

**Comment by Fuzzyma** [comment]
Did you make sure, that the x, y in your rotate method are the center of your shape?
Albeit rotation has issues sometimes iam pretty sure, that this is not the case here.
Also note, that transformations in svg.js v2 are absolute when not stated as relative. So Consecutive calls to rotate wouldnt change the output.

I would prefer to have a fiddle over dont having it

**Comment by smsti** [comment]
<!DOCTYPE html>
<html>
  <head>
      <script src="jquery-ui/js/jquery-1.11.2.min.js"></script>
      <script src="jquery-ui/js/jquery-ui.min.js"></script>
      <script src="libs/svg.js"></script>
  </head>
  <body>
    <div id="canvas" style="overflow:hidden;"> 
    </div>

    <script type="text/javascript">
var draw = SVG('canvas').size(400,400);
var text = draw.plain("test text");
text.translate(100,100);
text.rotate(90, 100,100);
    </script>
  </body>

The above code produces different results for old/new SVG.js. In new SVG.js, it does provide expected results when rotate() is before translate().

**Comment by smsti** [comment]
I think I am getting some understanding what's up with transformations. The old version of SVG.js was probably buggy and always placed transformations in order 1) rotate, 2) scale, 3) translate. Not aware of that bug I built an app which works as intended but doesn't work well with the proper (current) implementation of transformations.

Could you write some rotate2(), scale2(), translate2() for the backward compatibility? Or could you paste such methods here, so I can use user SVG.js to bring app--built on the old framework--back to the life?

**Comment by Fuzzyma** [comment]
For the records - here is the fiddle I expected from you: 
- old: https://jsfiddle.net/o2usrwge/
- new: https://jsfiddle.net/juy1aez6/

Updating to a new major version mostly produce breaking changes. Thats why its a major version.
That means that you have to adapt your code when updating to the new version and not the library to your code. Also it would not be backwards compatibility to add old methods with a new name.

So iam sorry that the anwer is no.

I guess you updated to svg.js v2 because of the chrome update which removed PathSegList?
If so just include the polyfill which adds the feature again and continue using v1: https://github.com/progers/pathseg

**Comment by smsti** [comment]
The pathseg link was very helpful. Thanks, I have made you a special credit on my site.
