### ISSUE TITLE
Uncaught TypeError: Cannot read property 'numberOfItems' of undefined

### ISSUE THREAD

**Issue by DanielTate** [wout/svg.js#460]
Uncaught TypeError: Cannot read property 'numberOfItems' of undefined

      for (i = 0, il = segs.numberOfItems; i < il; ++i)

line 629

Not sure why this is happening... it just randomly started happening in latest chrome.

**Comment by Fuzzyma** [comment]
http://bfy.tw/4GBT

**Comment by DanielTate** [comment]
@Fuzzyma  The fact that it works in Firefox and doesn't in Chrome makes me thing that it's related to the library. Also this has just popped up. I haven't worked on the project this showed up in in months.

Thanks for the help though you really contributed a lot here.

**Comment by Fuzzyma** [comment]
Thanks - just try to search for the error message first next time ;)

**Comment by DanielTate** [comment]
Note: This was because I was using an old version installed via bower. Make sure you are using the latest version :+1: 

Thanks again @Fuzzyma

**Comment by mspanish** [comment]
It would be better if this thread could tell why this error is now cropping up - I've been using a customized version of svg.js for over 2 years (I've continually updated parts of my svg.js, just not the whole thing), and this error only began happening in the last few weeks - and I don't have the option to just update my svg.js without breaking other functionality. If I find the actual cause I'll post it here.

**Comment by Fuzzyma** [comment]
It would be better if you maybe would google that error and find another issue where that is described properly with a commit which fixed that.

**Comment by mspanish** [comment]
For anybody like me who can't simply update to the latest svg.js - use the polyfill, found here - [pathseg polyfill](https://github.com/progers/pathseg). Just throw it in before your svg.js reference in the html.
