### ISSUE TITLE
Updating text using select() does not work directly

### ISSUE THREAD

**Issue by silverhawk184** [wout/svg.js#468]
I have my text in a group and want to update it.
What should work: groupVariable.select('text').text('new text');
I get an error saying "cannot read property "text" of undefined

To make it work, I need to access it this way: groupVariable.select('text').members[0].text('new text');

**Comment by Fuzzyma** [comment]
That's indeed not the intended behavior. I will take a look on it

**Comment by Fuzzyma** [comment]
A `Set` only inherits the methods from the shape class. So it doenst include any special method from a subclass like text. Thats somewhat unsatisfying. Maybe we find a way to change that

**Comment by wout** [comment]
With the current api there are three ways to achieve what you want without touching the (private) members property.

Get the first object:

```javascript
groupVariable.select('text').first().text('new text')
```

Get an object at a specific index:

```javascript
groupVariable.select('text').get(0).text('new text')
```

Or change the text value on every instance of or `SVG.Text`:

```javascript
groupVariable.select('text').each(function() {
  this.text('new text')
})
```

However, there is no `text()` method on `SVG.Set`.

**Comment by wout** [comment]
Due to its age, I'll close this issue for now. Please let us know if you have any further questions.
