### ISSUE TITLE
SVG.Matrix.native() throws error if SVG.prepare is not called

### ISSUE THREAD

**Issue by rdfriedl** [wout/svg.js#471]
if you call `new SVG.Matrix()` before you create any `SVG.Docs`
it will throw an error because `SVG.parser` is not defined.
im not sure if this is intended or not, but would it be possible to look into change how the parser object is created so it would be possible to use the `SVG.*` elements without having to create a `SVG.Doc`

i know i can always call `SVG.prepare(document.body)` but i thought it would make more since if you where able to create svg objects without having to set anything up.

here is an example for demonstration purposes https://jsfiddle.net/e267eyst/

**Comment by Fuzzyma** [comment]
No this is ofc no intended behavior. However - we would have to make checks at multiple places to cover this issue well.
Maybe we have to create the parser directly after the support check in any case no matter when the SVG.Doc is actually created. That would solve that problem quite well

**Comment by wout** [comment]
I think creating the parser right after the support check would be a very elegant solution indeed.
For sure it's better than it is right now so I'm all for it.

**Comment by Fuzzyma** [comment]
That leads to the problem of `dom not loaded` when the `prepare()` function is called.
We need at least the body when we want to create the parser in it. Any idea on how to solve that problem? (except placing the script tag at the end of the body)

**Comment by wout** [comment]
Why not wrap it in a:

```javascript
SVG.on( 'DOMContentLoaded', function() {
  // prepare
})
```

(not tested though)

**Comment by Fuzzyma** [comment]
Oh, yes - of course. Wasn't aware that this is already available in IE9

**Comment by wout** [comment]
True, so why not the good old:

```javascript
document.addEventListener( 'DOMContentLoaded', function() {
  // prepare
});
```

;)

**Comment by Fuzzyma** [comment]
I guess using the native stuff is allowed when initializing a lib ^^.
Just fixed it

**Comment by wout** [comment]
Brilliant!

**Comment by Fuzzyma** [comment]
meeh - there is something wrong anyway. I get an error in my test code.
The problem is the following:
The prepare function is called, when the code is ready. My code runs with the jquery ready event which for some reason fires first?!?
As soon as I do any matrix operation I get the error, that the parser is not defined...

**Comment by rdfriedl** [comment]
thanks guys, i appreciate the work you guys are putting into this issue.
its not something i need fixed, its just a bug a came across while using this library :D

anyways thanks again for responding / check this issue so fast
