### ISSUE TITLE
svg.js:2128 Error: Invalid negative value

### ISSUE THREAD

**Issue by GildoMat** [wout/svg.js#472]
Hi! I'm using SVG.js in an svg editor. It seems working well, but when the zooming level is too high, it starts, for example drawing rects, report a lot of errors like this:
![screenshot - 02_04_2016 00_31_35](https://cloud.githubusercontent.com/assets/9540618/14221849/5af058bc-f86a-11e5-85d7-1b5a10d655c8.png)

**Comment by Fuzzyma** [comment]
Looks like you are passing a negative value to width^^

**Comment by GildoMat** [comment]
sorry, I forgot one thing. I'm using your draw plugin, and I have implemented the drawing procedure, like esplained in your documentation,
Start drawing:
`			case 'tool_rect':
				elm=glb.Draw_active().GetActiveLevel().rect();
				elm.radius(0);
				elm.stroke({width:glb._sv_LineStroke,color :glb._sv_Colore_FG, opacity :glb._sv_SOpacity});
				elm.fill({color :glb._sv_Colore_BG, opacity :glb._sv_FOpacity});
				elm.draw(e,{	snapToGrid :	glb._sv_GridGap});
`
End drawing:
`				case 'tool_rect':
					//elm.draw('stop',e).selectize({deepSelect:true}).resize();
					elm.draw('stop',e);
					glb.Draw_active().setModified();
`
So when I am drawing, with the mouse, using the plugin, if the zoom is less then 1 no problems with the plugin if I try to draw with the area zoomed, any value more then one I have the reported problem. I hope is quite clear (sorry for my poor english).I hope the image can help you to understand what I mean...
![screenshot - 02_04_2016 15_00_49](https://cloud.githubusercontent.com/assets/9540618/14226495/595a8a7a-f8e4-11e5-9813-56504c37420d.png)

**Comment by Fuzzyma** [comment]
What exactly is your zoom doing?
Is it css zoom, viewbox zoom, simple scaling of everything?

**Comment by GildoMat** [comment]
This is the routine that resizes the svg canvas every time I change the zoom value, after the calculations:

`	// Function: RefreshCanvas
	// Updates the editor canvas width/height/position after a zoom has occurred 
	//
	// Parameters:
	// w - Float with the new width
	// h - Float with the new height
	//
	// Returns: 
	// Object with the following values:
	// * x - The canvas' new x coordinate
	// * y - The canvas' new y coordinate
	// * old_x - The canvas' old x coordinate
	// * old_y - The canvas' old y coordinate
	// * d_x - The x position difference
	// * d_y - The y position difference
	'RefreshCanvas':  function(w, h) {
		var DrawPlan=this.PianoLavoro.node;
		DrawPlan.setAttribute("width", w);
		DrawPlan.setAttribute("height", h);
		var bg = $('#BackGround')[0];
		var deskPlan = document.getElementById('deskPlan');
		var old_x = deskPlan.getAttribute('x');
		var old_y = deskPlan.getAttribute('y');
		var x = (w/2 - this._sv_contentW*this._sv_zoom/2);
		var y = (h/2 - this._sv_contentH*this._sv_zoom/2);
		//Magic Eye
		this.totCoord.width=w;
		this.totCoord.height=h;
		this.totCoord.x=x;
		this.totCoord.y=y;
		this.assignAttributes(deskPlan, {
			width: this._sv_contentW*this._sv_zoom,
			height: this._sv_contentH*this._sv_zoom,
			'x': x,
			'y': y,
			"viewBox" : "0 0 " + this._sv_contentW + " " + this._sv_contentH
			});

		this.assignAttributes(bg.childNodes[0], {
			width: deskPlan.getAttribute('width'),
			height: deskPlan.getAttribute('height'),
			x: x,
			y: y
			});

		var bg_img = DrawPlan.querySelector('#background_image');
		if (bg_img) {
			this.assignAttributes(bg_img, {
				'width': '100%',
				'height': '100%'
				});
			}

		// refresh the selector grips
		this.sel_Manager.setAttribute("transform", "translate(" + x + "," + y + ")");
		return {x:x, y:y, old_x:old_x, old_y:old_y, d_x:x - old_x, d_y:y - old_y};
		},
`

**Comment by Fuzzyma** [comment]
A simple "I use viewbox zoom" would have been enough here ;)
I dont know how to repliacate your issue. A fiddle would help a lot to track down the error.

**Comment by GildoMat** [comment]
Sorry! But I weren't sure what was the right answer. You must be patient with me...

About the Fiddle sample at the moment it is a little bit hard for many reasons. However I have done, this afternoon different test and, in my opinion, I think that my canvas manipolation outside of the library, may be, can create confusion in the plugin. It may be will use some variables stored into the Lib database, and may be my manipulation with the zoom function, can create some obsolete values in the stored values, in this way, when the plugin will  use those values can have impredictable results. I had similar problems with other plugins (select and resize) and I had to rewrite my own temporary functions.

**Comment by Fuzzyma** [comment]
I tried to keep the draw mechanism seperated from all other variables and scoped inside the plugin. I dont know what could cause confusion. However your code is huge and tracking down the error is really hard. Thats why I asked you to break down the code to the problem. Otherwise I wont be able to help you in an efficient way

**Comment by wout** [comment]
I'm closing this issue for now. Please let us know if you have any more questions.
