### ISSUE TITLE
No examples at http://svgjs.com/

### ISSUE THREAD

**Issue by matthewoates** [wout/svg.js#474]
Yes, this is a duplicate, but it should be open. A disclaimer could be added that the examples don't work in 2.x.

**Comment by wout** [comment]
Which examples are you referring to?

**Comment by matthewoates** [comment]
The examples referred to here:
https://github.com/wout/svg.js/issues/463

The title made it sound like there was a suite of examples on the website.

A very real use case for me: I'm trying to evaluate performance of the SVG animations using your library on my target devices. If the examples (even if they're a little dated) are not hosted, this testing becomes much more difficult.

**Comment by wout** [comment]
Unfortunately we don't have any working examples at the moment
The references to the examples on the site are already removed.

I can't offer you much at the moment.
But we're working hard on a new home page with plenty examples.

**Comment by wout** [comment]
We're working on a new site which will see the light within weeks. Examples will be added systematically.
