### ISSUE TITLE
.animate.radius() does not work for circles

### ISSUE THREAD

**Issue by matthewoates** [wout/svg.js#477]
Broken again in 2.3.0

https://github.com/wout/svg.js/issues/366

**Comment by Fuzzyma** [comment]
What happens when you use it?

**Comment by matthewoates** [comment]
The same as the cited issue.

The codepen is still accurate, and points to the latest built assets from your repo.

http://codepen.io/anon/pen/gpQyQZ

**Comment by matthewoates** [comment]
Debugged this. The code that orignally fixed #366 is still there, but `type` is undefined so the new condition doesn't appear to ever fire.
```
SVG.extend(SVG.Rect, SVG.Ellipse, SVG.Circle, SVG.Gradient, SVG.FX, {
  // Add x and y radius
  radius: function(x, y) {
    var type = (this.target || this).type;
    // `type` is undefined here when animating radius on circles
    return type == 'radial' || type == 'circle' ?
      this.attr({ 'r': new SVG.Number(x) }) :
      this.rx(x).ry(y == null ? x : y)
  }
})
```

**Comment by Fuzzyma** [comment]
fixed in 700a77060fe2b347e256abdb423c75a05613a690

**Comment by matthewoates** [comment]
http://t5.rbxcdn.com/641a428b3c1431c534f50cf8f47858d8

**Comment by matthewoates** [comment]
neat
