### ISSUE TITLE
.size(0, 0) doesn't work for images

### ISSUE THREAD

**Issue by matthewoates** [wout/svg.js#478]
```
var draw = SVG('drawing').size(400, 400);
var image = draw.image('http://static2.businessinsider.com/image/511d104a69bedd1f7c000012/grumpy-cat-still-hates-everyone-at-south-by-southwest.jpg');

image.size(0, 0);
```

**Comment by Fuzzyma** [comment]
Thats not completly true.
`size()` does work. Svg.js set the size of the image to its vales automatically **when** the image is loaded. You set the size of the image directly after creation where the image is not already loaded.
So svg.js overwrites your size.

However: Keep a look at the [`loaded()`](https://github.com/wout/svg.js#loaded) method which let you specify a function which should be called as soon as the image is loaded. In this function you can set the size.

**Comment by matthewoates** [comment]
I see.

```
var draw = SVG('drawing').size(400, 400);
var image = draw.image('http://static2.businessinsider.com/image/511d104a69bedd1f7c000012/grumpy-cat-still-hates-everyone-at-south-by-southwest.jpg');

setTimeout(function () {
  image.size(0, 0);
}, 1000);
```
works as expected.

thanks for the quick reply.

**Comment by Fuzzyma** [comment]
That's actually the wrong way to do that. As I said: use the loading method:

```javascript
draw.image('url').loaded(function(){
    this.size(0,0)
} ) 
```
