### ISSUE TITLE
Exponential numbers problem in ViewBox

### ISSUE THREAD

**Issue by newgerstas** [wout/svg.js#483]
In the ViewBox constructor there is a line with code "reg  = /-?[\d\.]+/g" with used to split numbers by any char between them. Which is wrong. It doesn't let use exponential numbers like **100.1234e-5**. So it just splits the number and gets two 100.1234 and -5. 
For instance: If would have a viewbox="100, 100.1234e-5, 200, 200" the regex will split it like an array of values [100, 100.1234, -5, 200, 200] and the last number will be omitted which gets negative width for viewbox.

I guess it would be fixed like this: /-?[\d\.Ee\\-\\+]+/g

**Comment by thomasd16** [comment]
According to the w3c standards for number types in SVG's number can be any floating point value [Source](https://www.w3.org/TR/SVG/types.html#DataTypeNumber) (but is usually an integer). The standard is almost identical to that of JSON. A better more exact regular expression that matches the w3c standards would be /[+-]?\d+(?:\.\d+)?([eE][+-]?\d+)/. ![visualization](https://www.debuggex.com/i/PUQmt0PzMmZKXKsz.png)

**Comment by Fuzzyma** [comment]
I tested your regex and found, that albeit the graphic is corretc, the regex misses an `?` at the end.
So it shoud be `/[+-]?\d+(?:.\d+)?([eE][+-]?\d+)?/` right?
