### ISSUE TITLE
Fix Illustrator Viewbox Method - Clean up Illustrator SVG

### ISSUE THREAD

**Issue by villanus** [wout/svg.js#484]
When you save a vector as SVG from adobe illustrator often times the ViewBox is does not start at "0 0 x y".   This throws off everything including all the paths. 

For example:
viewBox="300 66 720 432"

Is there a method to reset the viewbox to "0 0" and all the sub paths, rects, etc... ???

This would be really useful for those who are starting off with Illustrator for SVGs.

**Comment by Fuzzyma** [comment]
I don't understand exactly why it does mix up everything. After all viewbox ist just a translation and a zoom. And when you saved it this way why you would want to change it? However - svg.js does not cleanups. Nevertheless you could write an add-on which does that for you.

**Comment by wout** [comment]
@villanus Could you maybe create a fiddle to better illustrate your problem?

**Comment by villanus** [comment]
Sure:
https://jsfiddle.net/trurhu1h/5/

As you can see, when you save a vector as an SVG in adobe Illustrator (CS 6 or CC) the viewbox does not start with 0 0.   The only way I think you can fix this in illustrator alone is to:
1. Save the SVG
2. Open the SVG in illustrator
3. Select everything.
4. Change the X to 0
5. Change the Y to 0
6. Save again.

It would be sweet if the viewboxes were always set to 0 0  at the beginning, along with some more cleaning up.

In the fiddle I have 3 svg files.
1. Saved a vector as SVG using illustrator
2. Used clean up method (six steps) described above
3. Cleaned up the SVG tag manually.

**Comment by Fuzzyma** [comment]
Thank you for your fiddle!
As I already mentioned: The libraray MUST NOT change the svg when it is loaded into the svg. The user has to provoke this changes. Therefore svg.js will not automatically "clean" an svg. Note, that "clean" for you means "destroy" for other users.

Thats why you should write a plugin which adds a function (say `clean()`).
You can then call that function after you loaded the svg: `SVG('your_svg').clean()`

**Comment by wout** [comment]
I second that. SVG.js is not responsible, nor required to modify inputted data in any way. If some application outputs data which is not in a format desired by the user, the user should take the responsibility to modify the data accordingly, not SVG.js.

**Comment by villanus** [comment]
Doing this as a plugin or extension makes complete sense.  
I am a little confused on what to do with the paths.   If i set the new viewbox, dont the paths all need to be recalculated to the new offsets?

**Comment by Fuzzyma** [comment]
Thats correct. After all it was only a start.
However you would do something like this:
```javascript
SVG.extend(SVG.Doc, {
  clean: function(){

    var box = this.viewBox()

    // remove height, width and set new viewbox
    this.height(null).width(null).viewBox(0, 0, box.width, box.height)

    // adjust children
    this.children().dmove(viewBox.x, viewBox.y)
  }
})
```

**Comment by villanus** [comment]
Sweet.
I will give it a go when I get home from work. 

As always you and Wout are the best!
