### ISSUE TITLE
How to donate/support?

### ISSUE THREAD

**Issue by ActionScripted** [wout/svg.js#486]
Using SVG.js in a project and would love to support the project monetarily to help with ongoing development, hosting costs, etc. Flattr, PayPal, something?

(I know the issues section might not be the best place for this sort of request.)

**Comment by Fuzzyma** [comment]
We added a donate button to the docs. Thank you very much for that :)

**Comment by wout** [comment]
In the meantime we added a PayPal donate button. Please let me know if you have any more questions.
