### ISSUE TITLE
draw.line does not work with array of points

### ISSUE THREAD

**Issue by Satyam** [wout/svg.js#487]
In https://github.com/wout/svg.js/blob/master/src/line.js#L19 it checks for 4 arguments but if called from https://github.com/wout/svg.js/blob/master/src/line.js#L42 it will always get 4 arguments, even if the last three are `undefined` and the first one contains an array of points.

**Comment by Fuzzyma** [comment]
True, It should be checked for single arguments instead of the lengths of the arguments

**Comment by Satyam** [comment]
Probably just checking whether `y1` is `undefined` or not would do.
