### ISSUE TITLE
Adding multiple lines dynamically for text

### ISSUE THREAD

**Issue by Santhoshsvg** [wout/svg.js#488]
I am having a textarea content which needs to be added as text in SVG using SVG TEXT() method.

Content of textarea will be split based on the newline characters present in content and needs to be added as tspan to the SVG element with newline() added.

```javascript
var inText = input.value.replace(/(?:\r\n|\r|\n)/g, '\n');
var tspanText = inText.split( "\n" );
var tspan;
for( var i = 0; i < tspanText.length; ++i ) {
	//element.tspan(tspanText[i]).newLine();
	element.text(function(add) {
	  add.tspan(tspanText[i]).newLine()
	})
	element.tspan(tspan);
}
```

Only the last line of the textarea content is added to the text element.

**Comment by Fuzzyma** [comment]
ok forst I will explain to you, why your code is not working and then I will tell you a secret ;)

For every line you call the `text()` method on the element. Like any other command this sets the value of text - so its getting replaced over and over.

This can be avoided if you call `build(true)` before the `text` call which activats the build mode of text. You then can add `tspans` for every line which doenst get removed like this:

```javascript
element.build(true)

// in the loop
element.tspan('foo').newLine()
```

However its still not really useful whats written there.
You should switch the loop and the builder function where you add the text:

```javascript
    element.text(function(add) {
      for( var i = 0; i < tspanText.length; ++i ) {
          add.tspan(tspanText[i]).newLine()
      }
      add.tspan(tspan);
    })
}
```

That would work best - but now: **the secret**
svg.js automatically trade newline-charackters as newline and build up the text element for you.
So just call `text("Some Text \nWith newlines in it \nSo beatiful")` and let the magic happen.

Btw: Thats all in the docs: https://github.com/wout/svg.js#text

**Comment by Santhoshsvg** [comment]
Thanks a lot Ulrich master,

I did the other way by picking the newline and then adding each one as a
seperate tspan.

thanks for the mail.

On Thu, May 26, 2016 at 4:06 PM, Ulrich-Matthias Schäfer <
notifications@github.com> wrote:

> ok forst I will explain to you, why your code is not working and then I
> will tell you a secret ;)
>
> For every line you call the text() method on the element. Like any other
> command this sets the value of text - so its getting replaced over and over.
>
> This can be avoided if you call build(true) before the text call which
> activats the build mode of text. You then can add tspans for every line
> which doenst get removed like this:
>
> element.build(true)
> // in the loopelement.tspan('foo').newLine()
>
> However its still not really useful whats written there.
> You should switch the loop and the builder function where you add the text:
>
>     element.text(function(add) {
>       for( var i = 0; i < tspanText.length; ++i ) {
>           add.tspan(tspanText[i]).newLine()
>       }
>       add.tspan(tspan);
>     })
> }
>
> That would work best - but now: *the secret*
> svg.js automatically trade newline-charackters as newline and build up the
> text element for you.
> So just call text("Some Text \nWith newlines in it \nSo beatiful") and
> let the magic happen.
>
> Btw: Thats all in the docs: https://github.com/wout/svg.js#text
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/wout/svg.js/issues/488#issuecomment-221793951>
>



-- 
Santhosh Kumar.M
(+81)90-7828-4552

**Comment by Santhoshsvg** [comment]
Thanks a lot Ulrich,

That helped a lot and i was able to achieve things.
