### ISSUE TITLE
Event propagation

### ISSUE THREAD

**Issue by Frique** [wout/svg.js#491]
I'm working with click events on both the SVG background and on polygons. Currently when clicking a polygon, both events fire. Is there a way to prevent propagation, so that when clicking a polygon, the background click event does not fire?

**Comment by Fuzzyma** [comment]
Does `event.stopPropagation()` not work?

**Comment by Frique** [comment]
It does actually. In my situation I was mixing up jQuery events with the svg.js events which caused the issue. Thanks for the reply!
