### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by harlantwood** [wout/svg.js#492]
This library looks great!  Publishing it to NPM would make it easier to use for many of use.  (Prior art:  #255)

**Comment by Fuzzyma** [comment]
You mean like this? https://www.npmjs.com/package/svgjs
So you can install it with `npm install svg.js`?

**Comment by harlantwood** [comment]
Ah, yes, excellent, thanks.  Perhaps we should add this to the readme; I actually searched npm and did not find the lib somehow. .

**Comment by harlantwood** [comment]
Hm, also looks like there is a different version published at https://www.npmjs.com/package/svg.js BTW.

**Comment by Fuzzyma** [comment]
https://www.google.de/search?q=npm+svgjs
There is a package.json and a bower.json so everyone should know, thats pubslished there.
Also: just run the command and you will see, that it fetches the right version
