### ISSUE TITLE
ungroup is not working

### ISSUE THREAD

**Issue by Santhoshsvg** [wout/svg.js#493]
I am trying to ungroup/flatten a group object and i am not able to perform the same.
It is giving error as "Uncaught TypeError: Cannot read property 'nodeName' of null"

I am giving the SVG container element as the parameter with null value for the depth.

Code : 
var grpDraw = SVG('cvs');
var groupElement = SVG("groupId");
groupElement.ungroup(grpDraw );

Please let me know where i am going wrong.

Thanks in Advance.

Regards,
Santhosh.M

**Comment by Fuzzyma** [comment]
Neither `SVG('cvs')` nor `SVG("groupId")` can be a group. The SVG-command creates a new SVG in the node with the given id. It has nothing to do with creating groups. Please try to fix that first

**Comment by Santhoshsvg** [comment]
Sorry my mistake,

I need to send the parent document of the group which needs to be ungrouped.

I am sending 

var groupElement = SVG.get("groupId");
groupElement.ungroup(groupElement.parent());

Sorry now it is working without any issues.

Thanks a lot once again for pointing out the silly mistake that i had made.
