### ISSUE TITLE
By Default SVG is getting created in the page

### ISSUE THREAD

**Issue by Santhoshsvg** [wout/svg.js#495]
Dear All,

Thanks in advance for the help i am going to get for the below created issue.

I am having a HTML page with built in SVG tag [SVG Area] available in the div.

I am having button to create a Circle and when the button is clicked i am getting the existing SVG canvas by using the following code.

But still there is one SVG tag available in the code with the following data.

```xml
<svg id="SvgjsSvg1001" width="2" height="0" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs" style="opacity: 0; position: fixed; left: 100%; top: 100%; overflow: hidden;">
    <defs id="SvgjsDefs1002"></defs>
    <polyline id="SvgjsPolyline1003" points="0,0"></polyline>
    <path id="SvgjsPath1004" d="M0 0 "></path>
</svg>
```

circle creation code
```javascript
var cirDraw = SVG.get('cvs');
var circle = cirDraw.circle(50);
circle.fill("#FFFFFF");
circle.stroke("#000000");
```

SVG Canvas available in the HTML page.

```xml
<svg id="cvs" height="500" width="580"></svg>
```

Please show some light where i am doing the mistake.

**Comment by Fuzzyma** [comment]
Dont worry about that one. This node is never visible on your screen and wont interfer with any other elements. Note the style tag: `style="opacity: 0; position: fixed; left: 100%; top: 100%; overflow: hidden;"`.

We need this node in order to make some functions of the library work and we call it our `parser`.

**Comment by Santhoshsvg** [comment]
Thanks a lot Ulrich Master.

Will close this issue now.
