### ISSUE TITLE
exporting the svg for the child elements alone

### ISSUE THREAD

**Issue by Santhoshsvg** [wout/svg.js#496]
how to export the raw svg data for the root svg tags childs alone

Now when i use rootElement.svg(); it is giving the root element also.

Throw some light on this.

**Comment by wout** [comment]
the easies thing to do would be something like this:

```javascript
var data = ''

rootElement.each( function() {
  data += this.svg()
})
```

**Comment by wout** [comment]
Did this answer resolve your issue? I'll be closing this for now.
