### ISSUE TITLE
Any plugins available for performing Undo Redo Operation

### ISSUE THREAD

**Issue by Santhoshsvg** [wout/svg.js#497]
Hi,

I am trying to implement Undo / Redo Operation.

Is there any plugin available for that.

Actually i tried implementing in the following manner.
1. At the start of each operation, adding the current status of the svg container to the Array.
2. When the user clicks the undo button, the latest item in the array will be imported to the current svg container. 

For exporting i am using the SVG.get('svgcontainer').svg();
For importing i am using the SVG.get('svgcontainer').absorb(undoArray[lastElement]);

Here i am facing the following problems.
a) While exporting it is exporting from the <svg> tag onwards. So while importing i am getting <svg> tag inside <svg> tag. For this i need to remove the svg tag using the substring method and import.
b) After importing the Draggable and Resizable properties which i had added to the elements are not occuring.

Please let me know is there any direct undo/redo plugin is available. If it is not available then can you please show some light on how to solve the above issues.

Even when i checked the source code for svg.js i am able to see undo function but not clear about the procedure for using the same.

Thanks!

Regards,
Santhosh.M

**Comment by wout** [comment]
Hi,

I wrote an undo/redo micro library wich might serve the purpose:
https://github.com/wout/chronology.js

It's easy to extend and has no dependencies.
So it works also outside of SVG.js.

**Comment by Santhoshsvg** [comment]
Thanks for the update.
But i believe this might not work out since for my work i need based on the elements position and transforms.

Like position moved from one place to another and resized. So the undo operation needs to make the element to the old size before resizing first and at the second undo click the element needs to be moved to the old position before dragged.

This i believe it cannot be implemented with chronology.

Correct me if i am wrong.

Thanks in advance!

**Comment by wout** [comment]
You will need to register all befores and afters in your code. This will not all be registered automagically.

So instead of moving an SVG.js element like this:

```javascript
rect.move( 100, 150 )
```

You'll have to move it like this:

```javascript
var previous = {
  x: rect.x()
, y: rect.y()
} 

chronology.add({
  up:   function() { rect.move( 100, 150 ) }
, down: function() { rect.move( previous.x, previous.y ) }
})
```

I wrote this library (and SVG.js) for an online vector editor so it definitely does the job. With draggable functionality for example:

```javascript
rect.on( 'beforedrag', function() {
  rect.remember( 'previousX', rect.x() )
  rect.remember( 'previousY', rect.y() )
})

rect.on( 'dragend', function() {
  chronology.add({
    up:   function() { rect.move( rect.x(), rect.y() ) }
  , down: function() { rect.move( rect.remember( 'previousX' ), rect.remember( 'previousY' ) ) }
  , call: false //-> this makes sure the move is registered but not performed again after dragging
  })

  rect.forget( 'previousX' )
  rect.forget( 'previousY' )
})
```

**Comment by Santhoshsvg** [comment]
Thanks a lot.

Down with sick.

will check this today and will update if any issues i come across.

Regards,
Santhosh.M

**Comment by wout** [comment]
@Santhoshsvg I'm closing this issue for now. Please let me know if you have any more questions.

**Comment by ali-mohtashim** [comment]
@wout thanks for the very helpful code... undo/redo functionality is working fine but its delete and append element again
