### ISSUE TITLE
How to create a title element inside a polygon

### ISSUE THREAD

**Issue by splattne** [wout/svg.js#500]
I tried the following (simplified example):

    var polygon = draw.polygon('0,0 100,50 50,100').fill('none').stroke({ width: 1 });
    polygon.element('title').words('I am a polygon');

I get the exception `Uncaught TypeError: polygon.element is not a function`.

What is the right way to create a title tag inside a polygon? I also tried to create the title element using the parent of polygon and use to .add(). But polygon also misses the add method.

**Comment by wout** [comment]
It's advisable to add title elements as the first child of container elements.
Something like:

```javascript
var draw = SVG( 'drawing' )
  , group = draw.group()

group.element( 'title' ).words( 'the realness' )
group.rect().size( 100, 100 ).fill( '#f06' )

```

https://jsfiddle.net/bo8mb33a/2/
