### ISSUE TITLE
Center aligned move

### ISSUE THREAD

**Issue by ramezrafla** [wout/svg.js#502]
@woot and @Fuzzyma 
I tried to do this on my own but hit a wall due to my weak understanding of SVG coordinates. I am trying to add a custom moveTo function to element.js that would align the centers.

```
moveTo: function(element) {
        var ebb = element.bbox()
        var mbb = this.bbox();
        // getting the transform from one coordinate system to the other
        var ctmt = element.parent().ctm().multiply(this.parent().ctm().inverse());
        var x = ebb.cx / ctmt.a + ctmt.e - mbb.width/2;
        var y = ebb.cy / ctmt.d + ctmt.f - mbb.height/2;
        return this.x(x).y(y)
    }
```

This works for three of four test cases and I can't get it to work for the 4th one. If you have the time to take a quick expert glance it would be really appreciated!

[note: rect is inside a group that has been transformed]
```
rect.moveTo(circle) -- works
circle.moveTo(rect) -- works
rect.moveTo(circle.scale(2)) -- works
rect.scale(2).moveTo(circle) -- fails!
```

**Comment by Fuzzyma** [comment]
You touched a topic here that is not easy to handle.
One does not simply extract the translation from a transformation matrix. Often you just get crap when you try to use the flat values (like e and f). Especially when skew and rotation comes in, it doenst work anymore.

The only thing I can imagine is, that you create the [bounding client rect](https://developer.mozilla.org/de/docs/Web/API/Element/getBoundingClientRect) for each shape to get the actual difference bewteen 2 centers and then add this difference to one shape via relative translation to make it align with the center of the other shape.
Its never a good idea, to set absolute transformations since this is not possible in a reliable way.
Actually the only reason why this is implemented in the liraray is, to make a **non-transformed** group behave like any other shape when setting its position.

Some example code:

```javascript
moveTo: function(element) {
    var ebb = element.node.getBoundingClientRect()
    var mbb = this.node.getBoundingClientRect()

    var diffX = ebb.x - mbb.x
    var diffY = ebb.y - mbb.y
    
    return this.transform({x:diffX, y:diffY}, true)
}
```

No guarantee!

**Comment by ramezrafla** [comment]
Thanks a lot @Fuzzyma for taking the time to respond. Really appreciated!

Will try this approach with the bounding rect.

Do I need to apply the transform of the current object  to diffx,y? In other words, these two diffs are relative to the viewport not the current object's coordinate system. Is that ok with how the transform is applied in your function?

**Comment by ramezrafla** [comment]
@Fuzzyma,

Unfortunately the formulas did not work. I read through the theory a bit more https://www.w3.org/TR/SVG/coords.html and did the matrix math by hand. Here are the correct equations. Works great (and makes sense). For instance, using getBoundingClientRect requires correction for viewport scaling.

```
  , moveTo:  function(element) {
      var ebb = _g('s2').bbox()
      var mbb = _g('s1').bbox();
      // getting the transform from one coordinate system to the other
      var ctmt = _g('s2').ctm().multiply(_g('s1').ctm().inverse());
      var x = ctmt.a * ebb.x + ctmt.c * ebb.y + ctmt.e - mbb.x;
      var y = ctmt.b * ebb.x + ctmt.d * ebb.y + ctmt.f - mbb.y;
      return this.transform({x:x,y:y});
    }

```

Next on my challenge list is getting the actual center of the objects in their own coordinate system -- still figuring it out.

**Comment by Fuzzyma** [comment]
Well yes - as I said: Just an idea :D.
I dont know if your approach works when you start rotating your elements.
I made clear that absolute transformations are critical. However if it works for you its fine.

To your next challenge: Thats is rather easy.
>  The bounding box is the tightest fitting rectangle aligned with the axes of the applicable element's user coordinate system that entirely encloses the applicable element and its descendants.

(https://www.w3.org/TR/SVG/coords.html#ObjectBoundingBoxUnits)

Or even better stated in the SVG2 specification:
> The bounding box (or "bbox") of an element is the tightest fitting rectangle aligned with the axes of that element's user coordinate system that entirely encloses it and its descendants.

(https://www.w3.org/TR/SVG2/coords.html#BoundingBoxes)

Well - more or less the same but a better link^^.
That means that your bbox is already in the coordinate system of the element. So you can just calculate the center from your x,y and width,height values of the bbox. It then will give you `the actual center of the objects in their own coordinate system`

**Comment by ramezrafla** [comment]
Thanks @Fuzzyma 
We ended up using the getScreenCTM to compute proper coordinates (twice, rel to abs and then back to the coordinate space of the object we are moving). Overall, loving svg.js
