### ISSUE TITLE
Change the starting point on a closed path

### ISSUE THREAD

**Issue by bildlich** [wout/svg.js#506]
Imagine a triangle with three points P1, P2, P3.
P1 is the starting point. Can I make P2 the starting point?

I am morphing a path into another with [svg.pathmorphing.js](https://github.com/Fuzzyma/svg.pathmorphing.js). Redefining the starting point can make for a prettier animation because it determines which point fades to which.

See a demo (without changing the starting point) here: [CodePen](http://codepen.io/anon/pen/KrXopd?editors=1010)

**Comment by Fuzzyma** [comment]
You can alter the underlying `SVG.PathArray` and `plot` it again.
It should work somehow like this:

```javascript
var path = draw.path('Pathdata....);

// get the array
var arr = draw.path.array()

 // remove close path command (z)
arr.pop()

// get the first element
var first = arr.shift() 

// push it to the end
arr.push(first)

// add z back
arr.push(['z'])

// plot new path
path.plot(arr)
```

**Comment by Fuzzyma** [comment]
@bildlich can I close this?

**Comment by bildlich** [comment]
Thanks @Fuzzyma, this works for me.
