### ISSUE TITLE
Prevent random attributes being set.

### ISSUE THREAD

**Issue by bradodarb** [wout/svg.js#507]
Not sure how/why, and might very well be something simple I'm missing!

I'm noticing that some entities I generate such as a path or text are generating SVG elements with inline attributes such as font-family, x or dx, etc... with values that are unexpected and seemingly at random.

Anyone else have this issue?  Am I missing a something fundamentally here?

It forces me to do things such as-

```javascript
var var2 = target.text(function (add) {
    add.tspan(opts.variable2).addClass('slide-variable2-label')
       .y(opts.barLength).dy('1em');
}).x(v2Xoffset).attr('font-family','');
```

Note the clearing of font-family so I can target the element via CSS instead.

**Comment by Fuzzyma** [comment]
There is nothing random about that. In order to render things in a definite way, svg.js provides default values for several attributes including `font-family` and `font-size`. You can change this values.
Take a look at the `SVG.defaults` object (https://github.com/wout/svg.js/blob/master/src/default.js)

**Comment by wout** [comment]
Did this answer resolve your issue? I'll be closing this for now.

**Comment by bradodarb** [comment]
I can see setting reasonable defaults  for attributes not accessible through CSS, but for the properties that can be targeted via style sheets it's a bit intrusive IMO.

Maybe a good compromise could be an options setting where setting display property default values could be disabled?

**Comment by Fuzzyma** [comment]
Some functionality of svg.js is based on these properties. E.g. to correctly calculate the leading of lines, we need a font-size to be set. One may discuss if we should use `getComputedStyle` but this would add one more dom dependeny and is slower. I dont know if this is worth it
