### ISSUE TITLE
How to draw a path with dasharray and dashoffset?

### ISSUE THREAD

**Issue by god99me** [wout/svg.js#511]
Help me please and thanks a lot.
I already somehow I can make the path(line) move, draw itself, and become dash line by css attribute 'dasharray' and 'dashoffset'.
But I do wonder if this animation can be done with svg.js either.
Thanks again if u know the answer , or give me some hint(keyword) so that I can search myself in document.

**Comment by Fuzzyma** [comment]
What about `path.attr('stroke-dashoffset', 50)`?
If you want to animate it, it would be `path.animate().attr('stroke-dashoffset', 50)`.

PS: This is an issue tracker. Please post questions on stackoverflow and tag them with `svg.js`
