### ISSUE TITLE
line stroke-width not consistent

### ISSUE THREAD

**Issue by QuinDennis** [wout/svg.js#513]
In the attached image, there are two line styles, stroke-width 0.4 and 0.6.  the lines don't render cleanly and consistently in chrome

![screenshot from 2016-07-26 15-45-21](https://cloud.githubusercontent.com/assets/816529/17154791/1c0d0454-5348-11e6-85a9-7e3f79d9bd2c.png)

**Comment by Fuzzyma** [comment]
What do you expect? Whats your code? How can I reproduce this bug?

**Comment by QuinDennis** [comment]
My bad, this is just trying to render things on a less than pixel boundary.  I changed from lines to rects and added 'shape-rendering', much better.
![screenshot from 2016-07-26 17-11-49](https://cloud.githubusercontent.com/assets/816529/17157316/27e46ffe-5354-11e6-90b1-dbf6b56a2857.png)


g.rect(14,1).move(x+20,ytop+yrng*pct).attr({'shape-rendering':'crispEdges'})
