### ISSUE TITLE
multiple rect is very slow

### ISSUE THREAD

**Issue by lichtkabouter** [wout/svg.js#515]
Hi,

I'm drawing a grid (24 column, approx 200 rows) and I need to give a background color to some of the 'cells'. I've tried speeding things up by adding a background-pattern to the main SVG which saved me a lot of time. Now I'm only drawing rects on the positions where I need to have a background but after 20 rects or more the time to draw the rect is getting to 6 or even 10ms. so when drawing 1000 rects this counts up to multiple seconds.

Is there a way to speed this up? (the first rects draw within a millisecond but the more you draw the more time it takes per rect).

**Comment by ibrierley** [comment]
Is it possible to include a jsfiddle or jsbin showing a basic test with code you are using ?

**Comment by Fuzzyma** [comment]
Could be related to the bbox call in the size method of rect. I would test the same code when commenting out this call

**Comment by lichtkabouter** [comment]
`
var rowHeight, colWidth, SVG, rects
rowHeight = 20
colWidth = 40
SVG = SVG("test")
rects = []
for (i = 0; i<200; i ++) {
    for (j = 0 ; j < 24; j++) {
       var r = SVG.rect(colWidth, rowHeight).y(i*rowHeight).x(j*colWidth)
      // sometimes give some attributes
      // r.attr("datastate", "color");
      // r.attr("datatype", "type");
      rects[rects.length] = r
    }
}`

**Comment by lichtkabouter** [comment]
To show a example about how quick it can work:
http://jsfiddle.net/kzbwg/366/

That draws 10.000 squares and goes within milliseconds

**Comment by wout** [comment]
We're working on a fix.
Thanks for your input!

**Comment by wout** [comment]
@lichtkabouter A fix is on the way. Your example (4800 rects) runs in about 100-125ms now. As soon as we've verified it doesn't break anything else, we'll publish it.

**Comment by lichtkabouter** [comment]
@wout I've just noticed the problem also occurs on <text> elements (so a lot of <text> elements makes the script run slower).

**Comment by wout** [comment]
@lichtkabouter We just bumped to version 2.3.4 which brings speed improvements on creation of all element types. We're also working on other fixes as well to gain more speed.

**Comment by wout** [comment]
We added a tiny benchmarking system to be able to keep track of the performance of the library. This will help us to keep things up-to scratch. You can find it in the bench directory of the project. Basically it's a bit like the Jasmine spec runner, but very simple. You can add tests yourself easily to point out issues and everything is represented in a very clean way:

![screen shot 2016-08-04 at 18 46 30](https://cloud.githubusercontent.com/assets/107324/17410539/657bb4d6-5a74-11e6-8ed8-afb7a846bc60.png)

From the numbers you can see that the current release performs drastically better than the previous one. 😊

**Comment by wout** [comment]
Did the recent changes solve your problems?

**Comment by ibrierley** [comment]
I always like alternatives, and I have no idea if this could apply to SVG.js, but in Snap you could improve performance IF you're not so bothered about creating an initial wrapper around every single element (so its more like the raw version). eg..  

http://jsfiddle.net/ian_b/vv8x1qtw/

This would cut Snap down from 1820ms (on mine) to 129ms. Behind the scenes it puts it into a documentfragment and then appends each node iirc. There may be a penalty later if you need to wrap each element with Snap.

Maybe it defeats the object slightly, as you are ending up writing markup, but thought I would mention it in case its useful.

`var s = Snap("#svg");

var markup = '';
var rect = '<rect width="100" height="100" fill="#f06"/>';
for (var i = 0; i < 10000; i++) {
      markup += rect;
}
var frag = Snap.parse( markup );
s.append( frag );`

**Comment by wout** [comment]
Yeah, you could do the same for SVG.js which makes it even faster. If you're really after speed, it would be best to use vanilla js rather than a library. :)

It's our job to keep the extra load of SVG.js to a minimum. With the changes introduced in v2.3.4 that's already pretty acceptable.
