### ISSUE TITLE
Path intersection feature request

### ISSUE THREAD

**Issue by amatiash** [wout/svg.js#521]
First, thank you very much for the library!

I switched from **Raphael**. I also tried **snap.svg**. But I found **svg.js** much better!

There is one thing thats keeping me still load Raphael core -  its just one function that checks intersections of 2 paths: `Raphael.pathIntersection(path1, path2)`. So for this one function I have to load **55.30 KB min** code.

Can you please implement this functionality in svg.js? Or may be a plugin for this can be created...

P.S.
I've searched for alternatives but there were no light solutions.

**Comment by wout** [comment]
Thanks for using SVG.js!

We'll have to look into that, shouldn't be that hard to port from Raphael. The only big issue is time.

**Comment by amatiash** [comment]
I understand, thanks in advance!

**Comment by amatiash** [comment]
I found a solution. I wrote a [plugin](https://github.com/amatiash/svg.intersections.js) for it. You can check it out :)

**Comment by wout** [comment]
Wow, brilliant! Thanks for your contribution! I added the plugin to our plugins section in the docs:

https://github.com/wout/svg.js/blob/master/README.md#intersections

**Comment by amatiash** [comment]
Thanks))
