### ISSUE TITLE
mouseleave event missing

### ISSUE THREAD

**Issue by edemaine** [wout/svg.js#526]
The documentation lists:

> All available events are: click, dblclick, mousedown, mouseup, mouseover, mouseout, mousemove, touchstart, touchmove, touchleave, touchend and touchcancel.

Strangely, this is missing "mouseleave".  See e.g. http://www.w3schools.com/jquery/tryit.asp?filename=tryjquery_event_mouseleave_mouseout

**Comment by wout** [comment]
True, for some reason we removed them, not sure why though. But you can always do:

```javascript
element.on( 'mouseleave', function() { ... })
```

The named methods are just shortcuts.

**Comment by edemaine** [comment]
Ah, indeed.  Sorry, missed that.  Not important then.

**Comment by wout** [comment]
No problem. Thanks for pointing it ut anyway!
