### ISSUE TITLE
Fix failing spec/point.js

### ISSUE THREAD

**Issue by dotnetCarpenter** [wout/svg.js#530]
I tried to fix [point.js](https://github.com/wout/svg.js/blob/master/spec/spec/point.js) but I can't figure out what it's suppose do.

@Fuzzyma I can see that you wrote the test (at least the last commit).

In particular [point is declared as a `undefined` variable](https://github.com/wout/svg.js/blob/master/spec/spec/point.js#L2) but [its used as a function](https://github.com/wout/svg.js/blob/master/spec/spec/point.js#L8). Which means the [next 2 asserts are failing](https://github.com/wout/svg.js/blob/master/spec/spec/point.js#L13-L14).

This is part of landing #527

**Comment by Fuzzyma** [comment]
oh - the specs for the Pointclass where never tested because they are not included in the spec runner. Big fail from my side. Let me fix this!
