### ISSUE TITLE
README.md is a little wrong 

### ISSUE THREAD

**Issue by semi-xi** [wout/svg.js#531]
a grate plugin ！but in the readme.md it maybe has a little wrong 
below the title `bbox() `, if u run the js like
```js
var box1 = draw.rect(100,100).move(50,50)
var box2 = draw.rect(100,100).move(200,200)
var box3 = box1.merge(box2)
```
it will throw ` Uncaught TypeError: box1.merge is not a function` 
because `box` and `box2` are the instance of `SVG.Rect` but not the `SVG.BBox`,so it have not
`merge` method.
the correct maybe is like that
```js
var box1 = draw.rect(100,100).move(50,50).bbox()
var box2 = draw.rect(100,100).move(200,200).bbox()
var box3 = box1.merge(box2)
```

is that right?

**Comment by Fuzzyma** [comment]
Yes. Feel free to create a PR and correct this issue :)
