### ISSUE TITLE
.center() does not work correctly for groups with an origin not at the top left corner

### ISSUE THREAD

**Issue by bryhoyt** [wout/svg.js#96]
When calling .center on a normal element, it calculates the x,y location to position the element's top-left corner at, based on the bbox center. The same is done for groups, which is correct.

However, when the element is positioned, .x() and .y() are used to position the element. For most elements, this correctly positions the top-left corner. However, for groups, it positions the group's origin (0, 0) at the given location (because it works by translating the group by x, y).

Arguably, this what you want for a group's x() and y() methods, though it contradicts the docs for .move() (perhaps it would be better to provide a third 'true' argument, like for the text anchor, in this case).

However you argue the point for .x() and .y(), I think it's definitely incorrect for .center() -- it would only work as documented for groups that happen to have the origin exactly at the top-left corner. That's not necessarily the case.

Arguably, you might want group.center(x, y) to position the group's origin at x, y. But I think what should really happen is that it should position the group's bbox center. However, it currently does neither.

Suggested fix **(note this is buggy, see correct version below)**:

```javascript
SVG.extend(SVG.G, {
  // Move over x-axis
  x: function(x) {
    var bbox = this.bbox();
    var left = bbox.cx - bbox.width/2;
    return x == null ? left : this.transform('x', x-left);
  },
  // Move over y-axis
  y: function(y) {
    var bbox = this.bbox();
    var top = bbox.cy - bbox.height/2;
    return y == null ? top: this.transform('y', y-top);
  }
});
```

**Comment by Fuzzyma** [comment]
@bryhoyt - I assume this issue is solved and can be closed?

**Comment by bryhoyt** [comment]
Yes, thanks.
